// Generated by zebra-selfhost.
// Source: selfhost/Ast.zbr

const std     = @import("std");
const builtin = @import("builtin");
const _zbr_rt = @import("zebra_rt.zig");
pub const panic = std.debug.FullPanic(_zbr_rt._zebra_panic);
const _intern = _zbr_rt._intern;

pub const _zbr_ty_Span = struct {
    line: i64 = undefined,
    col: i64 = undefined,
    end_line: i64 = undefined,
    end_col: i64 = undefined,
    pub fn init(line: i64, col: i64, end_line: i64, end_col: i64) _zbr_ty_Span {
        var _self: _zbr_ty_Span = undefined;
// zbr:selfhost/Ast.zbr:22
            _self.line = line;
// zbr:selfhost/Ast.zbr:23
            _self.col = col;
// zbr:selfhost/Ast.zbr:24
            _self.end_line = end_line;
// zbr:selfhost/Ast.zbr:25
            _self.end_col = end_col;
        return _self;
    }

};

pub const _zbr_ty_Module = struct {
    file: []const u8 = undefined,
    decls: std.ArrayList(_zbr_ty_Decl) = undefined,
    pub fn init(file: []const u8, decls: std.ArrayList(_zbr_ty_Decl)) _zbr_ty_Module {
        var _self: _zbr_ty_Module = undefined;
// zbr:selfhost/Ast.zbr:34
            _self.file = _intern(file);
// zbr:selfhost/Ast.zbr:35
            _self.decls = decls;
        return _self;
    }

};

pub const _zbr_ty_Decl = union(enum) {
    use_: *_zbr_ty_DeclUse,
    namespace_: *_zbr_ty_DeclNamespace,
    class_: *_zbr_ty_DeclClass,
    interface_: *_zbr_ty_DeclInterface,
    struct_: *_zbr_ty_DeclStruct,
    mixin_: *_zbr_ty_DeclMixin,
    enum_: *_zbr_ty_DeclEnum,
    method: *_zbr_ty_DeclMethod,
    var_: *_zbr_ty_DeclVar,
    init: *_zbr_ty_DeclInit,
    extend_: *_zbr_ty_DeclExtend,
    union_: *_zbr_ty_DeclUnion,
    sig_: *_zbr_ty_DeclSig,
    type_alias_: *_zbr_ty_DeclTypeAlias,
};

pub const _zbr_ty_Modifiers = struct {
    is_public: bool = undefined,
    is_private: bool = undefined,
    is_static: bool = undefined,
    is_extern: bool = undefined,
    is_reflectable: bool = undefined,
    is_profile: bool = undefined,
    is_once: bool = undefined,
    is_export: bool = undefined,
    is_derive_debug: bool = undefined,
    is_derive_eq: bool = undefined,
    is_derive_hash: bool = undefined,
    is_pure: bool = undefined,
    is_node_export: bool = undefined,
    is_cue: bool = undefined,
    pub fn init(is_public: bool, is_private: bool, is_static: bool, is_extern: bool, is_reflectable: bool, is_profile: bool, is_once: bool, is_export: bool, is_derive_debug: bool, is_derive_eq: bool, is_derive_hash: bool, is_pure: bool, is_node_export: bool, is_cue: bool) _zbr_ty_Modifiers {
        var _self: _zbr_ty_Modifiers = undefined;
// zbr:selfhost/Ast.zbr:82
            _self.is_public = is_public;
// zbr:selfhost/Ast.zbr:83
            _self.is_private = is_private;
// zbr:selfhost/Ast.zbr:84
            _self.is_static = is_static;
// zbr:selfhost/Ast.zbr:85
            _self.is_extern = is_extern;
// zbr:selfhost/Ast.zbr:86
            _self.is_reflectable = is_reflectable;
// zbr:selfhost/Ast.zbr:87
            _self.is_profile = is_profile;
// zbr:selfhost/Ast.zbr:88
            _self.is_once = is_once;
// zbr:selfhost/Ast.zbr:89
            _self.is_export = is_export;
// zbr:selfhost/Ast.zbr:90
            _self.is_derive_debug = is_derive_debug;
// zbr:selfhost/Ast.zbr:91
            _self.is_derive_eq = is_derive_eq;
// zbr:selfhost/Ast.zbr:92
            _self.is_derive_hash = is_derive_hash;
// zbr:selfhost/Ast.zbr:93
            _self.is_pure = is_pure;
// zbr:selfhost/Ast.zbr:94
            _self.is_node_export = is_node_export;
// zbr:selfhost/Ast.zbr:95
            _self.is_cue = is_cue;
        return _self;
    }

};

pub const _zbr_ty_TypeParam = struct {
    name: []const u8 = undefined,
    constraint: ?[]const u8 = undefined,
    pub fn init(name: []const u8, constraint: ?[]const u8) _zbr_ty_TypeParam {
        var _self: _zbr_ty_TypeParam = undefined;
// zbr:selfhost/Ast.zbr:104
            _self.name = _intern(name);
// zbr:selfhost/Ast.zbr:105
            _self.constraint = constraint;
        return _self;
    }

};

pub const _zbr_ty_DeclUse = struct {
    span: _zbr_ty_Span = undefined,
    path: []const u8 = undefined,
    exposed: std.ArrayList([]const u8) = undefined,
    pub fn init(span: _zbr_ty_Span, path: []const u8, exposed: std.ArrayList([]const u8)) _zbr_ty_DeclUse {
        var _self: _zbr_ty_DeclUse = undefined;
// zbr:selfhost/Ast.zbr:115
            _self.span = span;
// zbr:selfhost/Ast.zbr:116
            _self.path = _intern(path);
// zbr:selfhost/Ast.zbr:117
            _self.exposed = exposed;
        return _self;
    }

};

pub const _zbr_ty_DeclNamespace = struct {
    span: _zbr_ty_Span = undefined,
    name: []const u8 = undefined,
    decls: std.ArrayList(_zbr_ty_Decl) = undefined,
    pub fn init(span: _zbr_ty_Span, name: []const u8, decls: std.ArrayList(_zbr_ty_Decl)) _zbr_ty_DeclNamespace {
        var _self: _zbr_ty_DeclNamespace = undefined;
// zbr:selfhost/Ast.zbr:127
            _self.span = span;
// zbr:selfhost/Ast.zbr:128
            _self.name = _intern(name);
// zbr:selfhost/Ast.zbr:129
            _self.decls = decls;
        return _self;
    }

};

pub const _zbr_ty_DeclClass = struct {
    span: _zbr_ty_Span = undefined,
    mods: _zbr_ty_Modifiers = undefined,
    name: []const u8 = undefined,
    type_params: std.ArrayList(_zbr_ty_TypeParam) = undefined,
    ifaces: std.ArrayList(_zbr_ty_TypeRef) = undefined,
    mixins: std.ArrayList(_zbr_ty_TypeRef) = undefined,
    members: std.ArrayList(_zbr_ty_Decl) = undefined,
    invariants: std.ArrayList(_zbr_ty_Expr) = undefined,
    export_sym: ?[]const u8 = undefined,
    pub fn init(span: _zbr_ty_Span, mods: _zbr_ty_Modifiers, name: []const u8, type_params: std.ArrayList(_zbr_ty_TypeParam), ifaces: std.ArrayList(_zbr_ty_TypeRef), mixins: std.ArrayList(_zbr_ty_TypeRef), members: std.ArrayList(_zbr_ty_Decl), inv_exprs: std.ArrayList(_zbr_ty_Expr), export_sym: ?[]const u8) _zbr_ty_DeclClass {
        var _self: _zbr_ty_DeclClass = undefined;
// zbr:selfhost/Ast.zbr:145
            _self.span = span;
// zbr:selfhost/Ast.zbr:146
            _self.mods = mods;
// zbr:selfhost/Ast.zbr:147
            _self.name = _intern(name);
// zbr:selfhost/Ast.zbr:148
            _self.type_params = type_params;
// zbr:selfhost/Ast.zbr:149
            _self.ifaces = ifaces;
// zbr:selfhost/Ast.zbr:150
            _self.mixins = mixins;
// zbr:selfhost/Ast.zbr:151
            _self.members = members;
// zbr:selfhost/Ast.zbr:152
            _self.invariants = inv_exprs;
// zbr:selfhost/Ast.zbr:153
            _self.export_sym = export_sym;
        return _self;
    }

};

pub const _zbr_ty_DeclInterface = struct {
    span: _zbr_ty_Span = undefined,
    mods: _zbr_ty_Modifiers = undefined,
    name: []const u8 = undefined,
    ifaces: std.ArrayList(_zbr_ty_TypeRef) = undefined,
    members: std.ArrayList(_zbr_ty_Decl) = undefined,
    type_params: std.ArrayList(_zbr_ty_TypeParam) = undefined,
    pub fn init(span: _zbr_ty_Span, mods: _zbr_ty_Modifiers, name: []const u8, ifaces: std.ArrayList(_zbr_ty_TypeRef), members: std.ArrayList(_zbr_ty_Decl), type_params: std.ArrayList(_zbr_ty_TypeParam)) _zbr_ty_DeclInterface {
        var _self: _zbr_ty_DeclInterface = undefined;
// zbr:selfhost/Ast.zbr:166
            _self.span = span;
// zbr:selfhost/Ast.zbr:167
            _self.mods = mods;
// zbr:selfhost/Ast.zbr:168
            _self.name = _intern(name);
// zbr:selfhost/Ast.zbr:169
            _self.ifaces = ifaces;
// zbr:selfhost/Ast.zbr:170
            _self.members = members;
// zbr:selfhost/Ast.zbr:171
            _self.type_params = type_params;
        return _self;
    }

};

pub const _zbr_ty_DeclStruct = struct {
    span: _zbr_ty_Span = undefined,
    mods: _zbr_ty_Modifiers = undefined,
    name: []const u8 = undefined,
    ifaces: std.ArrayList(_zbr_ty_TypeRef) = undefined,
    members: std.ArrayList(_zbr_ty_Decl) = undefined,
    invariants: std.ArrayList(_zbr_ty_Expr) = undefined,
    pub fn init(span: _zbr_ty_Span, mods: _zbr_ty_Modifiers, name: []const u8, ifaces: std.ArrayList(_zbr_ty_TypeRef), members: std.ArrayList(_zbr_ty_Decl), inv_exprs: std.ArrayList(_zbr_ty_Expr)) _zbr_ty_DeclStruct {
        var _self: _zbr_ty_DeclStruct = undefined;
// zbr:selfhost/Ast.zbr:184
            _self.span = span;
// zbr:selfhost/Ast.zbr:185
            _self.mods = mods;
// zbr:selfhost/Ast.zbr:186
            _self.name = _intern(name);
// zbr:selfhost/Ast.zbr:187
            _self.ifaces = ifaces;
// zbr:selfhost/Ast.zbr:188
            _self.members = members;
// zbr:selfhost/Ast.zbr:189
            _self.invariants = inv_exprs;
        return _self;
    }

};

pub const _zbr_ty_DeclMixin = struct {
    span: _zbr_ty_Span = undefined,
    mods: _zbr_ty_Modifiers = undefined,
    name: []const u8 = undefined,
    members: std.ArrayList(_zbr_ty_Decl) = undefined,
    pub fn init(span: _zbr_ty_Span, mods: _zbr_ty_Modifiers, name: []const u8, members: std.ArrayList(_zbr_ty_Decl)) _zbr_ty_DeclMixin {
        var _self: _zbr_ty_DeclMixin = undefined;
// zbr:selfhost/Ast.zbr:200
            _self.span = span;
// zbr:selfhost/Ast.zbr:201
            _self.mods = mods;
// zbr:selfhost/Ast.zbr:202
            _self.name = _intern(name);
// zbr:selfhost/Ast.zbr:203
            _self.members = members;
        return _self;
    }

};

pub const _zbr_ty_EnumMember = struct {
    span: _zbr_ty_Span = undefined,
    name: []const u8 = undefined,
    value: ?*_zbr_ty_Expr = undefined,
    pub fn init(span: _zbr_ty_Span, name: []const u8, value: ?*_zbr_ty_Expr) _zbr_ty_EnumMember {
        var _self: _zbr_ty_EnumMember = undefined;
// zbr:selfhost/Ast.zbr:213
            _self.span = span;
// zbr:selfhost/Ast.zbr:214
            _self.name = _intern(name);
// zbr:selfhost/Ast.zbr:215
            _self.value = value;
        return _self;
    }

};

pub const _zbr_ty_DeclEnum = struct {
    span: _zbr_ty_Span = undefined,
    mods: _zbr_ty_Modifiers = undefined,
    name: []const u8 = undefined,
    base: ?_zbr_ty_TypeRef = undefined,
    members: std.ArrayList(_zbr_ty_EnumMember) = undefined,
    pub fn init(span: _zbr_ty_Span, mods: _zbr_ty_Modifiers, name: []const u8, base: ?_zbr_ty_TypeRef, members: std.ArrayList(_zbr_ty_EnumMember)) _zbr_ty_DeclEnum {
        var _self: _zbr_ty_DeclEnum = undefined;
// zbr:selfhost/Ast.zbr:225
            _self.span = span;
// zbr:selfhost/Ast.zbr:226
            _self.mods = mods;
// zbr:selfhost/Ast.zbr:227
            _self.name = _intern(name);
// zbr:selfhost/Ast.zbr:228
            _self.base = base;
// zbr:selfhost/Ast.zbr:229
            _self.members = members;
        return _self;
    }

};

pub const _zbr_ty_DeclExtend = struct {
    span: _zbr_ty_Span = undefined,
    target: _zbr_ty_TypeRef = undefined,
    members: std.ArrayList(_zbr_ty_Decl) = undefined,
    pub fn init(span: _zbr_ty_Span, target: _zbr_ty_TypeRef, members: std.ArrayList(_zbr_ty_Decl)) _zbr_ty_DeclExtend {
        var _self: _zbr_ty_DeclExtend = undefined;
// zbr:selfhost/Ast.zbr:239
            _self.span = span;
// zbr:selfhost/Ast.zbr:240
            _self.target = target;
// zbr:selfhost/Ast.zbr:241
            _self.members = members;
        return _self;
    }

};

pub const _zbr_ty_UnionVariant = struct {
    span: _zbr_ty_Span = undefined,
    name: []const u8 = undefined,
    payload: ?_zbr_ty_TypeRef = undefined,
    pub fn init(span: _zbr_ty_Span, name: []const u8, payload: ?_zbr_ty_TypeRef) _zbr_ty_UnionVariant {
        var _self: _zbr_ty_UnionVariant = undefined;
// zbr:selfhost/Ast.zbr:251
            _self.span = span;
// zbr:selfhost/Ast.zbr:252
            _self.name = _intern(name);
// zbr:selfhost/Ast.zbr:253
            _self.payload = payload;
        return _self;
    }

};

pub const _zbr_ty_DeclUnion = struct {
    span: _zbr_ty_Span = undefined,
    mods: _zbr_ty_Modifiers = undefined,
    name: []const u8 = undefined,
    variants: std.ArrayList(_zbr_ty_UnionVariant) = undefined,
    pub fn init(span: _zbr_ty_Span, mods: _zbr_ty_Modifiers, name: []const u8, variants: std.ArrayList(_zbr_ty_UnionVariant)) _zbr_ty_DeclUnion {
        var _self: _zbr_ty_DeclUnion = undefined;
// zbr:selfhost/Ast.zbr:262
            _self.span = span;
// zbr:selfhost/Ast.zbr:263
            _self.mods = mods;
// zbr:selfhost/Ast.zbr:264
            _self.name = _intern(name);
// zbr:selfhost/Ast.zbr:265
            _self.variants = variants;
        return _self;
    }

};

pub const _zbr_ty_DeclTypeAlias = struct {
    span: _zbr_ty_Span = undefined,
    name: []const u8 = undefined,
    params: std.ArrayList(_zbr_ty_Param) = undefined,
    base: _zbr_ty_TypeRef = undefined,
    constraint: ?*_zbr_ty_Expr = undefined,
    pub fn init(span: _zbr_ty_Span, name: []const u8, params: std.ArrayList(_zbr_ty_Param), base: _zbr_ty_TypeRef, constraint: ?*_zbr_ty_Expr) _zbr_ty_DeclTypeAlias {
        var _self: _zbr_ty_DeclTypeAlias = undefined;
// zbr:selfhost/Ast.zbr:277
            _self.span = span;
// zbr:selfhost/Ast.zbr:278
            _self.name = _intern(name);
// zbr:selfhost/Ast.zbr:279
            _self.params = params;
// zbr:selfhost/Ast.zbr:280
            _self.base = base;
// zbr:selfhost/Ast.zbr:281
            _self.constraint = constraint;
        return _self;
    }

};

pub const _zbr_ty_DeclSig = struct {
    span: _zbr_ty_Span = undefined,
    name: []const u8 = undefined,
    params: std.ArrayList(_zbr_ty_Param) = undefined,
    return_type: ?_zbr_ty_TypeRef = undefined,
    pub fn init(span: _zbr_ty_Span, name: []const u8, params: std.ArrayList(_zbr_ty_Param), return_type: ?_zbr_ty_TypeRef) _zbr_ty_DeclSig {
        var _self: _zbr_ty_DeclSig = undefined;
// zbr:selfhost/Ast.zbr:292
            _self.span = span;
// zbr:selfhost/Ast.zbr:293
            _self.name = _intern(name);
// zbr:selfhost/Ast.zbr:294
            _self.params = params;
// zbr:selfhost/Ast.zbr:295
            _self.return_type = return_type;
        return _self;
    }

};

pub const _zbr_ty_DeclMethod = struct {
    span: _zbr_ty_Span = undefined,
    mods: _zbr_ty_Modifiers = undefined,
    name: []const u8 = undefined,
    type_params: std.ArrayList([]const u8) = undefined,
    params: std.ArrayList(_zbr_ty_Param) = undefined,
    return_type: ?_zbr_ty_TypeRef = undefined,
    stmts: ?std.ArrayList(_zbr_ty_Stmt) = undefined,
    is_test: bool = undefined,
    throws_: bool = undefined,
    require_: std.ArrayList(_zbr_ty_Expr) = undefined,
    ensure_: std.ArrayList(_zbr_ty_Expr) = undefined,
    tags: std.ArrayList([]const u8) = undefined,
    deprecated: []const u8 = undefined,
    pub fn init(span: _zbr_ty_Span, mods: _zbr_ty_Modifiers, name: []const u8, type_params: std.ArrayList([]const u8), params: std.ArrayList(_zbr_ty_Param), return_type: ?_zbr_ty_TypeRef, stmts: ?std.ArrayList(_zbr_ty_Stmt), is_test: bool, throws_: bool, require_: std.ArrayList(_zbr_ty_Expr), ensure_: std.ArrayList(_zbr_ty_Expr), tags: std.ArrayList([]const u8), deprecated: []const u8) _zbr_ty_DeclMethod {
        var _self: _zbr_ty_DeclMethod = undefined;
// zbr:selfhost/Ast.zbr:315
            _self.deprecated = _intern(deprecated);
// zbr:selfhost/Ast.zbr:316
            _self.span = span;
// zbr:selfhost/Ast.zbr:317
            _self.mods = mods;
// zbr:selfhost/Ast.zbr:318
            _self.name = _intern(name);
// zbr:selfhost/Ast.zbr:319
            _self.type_params = type_params;
// zbr:selfhost/Ast.zbr:320
            _self.params = params;
// zbr:selfhost/Ast.zbr:321
            _self.return_type = return_type;
// zbr:selfhost/Ast.zbr:322
            _self.stmts = stmts;
// zbr:selfhost/Ast.zbr:323
            _self.is_test = is_test;
// zbr:selfhost/Ast.zbr:324
            _self.throws_ = throws_;
// zbr:selfhost/Ast.zbr:325
            _self.require_ = require_;
// zbr:selfhost/Ast.zbr:326
            _self.ensure_ = ensure_;
// zbr:selfhost/Ast.zbr:327
            _self.tags = tags;
        return _self;
    }

};

pub const _zbr_ty_DeclVar = struct {
    span: _zbr_ty_Span = undefined,
    mods: _zbr_ty_Modifiers = undefined,
    name: []const u8 = undefined,
    type_: ?_zbr_ty_TypeRef = undefined,
    init_expr: ?*_zbr_ty_Expr = undefined,
    is_const: bool = undefined,
    pub fn init(span: _zbr_ty_Span, mods: _zbr_ty_Modifiers, name: []const u8, type_: ?_zbr_ty_TypeRef, init_expr: ?*_zbr_ty_Expr, is_const: bool) _zbr_ty_DeclVar {
        var _self: _zbr_ty_DeclVar = undefined;
// zbr:selfhost/Ast.zbr:340
            _self.span = span;
// zbr:selfhost/Ast.zbr:341
            _self.mods = mods;
// zbr:selfhost/Ast.zbr:342
            _self.name = _intern(name);
// zbr:selfhost/Ast.zbr:343
            _self.type_ = type_;
// zbr:selfhost/Ast.zbr:344
            _self.init_expr = init_expr;
// zbr:selfhost/Ast.zbr:345
            _self.is_const = is_const;
        return _self;
    }

};

pub const _zbr_ty_DeclInit = struct {
    span: _zbr_ty_Span = undefined,
    mods: _zbr_ty_Modifiers = undefined,
    params: std.ArrayList(_zbr_ty_Param) = undefined,
    stmts: ?std.ArrayList(_zbr_ty_Stmt) = undefined,
    require_: std.ArrayList(_zbr_ty_Expr) = undefined,
    ensure_: std.ArrayList(_zbr_ty_Expr) = undefined,
    pub fn init(span: _zbr_ty_Span, mods: _zbr_ty_Modifiers, params: std.ArrayList(_zbr_ty_Param), stmts: ?std.ArrayList(_zbr_ty_Stmt), require_: std.ArrayList(_zbr_ty_Expr), ensure_: std.ArrayList(_zbr_ty_Expr)) _zbr_ty_DeclInit {
        var _self: _zbr_ty_DeclInit = undefined;
// zbr:selfhost/Ast.zbr:358
            _self.span = span;
// zbr:selfhost/Ast.zbr:359
            _self.mods = mods;
// zbr:selfhost/Ast.zbr:360
            _self.params = params;
// zbr:selfhost/Ast.zbr:361
            _self.stmts = stmts;
// zbr:selfhost/Ast.zbr:362
            _self.require_ = require_;
// zbr:selfhost/Ast.zbr:363
            _self.ensure_ = ensure_;
        return _self;
    }

};

pub const _zbr_ty_ParamMode = enum {
    normal,
    variadic,
};

pub const _zbr_ty_Param = struct {
    span: _zbr_ty_Span = undefined,
    mode: _zbr_ty_ParamMode = undefined,
    name: []const u8 = undefined,
    type_: ?_zbr_ty_TypeRef = undefined,
    default_: ?*_zbr_ty_Expr = undefined,
    pub fn init(span: _zbr_ty_Span, mode: _zbr_ty_ParamMode, name: []const u8, type_: ?_zbr_ty_TypeRef, default_: ?*_zbr_ty_Expr) _zbr_ty_Param {
        var _self: _zbr_ty_Param = undefined;
// zbr:selfhost/Ast.zbr:379
            _self.span = span;
// zbr:selfhost/Ast.zbr:380
            _self.mode = mode;
// zbr:selfhost/Ast.zbr:381
            _self.name = _intern(name);
// zbr:selfhost/Ast.zbr:382
            _self.type_ = type_;
// zbr:selfhost/Ast.zbr:383
            _self.default_ = default_;
        return _self;
    }

};

pub const _zbr_ty_TypeRef = union(enum) {
    named: _zbr_ty_NamedTypeRef,
    nilable: *_zbr_ty_TypeRef,
    stream: *_zbr_ty_TypeRef,
    error_union: *_zbr_ty_TypeRef,
    ref_to: *_zbr_ty_TypeRef,
    generic: _zbr_ty_GenericTypeRef,
    void_,
    tuple: _zbr_ty_TupleTypeRef,
    alias_applied: _zbr_ty_AliasAppliedTypeRef,
    fn_type: _zbr_ty_FnTypeRef,
};

pub const _zbr_ty_FnTypeRef = struct {
    span: _zbr_ty_Span = undefined,
    params: std.ArrayList(_zbr_ty_TypeRef) = undefined,
    ret: *_zbr_ty_TypeRef = undefined,
    pub fn init(span: _zbr_ty_Span, params: std.ArrayList(_zbr_ty_TypeRef), ret: *_zbr_ty_TypeRef) _zbr_ty_FnTypeRef {
        var _self: _zbr_ty_FnTypeRef = undefined;
// zbr:selfhost/Ast.zbr:407
            _self.span = span;
// zbr:selfhost/Ast.zbr:408
            _self.params = params;
// zbr:selfhost/Ast.zbr:409
            _self.ret = ret;
        return _self;
    }

};

pub const _zbr_ty_NamedTypeRef = struct {
    span: _zbr_ty_Span = undefined,
    name: []const u8 = undefined,
    pub fn init(span: _zbr_ty_Span, name: []const u8) _zbr_ty_NamedTypeRef {
        var _self: _zbr_ty_NamedTypeRef = undefined;
// zbr:selfhost/Ast.zbr:416
            _self.span = span;
// zbr:selfhost/Ast.zbr:417
            _self.name = _intern(name);
        return _self;
    }

};

pub const _zbr_ty_GenericTypeRef = struct {
    span: _zbr_ty_Span = undefined,
    name: []const u8 = undefined,
    args: std.ArrayList(_zbr_ty_TypeRef) = undefined,
    pub fn init(span: _zbr_ty_Span, name: []const u8, args: std.ArrayList(_zbr_ty_TypeRef)) _zbr_ty_GenericTypeRef {
        var _self: _zbr_ty_GenericTypeRef = undefined;
// zbr:selfhost/Ast.zbr:425
            _self.span = span;
// zbr:selfhost/Ast.zbr:426
            _self.name = _intern(name);
// zbr:selfhost/Ast.zbr:427
            _self.args = args;
        return _self;
    }

};

pub const _zbr_ty_TupleTypeRef = struct {
    span: _zbr_ty_Span = undefined,
    elems: std.ArrayList(_zbr_ty_TypeRef) = undefined,
    pub fn init(span: _zbr_ty_Span, elems: std.ArrayList(_zbr_ty_TypeRef)) _zbr_ty_TupleTypeRef {
        var _self: _zbr_ty_TupleTypeRef = undefined;
// zbr:selfhost/Ast.zbr:434
            _self.span = span;
// zbr:selfhost/Ast.zbr:435
            _self.elems = elems;
        return _self;
    }

};

pub const _zbr_ty_AliasAppliedTypeRef = struct {
    span: _zbr_ty_Span = undefined,
    name: []const u8 = undefined,
    args: std.ArrayList(_zbr_ty_Expr) = undefined,
    pub fn init(span: _zbr_ty_Span, name: []const u8, args: std.ArrayList(_zbr_ty_Expr)) _zbr_ty_AliasAppliedTypeRef {
        var _self: _zbr_ty_AliasAppliedTypeRef = undefined;
// zbr:selfhost/Ast.zbr:443
            _self.span = span;
// zbr:selfhost/Ast.zbr:444
            _self.name = _intern(name);
// zbr:selfhost/Ast.zbr:445
            _self.args = args;
        return _self;
    }

};

pub const _zbr_ty_AssignOp = enum {
    assign,
    plus_eq,
    minus_eq,
    star_eq,
    slash_eq,
    slashslash_eq,
    percent_eq,
    starstar_eq,
    ampersand_eq,
    vertical_bar_eq,
    caret_eq,
    double_lt_eq,
    double_gt_eq,
};

pub const _zbr_ty_Stmt = union(enum) {
    if_: *_zbr_ty_StmtIf,
    while_: *_zbr_ty_StmtWhile,
    for_in: *_zbr_ty_StmtForIn,
    for_num: *_zbr_ty_StmtForNum,
    branch_: *_zbr_ty_StmtBranch,
    return_: *_zbr_ty_StmtReturn,
    assert_: *_zbr_ty_StmtAssert,
    pass_: _zbr_ty_Span,
    break_: _zbr_ty_Span,
    continue_: _zbr_ty_Span,
    assign: *_zbr_ty_StmtAssign,
    var_: *_zbr_ty_DeclVar,
    expr: *_zbr_ty_Expr,
    with_: *_zbr_ty_StmtWith,
    in_scope: *_zbr_ty_StmtIn,
    raise_: *_zbr_ty_StmtRaise,
    try_catch: *_zbr_ty_StmtTryCatch,
    destruct: *_zbr_ty_StmtDestruct,
    allocate_: *_zbr_ty_StmtAllocate,
    copy_out: *_zbr_ty_StmtCopyOut,
    print_: *_zbr_ty_StmtPrint,
    contract: *_zbr_ty_StmtContract,
    yield_: *_zbr_ty_StmtYield,
};

pub const _zbr_ty_ElseIf = struct {
    span: _zbr_ty_Span = undefined,
    cond: _zbr_ty_Expr = undefined,
    is_capture: ?[]const u8 = undefined,
    stmts: std.ArrayList(_zbr_ty_Stmt) = undefined,
    pub fn init(span: _zbr_ty_Span, cond: _zbr_ty_Expr, stmts: std.ArrayList(_zbr_ty_Stmt)) _zbr_ty_ElseIf {
        var _self: _zbr_ty_ElseIf = undefined;
// zbr:selfhost/Ast.zbr:499
            _self.span = span;
// zbr:selfhost/Ast.zbr:500
            _self.cond = cond;
// zbr:selfhost/Ast.zbr:501
            _self.is_capture = null;
// zbr:selfhost/Ast.zbr:502
            _self.stmts = stmts;
        return _self;
    }

};

pub const _zbr_ty_StmtIf = struct {
    span: _zbr_ty_Span = undefined,
    cond: *_zbr_ty_Expr = undefined,
    is_capture: ?[]const u8 = undefined,
    then_stmts: std.ArrayList(_zbr_ty_Stmt) = undefined,
    else_ifs: std.ArrayList(_zbr_ty_ElseIf) = undefined,
    else_stmts: ?std.ArrayList(_zbr_ty_Stmt) = undefined,
    pub fn init(span: _zbr_ty_Span, cond: *_zbr_ty_Expr, then_stmts: std.ArrayList(_zbr_ty_Stmt), else_ifs: std.ArrayList(_zbr_ty_ElseIf), else_stmts: ?std.ArrayList(_zbr_ty_Stmt)) _zbr_ty_StmtIf {
        var _self: _zbr_ty_StmtIf = undefined;
// zbr:selfhost/Ast.zbr:513
            _self.span = span;
// zbr:selfhost/Ast.zbr:514
            _self.cond = cond;
// zbr:selfhost/Ast.zbr:515
            _self.is_capture = null;
// zbr:selfhost/Ast.zbr:516
            _self.then_stmts = then_stmts;
// zbr:selfhost/Ast.zbr:517
            _self.else_ifs = else_ifs;
// zbr:selfhost/Ast.zbr:518
            _self.else_stmts = else_stmts;
        return _self;
    }

};

pub const _zbr_ty_StmtWhile = struct {
    span: _zbr_ty_Span = undefined,
    cond: *_zbr_ty_Expr = undefined,
    stmts: std.ArrayList(_zbr_ty_Stmt) = undefined,
    pub fn init(span: _zbr_ty_Span, cond: *_zbr_ty_Expr, stmts: std.ArrayList(_zbr_ty_Stmt)) _zbr_ty_StmtWhile {
        var _self: _zbr_ty_StmtWhile = undefined;
// zbr:selfhost/Ast.zbr:526
            _self.span = span;
// zbr:selfhost/Ast.zbr:527
            _self.cond = cond;
// zbr:selfhost/Ast.zbr:528
            _self.stmts = stmts;
        return _self;
    }

};

pub const _zbr_ty_StmtForIn = struct {
    span: _zbr_ty_Span = undefined,
    vars: std.ArrayList([]const u8) = undefined,
    iter: *_zbr_ty_Expr = undefined,
    filter: ?*_zbr_ty_Expr = undefined,
    stmts: std.ArrayList(_zbr_ty_Stmt) = undefined,
    else_: ?std.ArrayList(_zbr_ty_Stmt) = undefined,
    pub fn init(span: _zbr_ty_Span, vars: std.ArrayList([]const u8), iter: *_zbr_ty_Expr, filter: ?*_zbr_ty_Expr, stmts: std.ArrayList(_zbr_ty_Stmt), else_: ?std.ArrayList(_zbr_ty_Stmt)) _zbr_ty_StmtForIn {
        var _self: _zbr_ty_StmtForIn = undefined;
// zbr:selfhost/Ast.zbr:539
            _self.span = span;
// zbr:selfhost/Ast.zbr:540
            _self.vars = vars;
// zbr:selfhost/Ast.zbr:541
            _self.iter = iter;
// zbr:selfhost/Ast.zbr:542
            _self.filter = filter;
// zbr:selfhost/Ast.zbr:543
            _self.stmts = stmts;
// zbr:selfhost/Ast.zbr:544
            _self.else_ = else_;
        return _self;
    }

};

pub const _zbr_ty_StmtForNum = struct {
    span: _zbr_ty_Span = undefined,
    var_: []const u8 = undefined,
    start: *_zbr_ty_Expr = undefined,
    stop_: *_zbr_ty_Expr = undefined,
    step: ?*_zbr_ty_Expr = undefined,
    stmts: std.ArrayList(_zbr_ty_Stmt) = undefined,
    else_: ?std.ArrayList(_zbr_ty_Stmt) = undefined,
    pub fn init(span: _zbr_ty_Span, var_: []const u8, start: *_zbr_ty_Expr, stop_: *_zbr_ty_Expr, step: ?*_zbr_ty_Expr, stmts: std.ArrayList(_zbr_ty_Stmt), else_: ?std.ArrayList(_zbr_ty_Stmt)) _zbr_ty_StmtForNum {
        var _self: _zbr_ty_StmtForNum = undefined;
// zbr:selfhost/Ast.zbr:556
            _self.span = span;
// zbr:selfhost/Ast.zbr:557
            _self.var_ = _intern(var_);
// zbr:selfhost/Ast.zbr:558
            _self.start = start;
// zbr:selfhost/Ast.zbr:559
            _self.stop_ = stop_;
// zbr:selfhost/Ast.zbr:560
            _self.step = step;
// zbr:selfhost/Ast.zbr:561
            _self.stmts = stmts;
// zbr:selfhost/Ast.zbr:562
            _self.else_ = else_;
        return _self;
    }

};

pub const _zbr_ty_StructFieldPat = struct {
    name: []const u8 = undefined,
    value: _zbr_ty_Expr = undefined,
    pub fn init(name: []const u8, value: _zbr_ty_Expr) _zbr_ty_StructFieldPat {
        var _self: _zbr_ty_StructFieldPat = undefined;
// zbr:selfhost/Ast.zbr:569
            _self.name = _intern(name);
// zbr:selfhost/Ast.zbr:570
            _self.value = value;
        return _self;
    }

};

pub const _zbr_ty_StructPat = struct {
    type_name: []const u8 = undefined,
    fields: std.ArrayList(_zbr_ty_StructFieldPat) = undefined,
    pub fn init(type_name: []const u8, fields: std.ArrayList(_zbr_ty_StructFieldPat)) _zbr_ty_StructPat {
        var _self: _zbr_ty_StructPat = undefined;
// zbr:selfhost/Ast.zbr:577
            _self.type_name = _intern(type_name);
// zbr:selfhost/Ast.zbr:578
            _self.fields = fields;
        return _self;
    }

};

pub const _zbr_ty_BranchOn = struct {
    span: _zbr_ty_Span = undefined,
    values: std.ArrayList(_zbr_ty_Expr) = undefined,
    stmts: std.ArrayList(_zbr_ty_Stmt) = undefined,
    binding: ?[]const u8 = undefined,
    guard_expr: std.ArrayList(_zbr_ty_Expr) = undefined,
    struct_pat: ?_zbr_ty_StructPat = undefined,
    pub fn init(span: _zbr_ty_Span, values: std.ArrayList(_zbr_ty_Expr), stmts: std.ArrayList(_zbr_ty_Stmt), binding: ?[]const u8, guard_expr: std.ArrayList(_zbr_ty_Expr)) _zbr_ty_BranchOn {
        var _self: _zbr_ty_BranchOn = undefined;
// zbr:selfhost/Ast.zbr:589
            _self.span = span;
// zbr:selfhost/Ast.zbr:590
            _self.values = values;
// zbr:selfhost/Ast.zbr:591
            _self.stmts = stmts;
// zbr:selfhost/Ast.zbr:592
            _self.binding = binding;
// zbr:selfhost/Ast.zbr:593
            _self.guard_expr = guard_expr;
// zbr:selfhost/Ast.zbr:594
            _self.struct_pat = null;
        return _self;
    }

};

pub const _zbr_ty_StmtBranch = struct {
    span: _zbr_ty_Span = undefined,
    expr: *_zbr_ty_Expr = undefined,
    cases: std.ArrayList(_zbr_ty_BranchOn) = undefined,
    else_: ?std.ArrayList(_zbr_ty_Stmt) = undefined,
    pub fn init(span: _zbr_ty_Span, expr: *_zbr_ty_Expr, cases: std.ArrayList(_zbr_ty_BranchOn), else_: ?std.ArrayList(_zbr_ty_Stmt)) _zbr_ty_StmtBranch {
        var _self: _zbr_ty_StmtBranch = undefined;
// zbr:selfhost/Ast.zbr:603
            _self.span = span;
// zbr:selfhost/Ast.zbr:604
            _self.expr = expr;
// zbr:selfhost/Ast.zbr:605
            _self.cases = cases;
// zbr:selfhost/Ast.zbr:606
            _self.else_ = else_;
        return _self;
    }

};

pub const _zbr_ty_StmtReturn = struct {
    span: _zbr_ty_Span = undefined,
    value: ?*_zbr_ty_Expr = undefined,
    pub fn init(span: _zbr_ty_Span, value: ?*_zbr_ty_Expr) _zbr_ty_StmtReturn {
        var _self: _zbr_ty_StmtReturn = undefined;
// zbr:selfhost/Ast.zbr:613
            _self.span = span;
// zbr:selfhost/Ast.zbr:614
            _self.value = value;
        return _self;
    }

};

pub const _zbr_ty_StmtYield = struct {
    span: _zbr_ty_Span = undefined,
    value: *_zbr_ty_Expr = undefined,
    pub fn init(span: _zbr_ty_Span, value: *_zbr_ty_Expr) _zbr_ty_StmtYield {
        var _self: _zbr_ty_StmtYield = undefined;
// zbr:selfhost/Ast.zbr:622
            _self.span = span;
// zbr:selfhost/Ast.zbr:623
            _self.value = value;
        return _self;
    }

};

pub const _zbr_ty_StmtAssert = struct {
    span: _zbr_ty_Span = undefined,
    cond: *_zbr_ty_Expr = undefined,
    message: ?*_zbr_ty_Expr = undefined,
    pub fn init(span: _zbr_ty_Span, cond: *_zbr_ty_Expr, message: ?*_zbr_ty_Expr) _zbr_ty_StmtAssert {
        var _self: _zbr_ty_StmtAssert = undefined;
// zbr:selfhost/Ast.zbr:631
            _self.span = span;
// zbr:selfhost/Ast.zbr:632
            _self.cond = cond;
// zbr:selfhost/Ast.zbr:633
            _self.message = message;
        return _self;
    }

};

pub const _zbr_ty_StmtAssign = struct {
    span: _zbr_ty_Span = undefined,
    target: *_zbr_ty_Expr = undefined,
    op: _zbr_ty_AssignOp = undefined,
    value: *_zbr_ty_Expr = undefined,
    pub fn init(span: _zbr_ty_Span, target: *_zbr_ty_Expr, op: _zbr_ty_AssignOp, value: *_zbr_ty_Expr) _zbr_ty_StmtAssign {
        var _self: _zbr_ty_StmtAssign = undefined;
// zbr:selfhost/Ast.zbr:642
            _self.span = span;
// zbr:selfhost/Ast.zbr:643
            _self.target = target;
// zbr:selfhost/Ast.zbr:644
            _self.op = op;
// zbr:selfhost/Ast.zbr:645
            _self.value = value;
        return _self;
    }

};

pub const _zbr_ty_StmtWith = struct {
    span: _zbr_ty_Span = undefined,
    target: *_zbr_ty_Expr = undefined,
    stmts: std.ArrayList(_zbr_ty_Stmt) = undefined,
    pub fn init(span: _zbr_ty_Span, target: *_zbr_ty_Expr, stmts: std.ArrayList(_zbr_ty_Stmt)) _zbr_ty_StmtWith {
        var _self: _zbr_ty_StmtWith = undefined;
// zbr:selfhost/Ast.zbr:653
            _self.span = span;
// zbr:selfhost/Ast.zbr:654
            _self.target = target;
// zbr:selfhost/Ast.zbr:655
            _self.stmts = stmts;
        return _self;
    }

};

pub const _zbr_ty_StmtIn = struct {
    span: _zbr_ty_Span = undefined,
    expr: *_zbr_ty_Expr = undefined,
    stmts: std.ArrayList(_zbr_ty_Stmt) = undefined,
    pub fn init(span: _zbr_ty_Span, expr: *_zbr_ty_Expr, stmts: std.ArrayList(_zbr_ty_Stmt)) _zbr_ty_StmtIn {
        var _self: _zbr_ty_StmtIn = undefined;
// zbr:selfhost/Ast.zbr:663
            _self.span = span;
// zbr:selfhost/Ast.zbr:664
            _self.expr = expr;
// zbr:selfhost/Ast.zbr:665
            _self.stmts = stmts;
        return _self;
    }

};

pub const _zbr_ty_StmtRaise = struct {
    span: _zbr_ty_Span = undefined,
    message: ?*_zbr_ty_Expr = undefined,
    details: ?*_zbr_ty_Expr = undefined,
    pub fn init(span: _zbr_ty_Span, message: ?*_zbr_ty_Expr, details: ?*_zbr_ty_Expr) _zbr_ty_StmtRaise {
        var _self: _zbr_ty_StmtRaise = undefined;
// zbr:selfhost/Ast.zbr:673
            _self.span = span;
// zbr:selfhost/Ast.zbr:674
            _self.message = message;
// zbr:selfhost/Ast.zbr:675
            _self.details = details;
        return _self;
    }

};

pub const _zbr_ty_CatchClause = struct {
    span: _zbr_ty_Span = undefined,
    binding: ?[]const u8 = undefined,
    type_: ?_zbr_ty_TypeRef = undefined,
    stmts: std.ArrayList(_zbr_ty_Stmt) = undefined,
    pub fn init(span: _zbr_ty_Span, binding: ?[]const u8, type_: ?_zbr_ty_TypeRef, stmts: std.ArrayList(_zbr_ty_Stmt)) _zbr_ty_CatchClause {
        var _self: _zbr_ty_CatchClause = undefined;
// zbr:selfhost/Ast.zbr:684
            _self.span = span;
// zbr:selfhost/Ast.zbr:685
            _self.binding = binding;
// zbr:selfhost/Ast.zbr:686
            _self.type_ = type_;
// zbr:selfhost/Ast.zbr:687
            _self.stmts = stmts;
        return _self;
    }

};

pub const _zbr_ty_StmtTryCatch = struct {
    span: _zbr_ty_Span = undefined,
    stmts: std.ArrayList(_zbr_ty_Stmt) = undefined,
    clauses: std.ArrayList(_zbr_ty_CatchClause) = undefined,
    pub fn init(span: _zbr_ty_Span, stmts: std.ArrayList(_zbr_ty_Stmt), clauses: std.ArrayList(_zbr_ty_CatchClause)) _zbr_ty_StmtTryCatch {
        var _self: _zbr_ty_StmtTryCatch = undefined;
// zbr:selfhost/Ast.zbr:695
            _self.span = span;
// zbr:selfhost/Ast.zbr:696
            _self.stmts = stmts;
// zbr:selfhost/Ast.zbr:697
            _self.clauses = clauses;
        return _self;
    }

};

pub const _zbr_ty_StmtDestruct = struct {
    span: _zbr_ty_Span = undefined,
    names: std.ArrayList([]const u8) = undefined,
    init_expr: *_zbr_ty_Expr = undefined,
    is_struct: bool = undefined,
    pub fn init(span: _zbr_ty_Span, names: std.ArrayList([]const u8), init_expr: *_zbr_ty_Expr, is_struct: bool) _zbr_ty_StmtDestruct {
        var _self: _zbr_ty_StmtDestruct = undefined;
// zbr:selfhost/Ast.zbr:706
            _self.span = span;
// zbr:selfhost/Ast.zbr:707
            _self.names = names;
// zbr:selfhost/Ast.zbr:708
            _self.init_expr = init_expr;
// zbr:selfhost/Ast.zbr:709
            _self.is_struct = is_struct;
        return _self;
    }

};

pub const _zbr_ty_StmtAllocate = struct {
    span: _zbr_ty_Span = undefined,
    source: _zbr_ty_Expr = undefined,
    is_scoped: bool = undefined,
    stmts: std.ArrayList(_zbr_ty_Stmt) = undefined,
    pub fn init(span: _zbr_ty_Span, source: _zbr_ty_Expr, is_scoped: bool, stmts: std.ArrayList(_zbr_ty_Stmt)) _zbr_ty_StmtAllocate {
        var _self: _zbr_ty_StmtAllocate = undefined;
// zbr:selfhost/Ast.zbr:718
            _self.span = span;
// zbr:selfhost/Ast.zbr:719
            _self.source = source;
// zbr:selfhost/Ast.zbr:720
            _self.is_scoped = is_scoped;
// zbr:selfhost/Ast.zbr:721
            _self.stmts = stmts;
        return _self;
    }

};

pub const _zbr_ty_StmtCopyOut = struct {
    span: _zbr_ty_Span = undefined,
    target: _zbr_ty_Expr = undefined,
    value: _zbr_ty_Expr = undefined,
    deep: bool = undefined,
    pub fn init(span: _zbr_ty_Span, target: _zbr_ty_Expr, value: _zbr_ty_Expr, deep: bool) _zbr_ty_StmtCopyOut {
        var _self: _zbr_ty_StmtCopyOut = undefined;
// zbr:selfhost/Ast.zbr:730
            _self.span = span;
// zbr:selfhost/Ast.zbr:731
            _self.target = target;
// zbr:selfhost/Ast.zbr:732
            _self.value = value;
// zbr:selfhost/Ast.zbr:733
            _self.deep = deep;
        return _self;
    }

};

pub const _zbr_ty_ContractKind = enum {
    precond,
    postcond,
    classinv,
};

pub const _zbr_ty_StmtContract = struct {
    span: _zbr_ty_Span = undefined,
    kind: _zbr_ty_ContractKind = undefined,
    exprs: std.ArrayList(_zbr_ty_Expr) = undefined,
    pub fn init(span: _zbr_ty_Span, kind: _zbr_ty_ContractKind, exprs: std.ArrayList(_zbr_ty_Expr)) _zbr_ty_StmtContract {
        var _self: _zbr_ty_StmtContract = undefined;
// zbr:selfhost/Ast.zbr:746
            _self.span = span;
// zbr:selfhost/Ast.zbr:747
            _self.kind = kind;
// zbr:selfhost/Ast.zbr:748
            _self.exprs = exprs;
        return _self;
    }

};

pub const _zbr_ty_StmtPrint = struct {
    span: _zbr_ty_Span = undefined,
    args: std.ArrayList(_zbr_ty_Expr) = undefined,
    newline: bool = undefined,
    pub fn init(span: _zbr_ty_Span, args: std.ArrayList(_zbr_ty_Expr), newline: bool) _zbr_ty_StmtPrint {
        var _self: _zbr_ty_StmtPrint = undefined;
// zbr:selfhost/Ast.zbr:756
            _self.span = span;
// zbr:selfhost/Ast.zbr:757
            _self.args = args;
// zbr:selfhost/Ast.zbr:758
            _self.newline = newline;
        return _self;
    }

};

pub const _zbr_ty_Expr = union(enum) {
    int_lit: _zbr_ty_ExprIntLit,
    float_lit: _zbr_ty_ExprFloatLit,
    bool_lit: _zbr_ty_ExprBoolLit,
    char_lit: _zbr_ty_ExprCharLit,
    string_lit: _zbr_ty_ExprStringLit,
    string_interp: *_zbr_ty_ExprStringInterp,
    nil_: _zbr_ty_Span,
    this_: _zbr_ty_Span,
    ident: _zbr_ty_ExprIdent,
    member: *_zbr_ty_ExprMember,
    call: *_zbr_ty_ExprCall,
    index: *_zbr_ty_ExprIndex,
    slice: *_zbr_ty_ExprSlice,
    binary: *_zbr_ty_ExprBinary,
    unary: *_zbr_ty_ExprUnary,
    cast: *_zbr_ty_ExprCast,
    to_non_nil: *_zbr_ty_ExprToNonNil,
    is_nil: *_zbr_ty_ExprIsNil,
    orelse_: *_zbr_ty_ExprOrelse,
    catch_: *_zbr_ty_ExprCatch,
    if_expr: *_zbr_ty_ExprIf,
    lambda: *_zbr_ty_ExprLambda,
    list_lit: *_zbr_ty_ExprListLit,
    dict_lit: *_zbr_ty_ExprDictLit,
    set_lit: *_zbr_ty_ExprSetLit,
    array_lit: *_zbr_ty_ExprArrayLit,
    zig_lit: _zbr_ty_ExprZigLit,
    try_: *_zbr_ty_ExprTry,
    tuple_lit: *_zbr_ty_ExprTuple,
    type_check: *_zbr_ty_ExprTypeCheck,
    chained_cmp: *_zbr_ty_ExprChainedCmp,
    except_: *_zbr_ty_ExprExcept,
    old_: *_zbr_ty_ExprOld,
    result_: _zbr_ty_Span,
    opt_chain: *_zbr_ty_ExprOptChain,
};

pub const _zbr_ty_IntBase = enum {
    decimal,
    hex,
};

pub const _zbr_ty_ExprIntLit = struct {
    span: _zbr_ty_Span = undefined,
    text: []const u8 = undefined,
    base: _zbr_ty_IntBase = undefined,
    pub fn init(span: _zbr_ty_Span, text: []const u8, base: _zbr_ty_IntBase) _zbr_ty_ExprIntLit {
        var _self: _zbr_ty_ExprIntLit = undefined;
// zbr:selfhost/Ast.zbr:817
            _self.span = span;
// zbr:selfhost/Ast.zbr:818
            _self.text = _intern(text);
// zbr:selfhost/Ast.zbr:819
            _self.base = base;
        return _self;
    }

};

pub const _zbr_ty_ExprFloatLit = struct {
    span: _zbr_ty_Span = undefined,
    text: []const u8 = undefined,
    pub fn init(span: _zbr_ty_Span, text: []const u8) _zbr_ty_ExprFloatLit {
        var _self: _zbr_ty_ExprFloatLit = undefined;
// zbr:selfhost/Ast.zbr:828
            _self.span = span;
// zbr:selfhost/Ast.zbr:829
            _self.text = _intern(text);
        return _self;
    }

};

pub const _zbr_ty_ExprBoolLit = struct {
    span: _zbr_ty_Span = undefined,
    value: bool = undefined,
    pub fn init(span: _zbr_ty_Span, value: bool) _zbr_ty_ExprBoolLit {
        var _self: _zbr_ty_ExprBoolLit = undefined;
// zbr:selfhost/Ast.zbr:838
            _self.span = span;
// zbr:selfhost/Ast.zbr:839
            _self.value = value;
        return _self;
    }

};

pub const _zbr_ty_ExprCharLit = struct {
    span: _zbr_ty_Span = undefined,
    text: []const u8 = undefined,
    pub fn init(span: _zbr_ty_Span, text: []const u8) _zbr_ty_ExprCharLit {
        var _self: _zbr_ty_ExprCharLit = undefined;
// zbr:selfhost/Ast.zbr:848
            _self.span = span;
// zbr:selfhost/Ast.zbr:849
            _self.text = _intern(text);
        return _self;
    }

};

pub const _zbr_ty_StringKind = enum {
    plain,
    raw,
    nosub,
    zig_,
};

pub const _zbr_ty_ExprStringLit = struct {
    span: _zbr_ty_Span = undefined,
    kind: _zbr_ty_StringKind = undefined,
    text: []const u8 = undefined,
    pub fn init(span: _zbr_ty_Span, kind: _zbr_ty_StringKind, text: []const u8) _zbr_ty_ExprStringLit {
        var _self: _zbr_ty_ExprStringLit = undefined;
// zbr:selfhost/Ast.zbr:865
            _self.span = span;
// zbr:selfhost/Ast.zbr:866
            _self.kind = kind;
// zbr:selfhost/Ast.zbr:867
            _self.text = _intern(text);
        return _self;
    }

};

pub const _zbr_ty_StringPart = union(enum) {
    literal: []const u8,
    expr_: *_zbr_ty_Expr,
    format: []const u8,
};

pub const _zbr_ty_ExprStringInterp = struct {
    span: _zbr_ty_Span = undefined,
    parts: std.ArrayList(_zbr_ty_StringPart) = undefined,
    pub fn init(span: _zbr_ty_Span, parts: std.ArrayList(_zbr_ty_StringPart)) _zbr_ty_ExprStringInterp {
        var _self: _zbr_ty_ExprStringInterp = undefined;
// zbr:selfhost/Ast.zbr:881
            _self.span = span;
// zbr:selfhost/Ast.zbr:882
            _self.parts = parts;
        return _self;
    }

};

pub const _zbr_ty_ExceptField = struct {
    name: []const u8 = undefined,
    value: _zbr_ty_Expr = undefined,
    pub fn init(name: []const u8, value: _zbr_ty_Expr) _zbr_ty_ExceptField {
        var _self: _zbr_ty_ExceptField = undefined;
// zbr:selfhost/Ast.zbr:891
            _self.name = _intern(name);
// zbr:selfhost/Ast.zbr:892
            _self.value = value;
        return _self;
    }

};

pub const _zbr_ty_ExprExcept = struct {
    span: _zbr_ty_Span = undefined,
    base: _zbr_ty_Expr = undefined,
    fields: std.ArrayList(_zbr_ty_ExceptField) = undefined,
    pub fn init(span: _zbr_ty_Span, base: _zbr_ty_Expr, fields: std.ArrayList(_zbr_ty_ExceptField)) _zbr_ty_ExprExcept {
        var _self: _zbr_ty_ExprExcept = undefined;
// zbr:selfhost/Ast.zbr:900
            _self.span = span;
// zbr:selfhost/Ast.zbr:901
            _self.base = base;
// zbr:selfhost/Ast.zbr:902
            _self.fields = fields;
        return _self;
    }

};

pub const _zbr_ty_ExprIdent = struct {
    span: _zbr_ty_Span = undefined,
    name: []const u8 = undefined,
    pub fn init(span: _zbr_ty_Span, name: []const u8) _zbr_ty_ExprIdent {
        var _self: _zbr_ty_ExprIdent = undefined;
// zbr:selfhost/Ast.zbr:911
            _self.span = span;
// zbr:selfhost/Ast.zbr:912
            _self.name = _intern(name);
        return _self;
    }

};

pub const _zbr_ty_ExprMember = struct {
    span: _zbr_ty_Span = undefined,
    object: *_zbr_ty_Expr = undefined,
    member: []const u8 = undefined,
    pub fn init(span: _zbr_ty_Span, object: *_zbr_ty_Expr, member: []const u8) _zbr_ty_ExprMember {
        var _self: _zbr_ty_ExprMember = undefined;
// zbr:selfhost/Ast.zbr:922
            _self.span = span;
// zbr:selfhost/Ast.zbr:923
            _self.object = object;
// zbr:selfhost/Ast.zbr:924
            _self.member = _intern(member);
        return _self;
    }

};

pub const _zbr_ty_Arg = struct {
    span: _zbr_ty_Span = undefined,
    name: ?[]const u8 = undefined,
    value: _zbr_ty_Expr = undefined,
    pub fn init(span: _zbr_ty_Span, name: ?[]const u8, value: _zbr_ty_Expr) _zbr_ty_Arg {
        var _self: _zbr_ty_Arg = undefined;
// zbr:selfhost/Ast.zbr:934
            _self.span = span;
// zbr:selfhost/Ast.zbr:935
            _self.name = name;
// zbr:selfhost/Ast.zbr:936
            _self.value = value;
        return _self;
    }

};

pub const _zbr_ty_ExprCall = struct {
    span: _zbr_ty_Span = undefined,
    callee: _zbr_ty_Expr = undefined,
    args: std.ArrayList(_zbr_ty_Arg) = undefined,
    pub fn init(span: _zbr_ty_Span, callee: _zbr_ty_Expr, args: std.ArrayList(_zbr_ty_Arg)) _zbr_ty_ExprCall {
        var _self: _zbr_ty_ExprCall = undefined;
// zbr:selfhost/Ast.zbr:944
            _self.span = span;
// zbr:selfhost/Ast.zbr:945
            _self.callee = callee;
// zbr:selfhost/Ast.zbr:946
            _self.args = args;
        return _self;
    }

};

pub const _zbr_ty_ExprIndex = struct {
    span: _zbr_ty_Span = undefined,
    object: *_zbr_ty_Expr = undefined,
    index: *_zbr_ty_Expr = undefined,
    pub fn init(span: _zbr_ty_Span, object: *_zbr_ty_Expr, index: *_zbr_ty_Expr) _zbr_ty_ExprIndex {
        var _self: _zbr_ty_ExprIndex = undefined;
// zbr:selfhost/Ast.zbr:956
            _self.span = span;
// zbr:selfhost/Ast.zbr:957
            _self.object = object;
// zbr:selfhost/Ast.zbr:958
            _self.index = index;
        return _self;
    }

};

pub const _zbr_ty_ExprSlice = struct {
    span: _zbr_ty_Span = undefined,
    object: *_zbr_ty_Expr = undefined,
    start: ?*_zbr_ty_Expr = undefined,
    stop_: ?*_zbr_ty_Expr = undefined,
    pub fn init(span: _zbr_ty_Span, object: *_zbr_ty_Expr, start: ?*_zbr_ty_Expr, stop_: ?*_zbr_ty_Expr) _zbr_ty_ExprSlice {
        var _self: _zbr_ty_ExprSlice = undefined;
// zbr:selfhost/Ast.zbr:969
            _self.span = span;
// zbr:selfhost/Ast.zbr:970
            _self.object = object;
// zbr:selfhost/Ast.zbr:971
            _self.start = start;
// zbr:selfhost/Ast.zbr:972
            _self.stop_ = stop_;
        return _self;
    }

};

pub const _zbr_ty_BinaryOp = enum {
    add,
    sub,
    mul,
    div,
    int_div,
    mod,
    pow,
    bit_and,
    bit_or,
    bit_xor,
    shl,
    shr,
    eq,
    ne,
    lt,
    le,
    gt,
    ge,
    and_,
    or_,
    in_,
    dotdot,
};

pub const _zbr_ty_ExprBinary = struct {
    span: _zbr_ty_Span = undefined,
    op: _zbr_ty_BinaryOp = undefined,
    left: *_zbr_ty_Expr = undefined,
    right: *_zbr_ty_Expr = undefined,
    pub fn init(span: _zbr_ty_Span, op: _zbr_ty_BinaryOp, left: *_zbr_ty_Expr, right: *_zbr_ty_Expr) _zbr_ty_ExprBinary {
        var _self: _zbr_ty_ExprBinary = undefined;
// zbr:selfhost/Ast.zbr:1007
            _self.span = span;
// zbr:selfhost/Ast.zbr:1008
            _self.op = op;
// zbr:selfhost/Ast.zbr:1009
            _self.left = left;
// zbr:selfhost/Ast.zbr:1010
            _self.right = right;
        return _self;
    }

};

pub const _zbr_ty_UnaryOp = enum {
    neg,
    not_,
    bit_not,
};

pub const _zbr_ty_ExprUnary = struct {
    span: _zbr_ty_Span = undefined,
    op: _zbr_ty_UnaryOp = undefined,
    operand: *_zbr_ty_Expr = undefined,
    pub fn init(span: _zbr_ty_Span, op: _zbr_ty_UnaryOp, operand: *_zbr_ty_Expr) _zbr_ty_ExprUnary {
        var _self: _zbr_ty_ExprUnary = undefined;
// zbr:selfhost/Ast.zbr:1025
            _self.span = span;
// zbr:selfhost/Ast.zbr:1026
            _self.op = op;
// zbr:selfhost/Ast.zbr:1027
            _self.operand = operand;
        return _self;
    }

};

pub const _zbr_ty_ExprOld = struct {
    span: _zbr_ty_Span = undefined,
    uid: i64 = undefined,
    operand: *_zbr_ty_Expr = undefined,
    pub fn init(span: _zbr_ty_Span, uid: i64, operand: *_zbr_ty_Expr) _zbr_ty_ExprOld {
        var _self: _zbr_ty_ExprOld = undefined;
// zbr:selfhost/Ast.zbr:1037
            _self.span = span;
// zbr:selfhost/Ast.zbr:1038
            _self.uid = uid;
// zbr:selfhost/Ast.zbr:1039
            _self.operand = operand;
        return _self;
    }

};

pub const _zbr_ty_ExprCast = struct {
    span: _zbr_ty_Span = undefined,
    expr: *_zbr_ty_Expr = undefined,
    target: _zbr_ty_TypeRef = undefined,
    pub fn init(span: _zbr_ty_Span, expr: *_zbr_ty_Expr, target: _zbr_ty_TypeRef) _zbr_ty_ExprCast {
        var _self: _zbr_ty_ExprCast = undefined;
// zbr:selfhost/Ast.zbr:1049
            _self.span = span;
// zbr:selfhost/Ast.zbr:1050
            _self.expr = expr;
// zbr:selfhost/Ast.zbr:1051
            _self.target = target;
        return _self;
    }

};

pub const _zbr_ty_ExprTypeCheck = struct {
    span: _zbr_ty_Span = undefined,
    expr: *_zbr_ty_Expr = undefined,
    type_name: []const u8 = undefined,
    variant_name: ?[]const u8 = undefined,
    pub fn init(span: _zbr_ty_Span, expr: *_zbr_ty_Expr, type_name: []const u8) _zbr_ty_ExprTypeCheck {
        var _self: _zbr_ty_ExprTypeCheck = undefined;
// zbr:selfhost/Ast.zbr:1063
            _self.span = span;
// zbr:selfhost/Ast.zbr:1064
            _self.expr = expr;
// zbr:selfhost/Ast.zbr:1065
            _self.type_name = _intern(type_name);
// zbr:selfhost/Ast.zbr:1066
            _self.variant_name = null;
        return _self;
    }

};

pub const _zbr_ty_ExprChainedCmp = struct {
    span: _zbr_ty_Span = undefined,
    ops: std.ArrayList([]const u8) = undefined,
    operands: std.ArrayList(_zbr_ty_Expr) = undefined,
    pub fn init(span: _zbr_ty_Span, ops: std.ArrayList([]const u8), operands: std.ArrayList(_zbr_ty_Expr)) _zbr_ty_ExprChainedCmp {
        var _self: _zbr_ty_ExprChainedCmp = undefined;
// zbr:selfhost/Ast.zbr:1076
            _self.span = span;
// zbr:selfhost/Ast.zbr:1077
            _self.ops = ops;
// zbr:selfhost/Ast.zbr:1078
            _self.operands = operands;
        return _self;
    }

};

pub const _zbr_ty_ExprOptChain = struct {
    span: _zbr_ty_Span = undefined,
    base: *_zbr_ty_Expr = undefined,
    member: []const u8 = undefined,
    has_args: bool = undefined,
    args: std.ArrayList(_zbr_ty_Arg) = undefined,
    pub fn init(span: _zbr_ty_Span, base: *_zbr_ty_Expr, member: []const u8, has_args: bool, args: std.ArrayList(_zbr_ty_Arg)) _zbr_ty_ExprOptChain {
        var _self: _zbr_ty_ExprOptChain = undefined;
// zbr:selfhost/Ast.zbr:1088
            _self.span = span;
// zbr:selfhost/Ast.zbr:1089
            _self.base = base;
// zbr:selfhost/Ast.zbr:1090
            _self.member = _intern(member);
// zbr:selfhost/Ast.zbr:1091
            _self.has_args = has_args;
// zbr:selfhost/Ast.zbr:1092
            _self.args = args;
        return _self;
    }

};

pub const _zbr_ty_ExprToNonNil = struct {
    span: _zbr_ty_Span = undefined,
    expr: *_zbr_ty_Expr = undefined,
    pub fn init(span: _zbr_ty_Span, expr: *_zbr_ty_Expr) _zbr_ty_ExprToNonNil {
        var _self: _zbr_ty_ExprToNonNil = undefined;
// zbr:selfhost/Ast.zbr:1101
            _self.span = span;
// zbr:selfhost/Ast.zbr:1102
            _self.expr = expr;
        return _self;
    }

};

pub const _zbr_ty_ExprIsNil = struct {
    span: _zbr_ty_Span = undefined,
    expr: *_zbr_ty_Expr = undefined,
    pub fn init(span: _zbr_ty_Span, expr: *_zbr_ty_Expr) _zbr_ty_ExprIsNil {
        var _self: _zbr_ty_ExprIsNil = undefined;
// zbr:selfhost/Ast.zbr:1109
            _self.span = span;
// zbr:selfhost/Ast.zbr:1110
            _self.expr = expr;
        return _self;
    }

};

pub const _zbr_ty_ExprOrelse = struct {
    span: _zbr_ty_Span = undefined,
    expr: *_zbr_ty_Expr = undefined,
    fallback: *_zbr_ty_Expr = undefined,
    pub fn init(span: _zbr_ty_Span, expr: *_zbr_ty_Expr, fallback: *_zbr_ty_Expr) _zbr_ty_ExprOrelse {
        var _self: _zbr_ty_ExprOrelse = undefined;
// zbr:selfhost/Ast.zbr:1120
            _self.span = span;
// zbr:selfhost/Ast.zbr:1121
            _self.expr = expr;
// zbr:selfhost/Ast.zbr:1122
            _self.fallback = fallback;
        return _self;
    }

};

pub const _zbr_ty_ExprCatch = struct {
    span: _zbr_ty_Span = undefined,
    expr: *_zbr_ty_Expr = undefined,
    err_var: ?[]const u8 = undefined,
    fallback: *_zbr_ty_Expr = undefined,
    pub fn init(span: _zbr_ty_Span, expr: *_zbr_ty_Expr, err_var: ?[]const u8, fallback: *_zbr_ty_Expr) _zbr_ty_ExprCatch {
        var _self: _zbr_ty_ExprCatch = undefined;
// zbr:selfhost/Ast.zbr:1131
            _self.span = span;
// zbr:selfhost/Ast.zbr:1132
            _self.expr = expr;
// zbr:selfhost/Ast.zbr:1133
            _self.err_var = err_var;
// zbr:selfhost/Ast.zbr:1134
            _self.fallback = fallback;
        return _self;
    }

};

pub const _zbr_ty_ExprIf = struct {
    span: _zbr_ty_Span = undefined,
    cond: *_zbr_ty_Expr = undefined,
    then_expr: *_zbr_ty_Expr = undefined,
    else_expr: *_zbr_ty_Expr = undefined,
    pub fn init(span: _zbr_ty_Span, cond: *_zbr_ty_Expr, then_expr: *_zbr_ty_Expr, else_expr: *_zbr_ty_Expr) _zbr_ty_ExprIf {
        var _self: _zbr_ty_ExprIf = undefined;
// zbr:selfhost/Ast.zbr:1145
            _self.span = span;
// zbr:selfhost/Ast.zbr:1146
            _self.cond = cond;
// zbr:selfhost/Ast.zbr:1147
            _self.then_expr = then_expr;
// zbr:selfhost/Ast.zbr:1148
            _self.else_expr = else_expr;
        return _self;
    }

};

pub const _zbr_ty_LambdaBody = union(enum) {
    expr_: _zbr_ty_Expr,
    stmts: std.ArrayList(_zbr_ty_Stmt),
};

pub const _zbr_ty_ExprLambda = struct {
    span: _zbr_ty_Span = undefined,
    params: std.ArrayList(_zbr_ty_Param) = undefined,
    return_type: ?_zbr_ty_TypeRef = undefined,
    body_: _zbr_ty_LambdaBody = undefined,
    captures: std.ArrayList(_zbr_ty_DeclVar) = undefined,
    pub fn init(span: _zbr_ty_Span, params: std.ArrayList(_zbr_ty_Param), return_type: ?_zbr_ty_TypeRef, body_: _zbr_ty_LambdaBody, captures: std.ArrayList(_zbr_ty_DeclVar)) _zbr_ty_ExprLambda {
        var _self: _zbr_ty_ExprLambda = undefined;
// zbr:selfhost/Ast.zbr:1165
            _self.span = span;
// zbr:selfhost/Ast.zbr:1166
            _self.params = params;
// zbr:selfhost/Ast.zbr:1167
            _self.return_type = return_type;
// zbr:selfhost/Ast.zbr:1168
            _self.body_ = body_;
// zbr:selfhost/Ast.zbr:1169
            _self.captures = captures;
        return _self;
    }

};

pub const _zbr_ty_ExprListLit = struct {
    span: _zbr_ty_Span = undefined,
    elem_type: ?_zbr_ty_TypeRef = undefined,
    elems: std.ArrayList(_zbr_ty_Expr) = undefined,
    pub fn init(span: _zbr_ty_Span, elem_type: ?_zbr_ty_TypeRef, elems: std.ArrayList(_zbr_ty_Expr)) _zbr_ty_ExprListLit {
        var _self: _zbr_ty_ExprListLit = undefined;
// zbr:selfhost/Ast.zbr:1179
            _self.span = span;
// zbr:selfhost/Ast.zbr:1180
            _self.elem_type = elem_type;
// zbr:selfhost/Ast.zbr:1181
            _self.elems = elems;
        return _self;
    }

};

pub const _zbr_ty_ExprSetLit = struct {
    span: _zbr_ty_Span = undefined,
    elem_type: ?_zbr_ty_TypeRef = undefined,
    elems: std.ArrayList(_zbr_ty_Expr) = undefined,
    pub fn init(span: _zbr_ty_Span, elem_type: ?_zbr_ty_TypeRef, elems: std.ArrayList(_zbr_ty_Expr)) _zbr_ty_ExprSetLit {
        var _self: _zbr_ty_ExprSetLit = undefined;
// zbr:selfhost/Ast.zbr:1191
            _self.span = span;
// zbr:selfhost/Ast.zbr:1192
            _self.elem_type = elem_type;
// zbr:selfhost/Ast.zbr:1193
            _self.elems = elems;
        return _self;
    }

};

pub const _zbr_ty_DictEntry = struct {
    key: *_zbr_ty_Expr = undefined,
    value: *_zbr_ty_Expr = undefined,
    pub fn init(key: *_zbr_ty_Expr, value: *_zbr_ty_Expr) _zbr_ty_DictEntry {
        var _self: _zbr_ty_DictEntry = undefined;
// zbr:selfhost/Ast.zbr:1200
            _self.key = key;
// zbr:selfhost/Ast.zbr:1201
            _self.value = value;
        return _self;
    }

};

pub const _zbr_ty_ExprDictLit = struct {
    span: _zbr_ty_Span = undefined,
    entries: std.ArrayList(_zbr_ty_DictEntry) = undefined,
    pub fn init(span: _zbr_ty_Span, entries: std.ArrayList(_zbr_ty_DictEntry)) _zbr_ty_ExprDictLit {
        var _self: _zbr_ty_ExprDictLit = undefined;
// zbr:selfhost/Ast.zbr:1208
            _self.span = span;
// zbr:selfhost/Ast.zbr:1209
            _self.entries = entries;
        return _self;
    }

};

pub const _zbr_ty_ExprArrayLit = struct {
    span: _zbr_ty_Span = undefined,
    elems: std.ArrayList(_zbr_ty_Expr) = undefined,
    pub fn init(span: _zbr_ty_Span, elems: std.ArrayList(_zbr_ty_Expr)) _zbr_ty_ExprArrayLit {
        var _self: _zbr_ty_ExprArrayLit = undefined;
// zbr:selfhost/Ast.zbr:1216
            _self.span = span;
// zbr:selfhost/Ast.zbr:1217
            _self.elems = elems;
        return _self;
    }

};

pub const _zbr_ty_ExprZigLit = struct {
    span: _zbr_ty_Span = undefined,
    text: []const u8 = undefined,
    pub fn init(span: _zbr_ty_Span, text: []const u8) _zbr_ty_ExprZigLit {
        var _self: _zbr_ty_ExprZigLit = undefined;
// zbr:selfhost/Ast.zbr:1226
            _self.span = span;
// zbr:selfhost/Ast.zbr:1227
            _self.text = _intern(text);
        return _self;
    }

};

pub const _zbr_ty_ExprTry = struct {
    span: _zbr_ty_Span = undefined,
    expr: *_zbr_ty_Expr = undefined,
    pub fn init(span: _zbr_ty_Span, expr: *_zbr_ty_Expr) _zbr_ty_ExprTry {
        var _self: _zbr_ty_ExprTry = undefined;
// zbr:selfhost/Ast.zbr:1234
            _self.span = span;
// zbr:selfhost/Ast.zbr:1235
            _self.expr = expr;
        return _self;
    }

};

pub const _zbr_ty_ExprTuple = struct {
    span: _zbr_ty_Span = undefined,
    elems: std.ArrayList(_zbr_ty_Expr) = undefined,
    pub fn init(span: _zbr_ty_Span, elems: std.ArrayList(_zbr_ty_Expr)) _zbr_ty_ExprTuple {
        var _self: _zbr_ty_ExprTuple = undefined;
// zbr:selfhost/Ast.zbr:1242
            _self.span = span;
// zbr:selfhost/Ast.zbr:1243
            _self.elems = elems;
        return _self;
    }

};

var _module_vars_inited: bool = false;
pub fn _initModuleVars() void {
    if (_module_vars_inited) return;
    _module_vars_inited = true;
}
