// Generated by zebra-selfhost.
// Source: selfhost/Checker.zbr

const std     = @import("std");
const builtin = @import("builtin");
const _zbr_rt = @import("zebra_rt.zig");
pub const panic = std.debug.FullPanic(_zbr_rt._zebra_panic);
const _intern = _zbr_rt._intern;
const _zbr_at = _zbr_rt._zbr_at;
const _zebra_lt = _zbr_rt._zebra_lt;
const _zebra_le = _zbr_rt._zebra_le;
const _zebra_gt = _zbr_rt._zebra_gt;
const _zebra_ge = _zbr_rt._zebra_ge;
const _str_concat = _zbr_rt._str_concat;
const _zbr_hash = _zbr_rt._zbr_hash;

const Ast = @import("Ast.zig");
const _zbr_ty_Module = Ast._zbr_ty_Module;
const _zbr_ty_Decl = Ast._zbr_ty_Decl;
const _zbr_ty_DeclClass = Ast._zbr_ty_DeclClass;
const _zbr_ty_DeclStruct = Ast._zbr_ty_DeclStruct;
const _zbr_ty_DeclVar = Ast._zbr_ty_DeclVar;
const _zbr_ty_DeclMethod = Ast._zbr_ty_DeclMethod;
const _zbr_ty_DeclInit = Ast._zbr_ty_DeclInit;
const _zbr_ty_DeclUnion = Ast._zbr_ty_DeclUnion;
const _zbr_ty_UnionVariant = Ast._zbr_ty_UnionVariant;
const _zbr_ty_DeclNamespace = Ast._zbr_ty_DeclNamespace;
const _zbr_ty_DeclUse = Ast._zbr_ty_DeclUse;
const _zbr_ty_Param = Ast._zbr_ty_Param;
const _zbr_ty_Expr = Ast._zbr_ty_Expr;
const _zbr_ty_ExprMember = Ast._zbr_ty_ExprMember;
const _zbr_ty_ExprCall = Ast._zbr_ty_ExprCall;
const _zbr_ty_ExprBinary = Ast._zbr_ty_ExprBinary;
const _zbr_ty_ExprUnary = Ast._zbr_ty_ExprUnary;
const _zbr_ty_ExprCast = Ast._zbr_ty_ExprCast;
const _zbr_ty_ExprToNonNil = Ast._zbr_ty_ExprToNonNil;
const _zbr_ty_ExprIsNil = Ast._zbr_ty_ExprIsNil;
const _zbr_ty_ExprOrelse = Ast._zbr_ty_ExprOrelse;
const _zbr_ty_ExprCatch = Ast._zbr_ty_ExprCatch;
const _zbr_ty_ExprIf = Ast._zbr_ty_ExprIf;
const _zbr_ty_ExprLambda = Ast._zbr_ty_ExprLambda;
const _zbr_ty_ExprListLit = Ast._zbr_ty_ExprListLit;
const _zbr_ty_ExprDictLit = Ast._zbr_ty_ExprDictLit;
const _zbr_ty_ExprArrayLit = Ast._zbr_ty_ExprArrayLit;
const _zbr_ty_ExprStringInterp = Ast._zbr_ty_ExprStringInterp;
const _zbr_ty_ExprTuple = Ast._zbr_ty_ExprTuple;
const _zbr_ty_ExprTypeCheck = Ast._zbr_ty_ExprTypeCheck;
const _zbr_ty_ExprChainedCmp = Ast._zbr_ty_ExprChainedCmp;
const _zbr_ty_ExprExcept = Ast._zbr_ty_ExprExcept;
const _zbr_ty_ExprOld = Ast._zbr_ty_ExprOld;
const _zbr_ty_ExprIndex = Ast._zbr_ty_ExprIndex;
const _zbr_ty_ExprSlice = Ast._zbr_ty_ExprSlice;
const _zbr_ty_ExprTry = Ast._zbr_ty_ExprTry;
const _zbr_ty_Arg = Ast._zbr_ty_Arg;
const _zbr_ty_Stmt = Ast._zbr_ty_Stmt;
const _zbr_ty_StmtIf = Ast._zbr_ty_StmtIf;
const _zbr_ty_StmtWhile = Ast._zbr_ty_StmtWhile;
const _zbr_ty_StmtForIn = Ast._zbr_ty_StmtForIn;
const _zbr_ty_StmtForNum = Ast._zbr_ty_StmtForNum;
const _zbr_ty_StmtBranch = Ast._zbr_ty_StmtBranch;
const _zbr_ty_StmtReturn = Ast._zbr_ty_StmtReturn;
const _zbr_ty_StmtAssign = Ast._zbr_ty_StmtAssign;
const _zbr_ty_StmtDefer = Ast._zbr_ty_StmtDefer;
const _zbr_ty_StmtWith = Ast._zbr_ty_StmtWith;
const _zbr_ty_StmtRaise = Ast._zbr_ty_StmtRaise;
const _zbr_ty_StmtTryCatch = Ast._zbr_ty_StmtTryCatch;
const _zbr_ty_StmtGuard = Ast._zbr_ty_StmtGuard;
const _zbr_ty_StmtDestruct = Ast._zbr_ty_StmtDestruct;
const _zbr_ty_StmtAllocate = Ast._zbr_ty_StmtAllocate;
const _zbr_ty_StmtCopyOut = Ast._zbr_ty_StmtCopyOut;
const _zbr_ty_StmtContract = Ast._zbr_ty_StmtContract;
const _zbr_ty_StmtPrint = Ast._zbr_ty_StmtPrint;
const _zbr_ty_StmtAssert = Ast._zbr_ty_StmtAssert;
const _zbr_ty_StmtAssertCmp = Ast._zbr_ty_StmtAssertCmp;
const _zbr_ty_StmtAssertUnary = Ast._zbr_ty_StmtAssertUnary;
const _zbr_ty_BranchOn = Ast._zbr_ty_BranchOn;
const _zbr_ty_ElseIf = Ast._zbr_ty_ElseIf;
const _zbr_ty_CatchClause = Ast._zbr_ty_CatchClause;
const _zbr_ty_LambdaBody = Ast._zbr_ty_LambdaBody;
const _zbr_ty_StringPart = Ast._zbr_ty_StringPart;
const _zbr_ty_DictEntry = Ast._zbr_ty_DictEntry;
const _zbr_ty_ExceptField = Ast._zbr_ty_ExceptField;
const Parser = @import("Parser.zig");
const _zbr_ty_PNode = Parser._zbr_ty_PNode;
const _zbr_ty_PUse = Parser._zbr_ty_PUse;
const _zbr_ty_PModule = Parser._zbr_ty_PModule;
const _zbr_ty_Resolver = @import("Resolver.zig")._zbr_ty_Resolver;
const AstBuilder = @import("AstBuilder.zig");
const _zbr_ty_ASTBuilder = AstBuilder._zbr_ty_ASTBuilder;
pub const _zbr_ty_UnionInfo = struct {
    _type_tag: u64 = _ttag_UnionInfo,
    name: []const u8 = undefined,
    file: []const u8 = undefined,
    line: i64 = undefined,
    variants: std.ArrayList([]const u8) = undefined,
    variant_lines: std.ArrayList(i64) = undefined,
    pub fn init(name: []const u8, file: []const u8, line: i64) *_zbr_ty_UnionInfo {
        const _self = _zbr_rt._allocator.create(_zbr_ty_UnionInfo) catch @panic("OOM");
        _self._type_tag = _zbr_hash("UnionInfo");
// zbr:selfhost/Checker.zbr:28
            _self.name = _intern(name);
// zbr:selfhost/Checker.zbr:29
            _self.file = _intern(file);
// zbr:selfhost/Checker.zbr:30
            _self.line = line;
// zbr:selfhost/Checker.zbr:31
            _self.variants = std.ArrayList([]const u8).empty;
// zbr:selfhost/Checker.zbr:32
            _self.variant_lines = std.ArrayList(i64).empty;
        return _self;
    }

    pub fn addVariant(self: *_zbr_ty_UnionInfo, v: []const u8, ln: i64) void {
// zbr:selfhost/Checker.zbr:35
        self.variants.append(_zbr_rt._allocator, _intern(v)) catch @panic("OOM");
// zbr:selfhost/Checker.zbr:36
        self.variant_lines.append(_zbr_rt._allocator, ln) catch @panic("OOM");
    }

    pub fn hasVariant(self: *_zbr_ty_UnionInfo, v: []const u8) bool {
// zbr:selfhost/Checker.zbr:39
        var i: i64 = 0;
// zbr:selfhost/Checker.zbr:40
        while (_zebra_lt(i, @as(i64, @intCast(self.variants.items.len)))) {
// zbr:selfhost/Checker.zbr:41
            if (std.mem.eql(u8, _zbr_at(self.variants.items, i), v)) {
// zbr:selfhost/Checker.zbr:42
                return true;
            }
// zbr:selfhost/Checker.zbr:43
            i = (i + 1);
        }
// zbr:selfhost/Checker.zbr:44
        return false;
    }

    pub fn lineOf(self: *_zbr_ty_UnionInfo, v: []const u8) i64 {
// zbr:selfhost/Checker.zbr:47
        var i: i64 = 0;
// zbr:selfhost/Checker.zbr:48
        while (_zebra_lt(i, @as(i64, @intCast(self.variants.items.len)))) {
// zbr:selfhost/Checker.zbr:49
            if (std.mem.eql(u8, _zbr_at(self.variants.items, i), v)) {
// zbr:selfhost/Checker.zbr:50
                return _zbr_at(self.variant_lines.items, i);
            }
// zbr:selfhost/Checker.zbr:51
            i = (i + 1);
        }
// zbr:selfhost/Checker.zbr:52
        return 0;
    }

};
const _ttag_UnionInfo: u64 = _zbr_hash("UnionInfo");
const _reflect_UnionInfo_name: []const u8 = "UnionInfo";
const _reflect_UnionInfo_fields: []const []const u8 = &.{"name", "file", "line", "variants", "variant_lines"};
const _reflect_UnionInfo_field_types: []const []const u8 = &.{"str", "str", "int", "List(str)", "List(int)"};

pub const _zbr_ty_DeadCodeChecker = struct {
    _type_tag: u64 = _ttag_DeadCodeChecker,
    union_infos: std.StringHashMap(*_zbr_ty_UnionInfo) = undefined,
    match_sites: std.StringHashMap(std.ArrayList([]const u8)) = undefined,
    match_key_list: std.ArrayList([]const u8) = undefined,
    constructed_set: std.StringHashMap(bool) = undefined,
    constructed_key_list: std.ArrayList([]const u8) = undefined,
    module_fns: std.StringHashMap([]const u8) = undefined,
    module_fn_key_list: std.ArrayList([]const u8) = undefined,
    fn_edges: std.StringHashMap(std.ArrayList([]const u8)) = undefined,
    root_set: std.StringHashMap(bool) = undefined,
    root_key_list: std.ArrayList([]const u8) = undefined,
    reachable_set: std.StringHashMap(bool) = undefined,
    exposed_names: std.StringHashMap(bool) = undefined,
    current_file: []const u8 = undefined,
    current_fn_key: []const u8 = undefined,
    pub fn init() *_zbr_ty_DeadCodeChecker {
        const _self = _zbr_rt._allocator.create(_zbr_ty_DeadCodeChecker) catch @panic("OOM");
        _self._type_tag = _zbr_hash("DeadCodeChecker");
// zbr:selfhost/Checker.zbr:78
            _self.union_infos = std.StringHashMap(*_zbr_ty_UnionInfo).init(_zbr_rt._allocator);
// zbr:selfhost/Checker.zbr:79
            _self.match_sites = std.StringHashMap(std.ArrayList([]const u8)).init(_zbr_rt._allocator);
// zbr:selfhost/Checker.zbr:80
            _self.match_key_list = std.ArrayList([]const u8).empty;
// zbr:selfhost/Checker.zbr:81
            _self.constructed_set = std.StringHashMap(bool).init(_zbr_rt._allocator);
// zbr:selfhost/Checker.zbr:82
            _self.constructed_key_list = std.ArrayList([]const u8).empty;
// zbr:selfhost/Checker.zbr:83
            _self.module_fns = std.StringHashMap([]const u8).init(_zbr_rt._allocator);
// zbr:selfhost/Checker.zbr:84
            _self.module_fn_key_list = std.ArrayList([]const u8).empty;
// zbr:selfhost/Checker.zbr:85
            _self.fn_edges = std.StringHashMap(std.ArrayList([]const u8)).init(_zbr_rt._allocator);
// zbr:selfhost/Checker.zbr:86
            _self.root_set = std.StringHashMap(bool).init(_zbr_rt._allocator);
// zbr:selfhost/Checker.zbr:87
            _self.root_key_list = std.ArrayList([]const u8).empty;
// zbr:selfhost/Checker.zbr:88
            _self.reachable_set = std.StringHashMap(bool).init(_zbr_rt._allocator);
// zbr:selfhost/Checker.zbr:89
            _self.exposed_names = std.StringHashMap(bool).init(_zbr_rt._allocator);
// zbr:selfhost/Checker.zbr:90
            _self.current_file = _intern("");
// zbr:selfhost/Checker.zbr:91
            _self.current_fn_key = _intern("");
        return _self;
    }

    pub fn isKnownUnion(self: *_zbr_ty_DeadCodeChecker, name: []const u8) bool {
// zbr:selfhost/Checker.zbr:94
        return self.union_infos.contains(name);
    }

    pub fn recordMatch(self: *_zbr_ty_DeadCodeChecker, union_name: []const u8, variant: []const u8, file: []const u8, line: i64) void {
// zbr:selfhost/Checker.zbr:97
        const key: []const u8 = _str_concat(_str_concat(union_name, ":", _zbr_rt._allocator), variant, _zbr_rt._allocator);
// zbr:selfhost/Checker.zbr:98
        if ((!self.match_sites.contains(key))) {
// zbr:selfhost/Checker.zbr:99
            self.match_sites.put(_intern(key), std.ArrayList([]const u8).empty) catch @panic("OOM");
// zbr:selfhost/Checker.zbr:100
            self.match_key_list.append(_zbr_rt._allocator, _intern(key)) catch @panic("OOM");
        }
// zbr:selfhost/Checker.zbr:101
        var sites: std.ArrayList([]const u8) = (self.match_sites.get(key).?);
// zbr:selfhost/Checker.zbr:102
        sites.append(_zbr_rt._allocator, _intern(_str_concat(_str_concat(file, ":", _zbr_rt._allocator), (std.fmt.allocPrint(_zbr_rt._allocator, "{}", .{line}) catch @panic("OOM")), _zbr_rt._allocator))) catch @panic("OOM");
    }

    pub fn recordConstruction(self: *_zbr_ty_DeadCodeChecker, union_name: []const u8, variant: []const u8) void {
// zbr:selfhost/Checker.zbr:105
        const key: []const u8 = _str_concat(_str_concat(union_name, ":", _zbr_rt._allocator), variant, _zbr_rt._allocator);
// zbr:selfhost/Checker.zbr:106
        if ((!self.constructed_set.contains(key))) {
// zbr:selfhost/Checker.zbr:107
            self.constructed_set.put(_intern(key), true) catch @panic("OOM");
// zbr:selfhost/Checker.zbr:108
            self.constructed_key_list.append(_zbr_rt._allocator, _intern(key)) catch @panic("OOM");
        }
    }

    pub fn fnKey(self: *const _zbr_ty_DeadCodeChecker, file: []const u8, fn_name: []const u8) []const u8 {
        _ = self;
// zbr:selfhost/Checker.zbr:111
        return _str_concat(_str_concat(file, "::", _zbr_rt._allocator), fn_name, _zbr_rt._allocator);
    }

    pub fn registerModuleFn(self: *_zbr_ty_DeadCodeChecker, file: []const u8, fn_name: []const u8, line: i64) void {
// zbr:selfhost/Checker.zbr:114
        const key: []const u8 = self.fnKey(file, fn_name);
// zbr:selfhost/Checker.zbr:115
        if ((!self.module_fns.contains(key))) {
// zbr:selfhost/Checker.zbr:116
            self.module_fns.put(_intern(key), _intern(_str_concat(_str_concat(file, ":", _zbr_rt._allocator), (std.fmt.allocPrint(_zbr_rt._allocator, "{}", .{line}) catch @panic("OOM")), _zbr_rt._allocator))) catch @panic("OOM");
// zbr:selfhost/Checker.zbr:117
            self.module_fn_key_list.append(_zbr_rt._allocator, _intern(key)) catch @panic("OOM");
// zbr:selfhost/Checker.zbr:118
            self.fn_edges.put(_intern(key), std.ArrayList([]const u8).empty) catch @panic("OOM");
        }
    }

    pub fn markAsRoot(self: *_zbr_ty_DeadCodeChecker, fn_key: []const u8) void {
// zbr:selfhost/Checker.zbr:121
        if ((!self.root_set.contains(fn_key))) {
// zbr:selfhost/Checker.zbr:122
            self.root_set.put(_intern(fn_key), true) catch @panic("OOM");
// zbr:selfhost/Checker.zbr:123
            self.root_key_list.append(_zbr_rt._allocator, _intern(fn_key)) catch @panic("OOM");
        }
    }

    pub fn trackFnCall(self: *_zbr_ty_DeadCodeChecker, callee_name: []const u8) void {
// zbr:selfhost/Checker.zbr:126
        const to_key: []const u8 = self.fnKey(self.current_file, callee_name);
// zbr:selfhost/Checker.zbr:127
        if ((!self.module_fns.contains(to_key))) {
// zbr:selfhost/Checker.zbr:128
            return;
        }
// zbr:selfhost/Checker.zbr:129
        if (std.mem.eql(u8, self.current_fn_key, "")) {
// zbr:selfhost/Checker.zbr:131
            self.markAsRoot(to_key);
        } else {
// zbr:selfhost/Checker.zbr:134
            if (self.fn_edges.contains(self.current_fn_key)) {
// zbr:selfhost/Checker.zbr:135
                var edges: std.ArrayList([]const u8) = (self.fn_edges.get(self.current_fn_key).?);
// zbr:selfhost/Checker.zbr:136
                edges.append(_zbr_rt._allocator, _intern(to_key)) catch @panic("OOM");
            }
        }
    }

    pub fn extractFnName(self: *_zbr_ty_DeadCodeChecker, fn_key: []const u8) []const u8 {
        _ = self;
// zbr:selfhost/Checker.zbr:139
        if ((std.mem.indexOf(u8, fn_key, "::") != null)) {
// zbr:selfhost/Checker.zbr:140
            const parts: std.ArrayList([]const u8) = blk092_1: { var _ll_1: std.ArrayList([]const u8) = std.ArrayList([]const u8).empty; var _split_iter_1 = std.mem.splitSequence(u8, fn_key, "::"); while (_split_iter_1.next()) |_se_1| { _ll_1.append(_zbr_rt._allocator, _se_1) catch @panic("OOM"); } break :blk092_1 _ll_1; };
// zbr:selfhost/Checker.zbr:141
            if (_zebra_ge(@as(i64, @intCast(parts.items.len)), 2)) {
// zbr:selfhost/Checker.zbr:142
                return _zbr_at(parts.items, (@as(i64, @intCast(parts.items.len)) - 1));
            }
        }
// zbr:selfhost/Checker.zbr:143
        return fn_key;
    }

    pub fn collectDecls(self: *_zbr_ty_DeadCodeChecker, module: _zbr_ty_Module) void {
// zbr:selfhost/Checker.zbr:148
        const file: []const u8 = module.file;
// zbr:selfhost/Checker.zbr:149
        self.current_file = _intern(file);
// zbr:selfhost/Checker.zbr:150
        var i: i64 = 0;
// zbr:selfhost/Checker.zbr:151
        while (_zebra_lt(i, @as(i64, @intCast(module.decls.items.len)))) {
// zbr:selfhost/Checker.zbr:152
            self.collectDecl(_zbr_at(module.decls.items, i), file);
// zbr:selfhost/Checker.zbr:153
            i = (i + 1);
        }
    }

    pub fn collectDecl(self: *_zbr_ty_DeadCodeChecker, decl: _zbr_ty_Decl, file: []const u8) void {
// zbr:selfhost/Checker.zbr:156
        switch (decl) {
            .union_ => |_ptr_u| {
                const u = _ptr_u.*;
// zbr:selfhost/Checker.zbr:158
                var ui: *_zbr_ty_UnionInfo = _zbr_ty_UnionInfo.init(u.name, file, u.span.line);
// zbr:selfhost/Checker.zbr:159
                var vi: i64 = 0;
// zbr:selfhost/Checker.zbr:160
                while (_zebra_lt(vi, @as(i64, @intCast(u.variants.items.len)))) {
// zbr:selfhost/Checker.zbr:161
                    const vt: _zbr_ty_UnionVariant = _zbr_at(u.variants.items, vi);
// zbr:selfhost/Checker.zbr:162
                    ui.addVariant(vt.name, vt.span.line);
// zbr:selfhost/Checker.zbr:163
                    vi = (vi + 1);
                }
// zbr:selfhost/Checker.zbr:164
                self.union_infos.put(_intern(u.name), ui) catch @panic("OOM");
            },
            .method => |_ptr_m| {
                const m = _ptr_m.*;
// zbr:selfhost/Checker.zbr:166
                if ((m.stmts != null)) {
// zbr:selfhost/Checker.zbr:167
                    self.registerModuleFn(file, m.name, m.span.line);
// zbr:selfhost/Checker.zbr:168
                    if (std.mem.eql(u8, m.name, "main")) {
// zbr:selfhost/Checker.zbr:169
                        self.markAsRoot(self.fnKey(file, "main"));
                    }
                }
            },
            .use_ => |_ptr_u| {
                const u = _ptr_u.*;
// zbr:selfhost/Checker.zbr:171
                var ei: i64 = 0;
// zbr:selfhost/Checker.zbr:172
                while (_zebra_lt(ei, @as(i64, @intCast(u.exposed.items.len)))) {
// zbr:selfhost/Checker.zbr:173
                    const ename: []const u8 = _zbr_at(u.exposed.items, ei);
// zbr:selfhost/Checker.zbr:174
                    self.exposed_names.put(_intern(ename), true) catch @panic("OOM");
// zbr:selfhost/Checker.zbr:175
                    ei = (ei + 1);
                }
            },
            .namespace_ => |_ptr_ns| {
                const ns = _ptr_ns.*;
// zbr:selfhost/Checker.zbr:177
                var ni: i64 = 0;
// zbr:selfhost/Checker.zbr:178
                while (_zebra_lt(ni, @as(i64, @intCast(ns.decls.items.len)))) {
// zbr:selfhost/Checker.zbr:179
                    self.collectDecl(_zbr_at(ns.decls.items, ni), file);
// zbr:selfhost/Checker.zbr:180
                    ni = (ni + 1);
                }
            },
            else => {
                // pass
            },
        }
    }

    pub fn walkModule(self: *_zbr_ty_DeadCodeChecker, module: _zbr_ty_Module) void {
// zbr:selfhost/Checker.zbr:187
        const file: []const u8 = module.file;
// zbr:selfhost/Checker.zbr:188
        self.current_file = _intern(file);
// zbr:selfhost/Checker.zbr:189
        var i: i64 = 0;
// zbr:selfhost/Checker.zbr:190
        while (_zebra_lt(i, @as(i64, @intCast(module.decls.items.len)))) {
// zbr:selfhost/Checker.zbr:191
            self.walkTopDecl(_zbr_at(module.decls.items, i), file);
// zbr:selfhost/Checker.zbr:192
            i = (i + 1);
        }
    }

    pub fn walkTopDecl(self: *_zbr_ty_DeadCodeChecker, decl: _zbr_ty_Decl, file: []const u8) void {
// zbr:selfhost/Checker.zbr:195
        switch (decl) {
            .class_ => |_ptr_c| {
                const c = _ptr_c.*;
// zbr:selfhost/Checker.zbr:197
                self.walkMemberDecls(c.members, file);
            },
            .struct_ => |_ptr_s| {
                const s = _ptr_s.*;
// zbr:selfhost/Checker.zbr:199
                self.walkMemberDecls(s.members, file);
            },
            .method => |_ptr_m| {
                const m = _ptr_m.*;
// zbr:selfhost/Checker.zbr:201
                if (m.stmts) |stmts| {
// zbr:selfhost/Checker.zbr:202
                    const fn_key: []const u8 = self.fnKey(file, m.name);
// zbr:selfhost/Checker.zbr:203
                    const saved: []const u8 = self.current_fn_key;
// zbr:selfhost/Checker.zbr:204
                    self.current_fn_key = _intern(fn_key);
// zbr:selfhost/Checker.zbr:205
                    self.walkStmts(stmts, file);
// zbr:selfhost/Checker.zbr:206
                    self.current_fn_key = _intern(saved);
                }
            },
            .var_ => |_ptr_v| {
                const v = _ptr_v.*;
// zbr:selfhost/Checker.zbr:208
                if ((v.init_expr != null)) {
// zbr:selfhost/Checker.zbr:209
                    const saved: []const u8 = self.current_fn_key;
// zbr:selfhost/Checker.zbr:210
                    self.current_fn_key = _intern("");
// zbr:selfhost/Checker.zbr:211
                    self.walkExpr(v.init_expr.?.*, file, false);
// zbr:selfhost/Checker.zbr:212
                    self.current_fn_key = _intern(saved);
                }
            },
            .namespace_ => |_ptr_ns| {
                const ns = _ptr_ns.*;
// zbr:selfhost/Checker.zbr:214
                var ni: i64 = 0;
// zbr:selfhost/Checker.zbr:215
                while (_zebra_lt(ni, @as(i64, @intCast(ns.decls.items.len)))) {
// zbr:selfhost/Checker.zbr:216
                    self.walkTopDecl(_zbr_at(ns.decls.items, ni), file);
// zbr:selfhost/Checker.zbr:217
                    ni = (ni + 1);
                }
            },
            else => {
                // pass
            },
        }
    }

    pub fn walkMemberDecls(self: *_zbr_ty_DeadCodeChecker, members: std.ArrayList(_zbr_ty_Decl), file: []const u8) void {
// zbr:selfhost/Checker.zbr:222
        const saved: []const u8 = self.current_fn_key;
// zbr:selfhost/Checker.zbr:223
        self.current_fn_key = _intern("");
// zbr:selfhost/Checker.zbr:224
        var i: i64 = 0;
// zbr:selfhost/Checker.zbr:225
        while (_zebra_lt(i, @as(i64, @intCast(members.items.len)))) {
// zbr:selfhost/Checker.zbr:226
            switch (_zbr_at(members.items, i)) {
                .method => |_ptr_m| {
                    const m = _ptr_m.*;
// zbr:selfhost/Checker.zbr:228
                    if (m.stmts) |stmts| {
// zbr:selfhost/Checker.zbr:229
                        self.walkStmts(stmts, file);
                    }
                },
                .init => |_ptr_ini| {
                    const ini = _ptr_ini.*;
// zbr:selfhost/Checker.zbr:231
                    if (ini.stmts) |stmts| {
// zbr:selfhost/Checker.zbr:232
                        self.walkStmts(stmts, file);
                    }
                },
                .var_ => |_ptr_v| {
                    const v = _ptr_v.*;
// zbr:selfhost/Checker.zbr:234
                    if ((v.init_expr != null)) {
// zbr:selfhost/Checker.zbr:235
                        self.walkExpr(v.init_expr.?.*, file, false);
                    }
                },
                else => {
                    // pass
                },
            }
// zbr:selfhost/Checker.zbr:238
            i = (i + 1);
        }
// zbr:selfhost/Checker.zbr:239
        self.current_fn_key = _intern(saved);
    }

    pub fn walkStmts(self: *_zbr_ty_DeadCodeChecker, stmts: std.ArrayList(_zbr_ty_Stmt), file: []const u8) void {
// zbr:selfhost/Checker.zbr:242
        var i: i64 = 0;
// zbr:selfhost/Checker.zbr:243
        while (_zebra_lt(i, @as(i64, @intCast(stmts.items.len)))) {
// zbr:selfhost/Checker.zbr:244
            self.walkStmt(_zbr_at(stmts.items, i), file);
// zbr:selfhost/Checker.zbr:245
            i = (i + 1);
        }
    }

    pub fn walkStmt(self: *_zbr_ty_DeadCodeChecker, stmt: _zbr_ty_Stmt, file: []const u8) void {
// zbr:selfhost/Checker.zbr:248
        switch (stmt) {
            .if_ => |_ptr_si| {
                const si = _ptr_si.*;
// zbr:selfhost/Checker.zbr:250
                self.walkExpr(si.cond.*, file, false);
// zbr:selfhost/Checker.zbr:251
                self.walkStmts(si.then_stmts, file);
// zbr:selfhost/Checker.zbr:252
                var ei: i64 = 0;
// zbr:selfhost/Checker.zbr:253
                while (_zebra_lt(ei, @as(i64, @intCast(si.else_ifs.items.len)))) {
// zbr:selfhost/Checker.zbr:254
                    const ef: _zbr_ty_ElseIf = _zbr_at(si.else_ifs.items, ei);
// zbr:selfhost/Checker.zbr:255
                    self.walkExpr(ef.cond, file, false);
// zbr:selfhost/Checker.zbr:256
                    self.walkStmts(ef.stmts, file);
// zbr:selfhost/Checker.zbr:257
                    ei = (ei + 1);
                }
// zbr:selfhost/Checker.zbr:258
                if (si.else_stmts) |es| {
// zbr:selfhost/Checker.zbr:259
                    self.walkStmts(es, file);
                }
            },
            .while_ => |_ptr_sw| {
                const sw = _ptr_sw.*;
// zbr:selfhost/Checker.zbr:261
                self.walkExpr(sw.cond.*, file, false);
// zbr:selfhost/Checker.zbr:262
                self.walkStmts(sw.stmts, file);
            },
            .for_in => |_ptr_fi| {
                const fi = _ptr_fi.*;
// zbr:selfhost/Checker.zbr:264
                self.walkExpr(fi.iter.*, file, false);
// zbr:selfhost/Checker.zbr:265
                if ((fi.filter != null)) {
// zbr:selfhost/Checker.zbr:266
                    self.walkExpr(fi.filter.?.*, file, false);
                }
// zbr:selfhost/Checker.zbr:267
                self.walkStmts(fi.stmts, file);
// zbr:selfhost/Checker.zbr:268
                if (fi.else_) |fe| {
// zbr:selfhost/Checker.zbr:269
                    self.walkStmts(fe, file);
                }
            },
            .for_num => |_ptr_fn2| {
                const fn2 = _ptr_fn2.*;
// zbr:selfhost/Checker.zbr:271
                self.walkExpr(fn2.start.*, file, false);
// zbr:selfhost/Checker.zbr:272
                self.walkExpr(fn2.stop_.*, file, false);
// zbr:selfhost/Checker.zbr:273
                if ((fn2.step != null)) {
// zbr:selfhost/Checker.zbr:274
                    self.walkExpr(fn2.step.?.*, file, false);
                }
// zbr:selfhost/Checker.zbr:275
                self.walkStmts(fn2.stmts, file);
// zbr:selfhost/Checker.zbr:276
                if (fn2.else_) |fne| {
// zbr:selfhost/Checker.zbr:277
                    self.walkStmts(fne, file);
                }
            },
            .branch_ => |_ptr_sb| {
                const sb = _ptr_sb.*;
// zbr:selfhost/Checker.zbr:279
                self.walkExpr(sb.expr.*, file, false);
// zbr:selfhost/Checker.zbr:280
                var ci: i64 = 0;
// zbr:selfhost/Checker.zbr:281
                while (_zebra_lt(ci, @as(i64, @intCast(sb.cases.items.len)))) {
// zbr:selfhost/Checker.zbr:282
                    const bc: _zbr_ty_BranchOn = _zbr_at(sb.cases.items, ci);
// zbr:selfhost/Checker.zbr:283
                    self.walkBranchValues(bc.values, file);
// zbr:selfhost/Checker.zbr:284
                    self.walkStmts(bc.stmts, file);
// zbr:selfhost/Checker.zbr:285
                    ci = (ci + 1);
                }
// zbr:selfhost/Checker.zbr:286
                if (sb.else_) |sbe| {
// zbr:selfhost/Checker.zbr:287
                    self.walkStmts(sbe, file);
                }
            },
            .return_ => |_ptr_sr| {
                const sr = _ptr_sr.*;
// zbr:selfhost/Checker.zbr:289
                if ((sr.value != null)) {
// zbr:selfhost/Checker.zbr:290
                    self.walkExpr(sr.value.?.*, file, false);
                }
            },
            .assign => |_ptr_sa| {
                const sa = _ptr_sa.*;
// zbr:selfhost/Checker.zbr:292
                self.walkExpr(sa.target.*, file, false);
// zbr:selfhost/Checker.zbr:293
                self.walkExpr(sa.value.*, file, false);
            },
            .var_ => |_ptr_sv| {
                const sv = _ptr_sv.*;
// zbr:selfhost/Checker.zbr:295
                if ((sv.init_expr != null)) {
// zbr:selfhost/Checker.zbr:296
                    self.walkExpr(sv.init_expr.?.*, file, false);
                }
            },
            .expr => |_ptr_se| {
                const se = _ptr_se.*;
// zbr:selfhost/Checker.zbr:298
                self.walkExpr(se, file, false);
            },
            .defer_ => |_ptr_sd| {
                const sd = _ptr_sd.*;
// zbr:selfhost/Checker.zbr:300
                self.walkStmt(sd.stmt.*, file);
            },
            .with_ => |_ptr_sw2| {
                const sw2 = _ptr_sw2.*;
// zbr:selfhost/Checker.zbr:302
                self.walkExpr(sw2.target.*, file, false);
// zbr:selfhost/Checker.zbr:303
                self.walkStmts(sw2.stmts, file);
            },
            .raise_ => |_ptr_sr2| {
                const sr2 = _ptr_sr2.*;
// zbr:selfhost/Checker.zbr:305
                if ((sr2.message != null)) {
// zbr:selfhost/Checker.zbr:306
                    self.walkExpr(sr2.message.?.*, file, false);
                }
// zbr:selfhost/Checker.zbr:307
                if ((sr2.details != null)) {
// zbr:selfhost/Checker.zbr:308
                    self.walkExpr(sr2.details.?.*, file, false);
                }
            },
            .try_catch => |_ptr_stc| {
                const stc = _ptr_stc.*;
// zbr:selfhost/Checker.zbr:310
                self.walkStmts(stc.stmts, file);
// zbr:selfhost/Checker.zbr:311
                var cli: i64 = 0;
// zbr:selfhost/Checker.zbr:312
                while (_zebra_lt(cli, @as(i64, @intCast(stc.clauses.items.len)))) {
// zbr:selfhost/Checker.zbr:313
                    const cl: _zbr_ty_CatchClause = _zbr_at(stc.clauses.items, cli);
// zbr:selfhost/Checker.zbr:314
                    self.walkStmts(cl.stmts, file);
// zbr:selfhost/Checker.zbr:315
                    cli = (cli + 1);
                }
            },
            .guard_ => |_ptr_sg| {
                const sg = _ptr_sg.*;
// zbr:selfhost/Checker.zbr:317
                self.walkExpr(sg.cond.*, file, false);
// zbr:selfhost/Checker.zbr:318
                self.walkStmts(sg.else_stmts, file);
            },
            .destruct => |_ptr_sdt| {
                const sdt = _ptr_sdt.*;
// zbr:selfhost/Checker.zbr:320
                self.walkExpr(sdt.init_expr.*, file, false);
            },
            .allocate_ => |_ptr_sal| {
                const sal = _ptr_sal.*;
// zbr:selfhost/Checker.zbr:322
                self.walkExpr(sal.source, file, false);
// zbr:selfhost/Checker.zbr:323
                self.walkStmts(sal.stmts, file);
            },
            .copy_out => |_ptr_sco| {
                const sco = _ptr_sco.*;
// zbr:selfhost/Checker.zbr:325
                self.walkExpr(sco.target, file, false);
// zbr:selfhost/Checker.zbr:326
                self.walkExpr(sco.value, file, false);
            },
            .print_ => |_ptr_sp| {
                const sp = _ptr_sp.*;
// zbr:selfhost/Checker.zbr:328
                var pi: i64 = 0;
// zbr:selfhost/Checker.zbr:329
                while (_zebra_lt(pi, @as(i64, @intCast(sp.args.items.len)))) {
// zbr:selfhost/Checker.zbr:330
                    self.walkExpr(_zbr_at(sp.args.items, pi), file, false);
// zbr:selfhost/Checker.zbr:331
                    pi = (pi + 1);
                }
            },
            .assert_ => |_ptr_sa2| {
                const sa2 = _ptr_sa2.*;
// zbr:selfhost/Checker.zbr:333
                self.walkExpr(sa2.cond.*, file, false);
// zbr:selfhost/Checker.zbr:334
                if ((sa2.message != null)) {
// zbr:selfhost/Checker.zbr:335
                    self.walkExpr(sa2.message.?.*, file, false);
                }
            },
            .assert_eq_ => |_ptr_saeq| {
                const saeq = _ptr_saeq.*;
// zbr:selfhost/Checker.zbr:337
                self.walkExpr(saeq.lhs.*, file, false);
// zbr:selfhost/Checker.zbr:338
                self.walkExpr(saeq.rhs.*, file, false);
            },
            .assert_ne_ => |_ptr_sane| {
                const sane = _ptr_sane.*;
// zbr:selfhost/Checker.zbr:340
                self.walkExpr(sane.lhs.*, file, false);
// zbr:selfhost/Checker.zbr:341
                self.walkExpr(sane.rhs.*, file, false);
            },
            .assert_true_ => |_ptr_sat| {
                const sat = _ptr_sat.*;
// zbr:selfhost/Checker.zbr:343
                self.walkExpr(sat.expr.*, file, false);
            },
            .assert_false_ => |_ptr_saf| {
                const saf = _ptr_saf.*;
// zbr:selfhost/Checker.zbr:345
                self.walkExpr(saf.expr.*, file, false);
            },
            .contract => |_ptr_sct| {
                const sct = _ptr_sct.*;
// zbr:selfhost/Checker.zbr:347
                var cti: i64 = 0;
// zbr:selfhost/Checker.zbr:348
                while (_zebra_lt(cti, @as(i64, @intCast(sct.exprs.items.len)))) {
// zbr:selfhost/Checker.zbr:349
                    self.walkExpr(_zbr_at(sct.exprs.items, cti), file, false);
// zbr:selfhost/Checker.zbr:350
                    cti = (cti + 1);
                }
            },
            else => {
                // pass
            },
        }
    }

    pub fn walkBranchValues(self: *_zbr_ty_DeadCodeChecker, values: std.ArrayList(_zbr_ty_Expr), file: []const u8) void {
// zbr:selfhost/Checker.zbr:355
        var vi: i64 = 0;
// zbr:selfhost/Checker.zbr:356
        while (_zebra_lt(vi, @as(i64, @intCast(values.items.len)))) {
// zbr:selfhost/Checker.zbr:357
            self.walkExpr(_zbr_at(values.items, vi), file, true);
// zbr:selfhost/Checker.zbr:358
            vi = (vi + 1);
        }
    }

    pub fn walkCapture(self: *_zbr_ty_DeadCodeChecker, cap: _zbr_ty_DeclVar, file: []const u8) void {
// zbr:selfhost/Checker.zbr:363
        if ((cap.init_expr != null)) {
// zbr:selfhost/Checker.zbr:364
            self.walkExpr(cap.init_expr.?.*, file, false);
        }
    }

    pub fn walkDictEntry(self: *_zbr_ty_DeadCodeChecker, entry: _zbr_ty_DictEntry, file: []const u8) void {
// zbr:selfhost/Checker.zbr:369
        self.walkExpr(entry.key.*, file, false);
// zbr:selfhost/Checker.zbr:370
        self.walkExpr(entry.value.*, file, false);
    }

    pub fn walkExpr(self: *_zbr_ty_DeadCodeChecker, expr: _zbr_ty_Expr, file: []const u8, in_match: bool) void {
// zbr:selfhost/Checker.zbr:373
        switch (expr) {
            .member => |_ptr_em| {
                const em = _ptr_em.*;
// zbr:selfhost/Checker.zbr:375
                const mem_name: []const u8 = em.member;
// zbr:selfhost/Checker.zbr:376
                if (em.object.* == .ident) {
                    const eid = em.object.*.ident;
// zbr:selfhost/Checker.zbr:377
                    const obj: []const u8 = eid.name;
// zbr:selfhost/Checker.zbr:378
                    if (self.isKnownUnion(obj)) {
// zbr:selfhost/Checker.zbr:379
                        if (in_match) {
// zbr:selfhost/Checker.zbr:380
                            self.recordMatch(obj, mem_name, file, em.span.line);
                        } else {
// zbr:selfhost/Checker.zbr:382
                            self.recordConstruction(obj, mem_name);
                        }
                    }
                } else {
// zbr:selfhost/Checker.zbr:385
                    self.walkExpr(em.object.*, file, false);
                }
            },
            .call => |_ptr_ec| {
                const ec = _ptr_ec.*;
// zbr:selfhost/Checker.zbr:387
                var is_union_ctor: bool = false;
// zbr:selfhost/Checker.zbr:388
                if (ec.callee == .member) {
                    const cm_ptr = ec.callee.member;
                    const cm = cm_ptr.*;
// zbr:selfhost/Checker.zbr:389
                    if (cm.object.* == .ident) {
                        const cid = cm.object.*.ident;
// zbr:selfhost/Checker.zbr:390
                        if (self.isKnownUnion(cid.name)) {
// zbr:selfhost/Checker.zbr:391
                            is_union_ctor = true;
// zbr:selfhost/Checker.zbr:392
                            const v_name: []const u8 = cm.member;
// zbr:selfhost/Checker.zbr:393
                            if (in_match) {
// zbr:selfhost/Checker.zbr:394
                                self.recordMatch(cid.name, v_name, file, cm.span.line);
                            } else {
// zbr:selfhost/Checker.zbr:396
                                self.recordConstruction(cid.name, v_name);
                            }
                        }
                    }
                }
// zbr:selfhost/Checker.zbr:397
                if ((!is_union_ctor)) {
// zbr:selfhost/Checker.zbr:400
                    if (ec.callee == .member) {
                        const cal_m_ptr = ec.callee.member;
                        const cal_m = cal_m_ptr.*;
// zbr:selfhost/Checker.zbr:401
                        self.walkExpr(cal_m.object.*, file, false);
                    }
                }
// zbr:selfhost/Checker.zbr:404
                if (ec.callee == .ident) {
                    const cfn = ec.callee.ident;
// zbr:selfhost/Checker.zbr:405
                    self.trackFnCall(cfn.name);
                }
// zbr:selfhost/Checker.zbr:406
                var ai: i64 = 0;
// zbr:selfhost/Checker.zbr:407
                while (_zebra_lt(ai, @as(i64, @intCast(ec.args.items.len)))) {
// zbr:selfhost/Checker.zbr:410
                    const aarg: _zbr_ty_Arg = _zbr_at(ec.args.items, ai);
// zbr:selfhost/Checker.zbr:411
                    switch (aarg.value) {
                        .member => |_ptr_avm| {
                            const avm = _ptr_avm.*;
// zbr:selfhost/Checker.zbr:413
                            if (avm.object.* == .ident) {
                                const avid = avm.object.*.ident;
// zbr:selfhost/Checker.zbr:414
                                if (self.isKnownUnion(avid.name)) {
// zbr:selfhost/Checker.zbr:415
                                    if (in_match) {
// zbr:selfhost/Checker.zbr:416
                                        self.recordMatch(avid.name, avm.member, file, avm.span.line);
                                    } else {
// zbr:selfhost/Checker.zbr:418
                                        self.recordConstruction(avid.name, avm.member);
                                    }
                                } else {
// zbr:selfhost/Checker.zbr:420
                                    self.walkExpr(avm.object.*, file, false);
                                }
                            }
                        },
                        .call => |_ptr_avc| {
                            const avc = _ptr_avc.*;
// zbr:selfhost/Checker.zbr:422
                            if (avc.callee == .member) {
                                const avcm_ptr = avc.callee.member;
                                const avcm = avcm_ptr.*;
// zbr:selfhost/Checker.zbr:423
                                if (avcm.object.* == .ident) {
                                    const avci = avcm.object.*.ident;
// zbr:selfhost/Checker.zbr:424
                                    if (self.isKnownUnion(avci.name)) {
// zbr:selfhost/Checker.zbr:425
                                        if (in_match) {
// zbr:selfhost/Checker.zbr:426
                                            self.recordMatch(avci.name, avcm.member, file, avcm.span.line);
                                        } else {
// zbr:selfhost/Checker.zbr:428
                                            self.recordConstruction(avci.name, avcm.member);
                                        }
                                    }
                                }
                            }
// zbr:selfhost/Checker.zbr:429
                            if (avc.callee == .ident) {
                                const avcfn = avc.callee.ident;
// zbr:selfhost/Checker.zbr:430
                                self.trackFnCall(avcfn.name);
                            }
                        },
                        .type_check => |_ptr_avtc| {
                            const avtc = _ptr_avtc.*;
// zbr:selfhost/Checker.zbr:432
                            if (avtc.variant_name) |vn| {
// zbr:selfhost/Checker.zbr:433
                                self.recordMatch(avtc.type_name, vn, file, avtc.span.line);
                            }
// zbr:selfhost/Checker.zbr:434
                            self.walkExpr(avtc.expr.*, file, false);
                        },
                        .binary => |_ptr_avb| {
                            const avb = _ptr_avb.*;
// zbr:selfhost/Checker.zbr:436
                            self.walkExpr(avb.left.*, file, false);
// zbr:selfhost/Checker.zbr:437
                            self.walkExpr(avb.right.*, file, false);
                        },
                        .unary => |_ptr_avu| {
                            const avu = _ptr_avu.*;
// zbr:selfhost/Checker.zbr:439
                            self.walkExpr(avu.operand.*, file, false);
                        },
                        else => {
                            // pass
                        },
                    }
// zbr:selfhost/Checker.zbr:442
                    ai = (ai + 1);
                }
            },
            .type_check => |_ptr_etc| {
                const etc = _ptr_etc.*;
// zbr:selfhost/Checker.zbr:444
                if (etc.variant_name) |vn| {
// zbr:selfhost/Checker.zbr:445
                    self.recordMatch(etc.type_name, vn, file, etc.span.line);
                }
// zbr:selfhost/Checker.zbr:446
                self.walkExpr(etc.expr.*, file, false);
            },
            .binary => |_ptr_eb| {
                const eb = _ptr_eb.*;
// zbr:selfhost/Checker.zbr:448
                self.walkExpr(eb.left.*, file, false);
// zbr:selfhost/Checker.zbr:449
                self.walkExpr(eb.right.*, file, false);
            },
            .unary => |_ptr_eu| {
                const eu = _ptr_eu.*;
// zbr:selfhost/Checker.zbr:451
                self.walkExpr(eu.operand.*, file, false);
            },
            .index => |_ptr_eidx| {
                const eidx = _ptr_eidx.*;
// zbr:selfhost/Checker.zbr:453
                self.walkExpr(eidx.object.*, file, false);
// zbr:selfhost/Checker.zbr:454
                self.walkExpr(eidx.index.*, file, false);
            },
            .slice => |_ptr_esl| {
                const esl = _ptr_esl.*;
// zbr:selfhost/Checker.zbr:456
                self.walkExpr(esl.object.*, file, false);
// zbr:selfhost/Checker.zbr:457
                if ((esl.start != null)) {
// zbr:selfhost/Checker.zbr:458
                    self.walkExpr(esl.start.?.*, file, false);
                }
// zbr:selfhost/Checker.zbr:459
                if ((esl.stop_ != null)) {
// zbr:selfhost/Checker.zbr:460
                    self.walkExpr(esl.stop_.?.*, file, false);
                }
            },
            .cast => |_ptr_ec2| {
                const ec2 = _ptr_ec2.*;
// zbr:selfhost/Checker.zbr:462
                self.walkExpr(ec2.expr.*, file, false);
            },
            .to_non_nil => |_ptr_etnn| {
                const etnn = _ptr_etnn.*;
// zbr:selfhost/Checker.zbr:464
                self.walkExpr(etnn.expr.*, file, false);
            },
            .is_nil => |_ptr_ein| {
                const ein = _ptr_ein.*;
// zbr:selfhost/Checker.zbr:466
                self.walkExpr(ein.expr.*, file, false);
            },
            .orelse_ => |_ptr_eo| {
                const eo = _ptr_eo.*;
// zbr:selfhost/Checker.zbr:468
                self.walkExpr(eo.expr.*, file, false);
// zbr:selfhost/Checker.zbr:469
                self.walkExpr(eo.fallback.*, file, false);
            },
            .catch_ => |_ptr_eca| {
                const eca = _ptr_eca.*;
// zbr:selfhost/Checker.zbr:471
                self.walkExpr(eca.expr.*, file, false);
// zbr:selfhost/Checker.zbr:472
                self.walkExpr(eca.fallback.*, file, false);
            },
            .if_expr => |_ptr_eif| {
                const eif = _ptr_eif.*;
// zbr:selfhost/Checker.zbr:474
                self.walkExpr(eif.cond.*, file, false);
// zbr:selfhost/Checker.zbr:475
                self.walkExpr(eif.then_expr.*, file, false);
// zbr:selfhost/Checker.zbr:476
                self.walkExpr(eif.else_expr.*, file, false);
            },
            .lambda => |_ptr_el| {
                const el = _ptr_el.*;
// zbr:selfhost/Checker.zbr:478
                var ci: i64 = 0;
// zbr:selfhost/Checker.zbr:479
                while (_zebra_lt(ci, @as(i64, @intCast(el.captures.items.len)))) {
// zbr:selfhost/Checker.zbr:480
                    self.walkCapture(_zbr_at(el.captures.items, ci), file);
// zbr:selfhost/Checker.zbr:481
                    ci = (ci + 1);
                }
// zbr:selfhost/Checker.zbr:482
                switch (el.body_) {
                    .expr_ => |le| {
// zbr:selfhost/Checker.zbr:484
                        self.walkExpr(le, file, false);
                    },
                    .stmts => |ls| {
// zbr:selfhost/Checker.zbr:486
                        self.walkStmts(ls, file);
                    },
                }
            },
            .list_lit => |_ptr_ell| {
                const ell = _ptr_ell.*;
// zbr:selfhost/Checker.zbr:488
                var eli: i64 = 0;
// zbr:selfhost/Checker.zbr:489
                while (_zebra_lt(eli, @as(i64, @intCast(ell.elems.items.len)))) {
// zbr:selfhost/Checker.zbr:490
                    self.walkExpr(_zbr_at(ell.elems.items, eli), file, false);
// zbr:selfhost/Checker.zbr:491
                    eli = (eli + 1);
                }
            },
            .set_lit => |_ptr_esl| {
                const esl = _ptr_esl.*;
// zbr:selfhost/Checker.zbr:493
                var sli: i64 = 0;
// zbr:selfhost/Checker.zbr:494
                while (_zebra_lt(sli, @as(i64, @intCast(esl.elems.items.len)))) {
// zbr:selfhost/Checker.zbr:495
                    self.walkExpr(_zbr_at(esl.elems.items, sli), file, false);
// zbr:selfhost/Checker.zbr:496
                    sli = (sli + 1);
                }
            },
            .dict_lit => |_ptr_edl| {
                const edl = _ptr_edl.*;
// zbr:selfhost/Checker.zbr:498
                var dli: i64 = 0;
// zbr:selfhost/Checker.zbr:499
                while (_zebra_lt(dli, @as(i64, @intCast(edl.entries.items.len)))) {
// zbr:selfhost/Checker.zbr:500
                    self.walkDictEntry(_zbr_at(edl.entries.items, dli), file);
// zbr:selfhost/Checker.zbr:501
                    dli = (dli + 1);
                }
            },
            .array_lit => |_ptr_eal| {
                const eal = _ptr_eal.*;
// zbr:selfhost/Checker.zbr:503
                var ali: i64 = 0;
// zbr:selfhost/Checker.zbr:504
                while (_zebra_lt(ali, @as(i64, @intCast(eal.elems.items.len)))) {
// zbr:selfhost/Checker.zbr:505
                    self.walkExpr(_zbr_at(eal.elems.items, ali), file, false);
// zbr:selfhost/Checker.zbr:506
                    ali = (ali + 1);
                }
            },
            .string_interp => |_ptr_esi| {
                const esi = _ptr_esi.*;
// zbr:selfhost/Checker.zbr:508
                var spi: i64 = 0;
// zbr:selfhost/Checker.zbr:509
                while (_zebra_lt(spi, @as(i64, @intCast(esi.parts.items.len)))) {
// zbr:selfhost/Checker.zbr:510
                    const part: _zbr_ty_StringPart = _zbr_at(esi.parts.items, spi);
// zbr:selfhost/Checker.zbr:511
                    if (part == .expr_) {
                        const pe_ptr = part.expr_;
                        const pe = pe_ptr.*;
// zbr:selfhost/Checker.zbr:512
                        self.walkExpr(pe, file, false);
                    }
// zbr:selfhost/Checker.zbr:513
                    spi = (spi + 1);
                }
            },
            .tuple_lit => |_ptr_etup| {
                const etup = _ptr_etup.*;
// zbr:selfhost/Checker.zbr:515
                var ti: i64 = 0;
// zbr:selfhost/Checker.zbr:516
                while (_zebra_lt(ti, @as(i64, @intCast(etup.elems.items.len)))) {
// zbr:selfhost/Checker.zbr:517
                    self.walkExpr(_zbr_at(etup.elems.items, ti), file, false);
// zbr:selfhost/Checker.zbr:518
                    ti = (ti + 1);
                }
            },
            .try_ => |_ptr_etr| {
                const etr = _ptr_etr.*;
// zbr:selfhost/Checker.zbr:520
                self.walkExpr(etr.expr.*, file, false);
            },
            .chained_cmp => |_ptr_ecc| {
                const ecc = _ptr_ecc.*;
// zbr:selfhost/Checker.zbr:522
                var cci: i64 = 0;
// zbr:selfhost/Checker.zbr:523
                while (_zebra_lt(cci, @as(i64, @intCast(ecc.operands.items.len)))) {
// zbr:selfhost/Checker.zbr:524
                    self.walkExpr(_zbr_at(ecc.operands.items, cci), file, false);
// zbr:selfhost/Checker.zbr:525
                    cci = (cci + 1);
                }
            },
            .except_ => |_ptr_eex| {
                const eex = _ptr_eex.*;
// zbr:selfhost/Checker.zbr:527
                self.walkExpr(eex.base, file, false);
// zbr:selfhost/Checker.zbr:528
                var exi: i64 = 0;
// zbr:selfhost/Checker.zbr:529
                while (_zebra_lt(exi, @as(i64, @intCast(eex.fields.items.len)))) {
// zbr:selfhost/Checker.zbr:532
                    const exf: _zbr_ty_ExceptField = _zbr_at(eex.fields.items, exi);
// zbr:selfhost/Checker.zbr:533
                    switch (exf.value) {
                        .member => |_ptr_efvm| {
                            const efvm = _ptr_efvm.*;
// zbr:selfhost/Checker.zbr:535
                            if (efvm.object.* == .ident) {
                                const efvid = efvm.object.*.ident;
// zbr:selfhost/Checker.zbr:536
                                if (self.isKnownUnion(efvid.name)) {
// zbr:selfhost/Checker.zbr:537
                                    self.recordConstruction(efvid.name, efvm.member);
                                } else {
// zbr:selfhost/Checker.zbr:539
                                    self.walkExpr(efvm.object.*, file, false);
                                }
                            }
                        },
                        .call => |_ptr_efvc| {
                            const efvc = _ptr_efvc.*;
// zbr:selfhost/Checker.zbr:541
                            if (efvc.callee == .member) {
                                const efvcm_ptr = efvc.callee.member;
                                const efvcm = efvcm_ptr.*;
// zbr:selfhost/Checker.zbr:542
                                if (efvcm.object.* == .ident) {
                                    const efvci = efvcm.object.*.ident;
// zbr:selfhost/Checker.zbr:543
                                    if (self.isKnownUnion(efvci.name)) {
// zbr:selfhost/Checker.zbr:544
                                        self.recordConstruction(efvci.name, efvcm.member);
                                    }
                                }
                            }
                        },
                        .binary => |_ptr_efvb| {
                            const efvb = _ptr_efvb.*;
// zbr:selfhost/Checker.zbr:546
                            self.walkExpr(efvb.left.*, file, false);
// zbr:selfhost/Checker.zbr:547
                            self.walkExpr(efvb.right.*, file, false);
                        },
                        else => {
                            // pass
                        },
                    }
// zbr:selfhost/Checker.zbr:550
                    exi = (exi + 1);
                }
            },
            .old_ => |_ptr_eold| {
                const eold = _ptr_eold.*;
// zbr:selfhost/Checker.zbr:552
                self.walkExpr(eold.operand.*, file, false);
            },
            else => {
                // pass
            },
        }
    }

    pub fn computeReachability(self: *_zbr_ty_DeadCodeChecker) void {
// zbr:selfhost/Checker.zbr:559
        var pending = std.ArrayList([]const u8).empty;
// zbr:selfhost/Checker.zbr:561
        var ri: i64 = 0;
// zbr:selfhost/Checker.zbr:562
        while (_zebra_lt(ri, @as(i64, @intCast(self.root_key_list.items.len)))) {
// zbr:selfhost/Checker.zbr:563
            pending.append(_zbr_rt._allocator, _intern(_zbr_at(self.root_key_list.items, ri))) catch @panic("OOM");
// zbr:selfhost/Checker.zbr:564
            ri = (ri + 1);
        }
// zbr:selfhost/Checker.zbr:566
        var mi: i64 = 0;
// zbr:selfhost/Checker.zbr:567
        while (_zebra_lt(mi, @as(i64, @intCast(self.module_fn_key_list.items.len)))) {
// zbr:selfhost/Checker.zbr:568
            const mfk: []const u8 = _zbr_at(self.module_fn_key_list.items, mi);
// zbr:selfhost/Checker.zbr:569
            const fn_name: []const u8 = self.extractFnName(mfk);
// zbr:selfhost/Checker.zbr:570
            if (self.exposed_names.contains(fn_name)) {
// zbr:selfhost/Checker.zbr:571
                pending.append(_zbr_rt._allocator, _intern(mfk)) catch @panic("OOM");
            }
// zbr:selfhost/Checker.zbr:572
            mi = (mi + 1);
        }
// zbr:selfhost/Checker.zbr:574
        var qi: i64 = 0;
// zbr:selfhost/Checker.zbr:575
        while (_zebra_lt(qi, @as(i64, @intCast(pending.items.len)))) {
// zbr:selfhost/Checker.zbr:576
            const key: []const u8 = _zbr_at(pending.items, qi);
// zbr:selfhost/Checker.zbr:577
            if ((!self.reachable_set.contains(key))) {
// zbr:selfhost/Checker.zbr:578
                self.reachable_set.put(_intern(key), true) catch @panic("OOM");
// zbr:selfhost/Checker.zbr:579
                if (self.fn_edges.contains(key)) {
// zbr:selfhost/Checker.zbr:580
                    const edges: std.ArrayList([]const u8) = (self.fn_edges.get(key).?);
// zbr:selfhost/Checker.zbr:581
                    var ei: i64 = 0;
// zbr:selfhost/Checker.zbr:582
                    while (_zebra_lt(ei, @as(i64, @intCast(edges.items.len)))) {
// zbr:selfhost/Checker.zbr:583
                        const target: []const u8 = _zbr_at(edges.items, ei);
// zbr:selfhost/Checker.zbr:584
                        if ((!self.reachable_set.contains(target))) {
// zbr:selfhost/Checker.zbr:585
                            pending.append(_zbr_rt._allocator, _intern(target)) catch @panic("OOM");
                        }
// zbr:selfhost/Checker.zbr:586
                        ei = (ei + 1);
                    }
                }
            }
// zbr:selfhost/Checker.zbr:587
            qi = (qi + 1);
        }
    }

    pub fn hasIssues(self: *_zbr_ty_DeadCodeChecker) bool {
// zbr:selfhost/Checker.zbr:592
        var i: i64 = 0;
// zbr:selfhost/Checker.zbr:593
        while (_zebra_lt(i, @as(i64, @intCast(self.match_key_list.items.len)))) {
// zbr:selfhost/Checker.zbr:594
            if ((!self.constructed_set.contains(_zbr_at(self.match_key_list.items, i)))) {
// zbr:selfhost/Checker.zbr:595
                return true;
            }
// zbr:selfhost/Checker.zbr:596
            i = (i + 1);
        }
// zbr:selfhost/Checker.zbr:597
        i = 0;
// zbr:selfhost/Checker.zbr:598
        while (_zebra_lt(i, @as(i64, @intCast(self.constructed_key_list.items.len)))) {
// zbr:selfhost/Checker.zbr:599
            if ((!self.match_sites.contains(_zbr_at(self.constructed_key_list.items, i)))) {
// zbr:selfhost/Checker.zbr:600
                return true;
            }
// zbr:selfhost/Checker.zbr:601
            i = (i + 1);
        }
// zbr:selfhost/Checker.zbr:602
        i = 0;
// zbr:selfhost/Checker.zbr:603
        while (_zebra_lt(i, @as(i64, @intCast(self.module_fn_key_list.items.len)))) {
// zbr:selfhost/Checker.zbr:604
            if ((!self.reachable_set.contains(_zbr_at(self.module_fn_key_list.items, i)))) {
// zbr:selfhost/Checker.zbr:605
                return true;
            }
// zbr:selfhost/Checker.zbr:606
            i = (i + 1);
        }
// zbr:selfhost/Checker.zbr:607
        return false;
    }

    pub fn report(self: *_zbr_ty_DeadCodeChecker) []const u8 {
// zbr:selfhost/Checker.zbr:610
        var sb = std.ArrayList(u8).empty;
// zbr:selfhost/Checker.zbr:611
        const RED: []const u8 = "\x1b[31m";
// zbr:selfhost/Checker.zbr:612
        const YLW: []const u8 = "\x1b[33m";
// zbr:selfhost/Checker.zbr:613
        const CYN: []const u8 = "\x1b[36m";
// zbr:selfhost/Checker.zbr:614
        const BLD: []const u8 = "\x1b[1m";
// zbr:selfhost/Checker.zbr:615
        const RST: []const u8 = "\x1b[0m";
// zbr:selfhost/Checker.zbr:618
        var dead_count: i64 = 0;
// zbr:selfhost/Checker.zbr:619
        var dead_sb = std.ArrayList(u8).empty;
// zbr:selfhost/Checker.zbr:620
        var i: i64 = 0;
// zbr:selfhost/Checker.zbr:621
        while (_zebra_lt(i, @as(i64, @intCast(self.match_key_list.items.len)))) {
// zbr:selfhost/Checker.zbr:622
            const key: []const u8 = _zbr_at(self.match_key_list.items, i);
// zbr:selfhost/Checker.zbr:623
            if ((!self.constructed_set.contains(key))) {
// zbr:selfhost/Checker.zbr:624
                dead_count = (dead_count + 1);
// zbr:selfhost/Checker.zbr:625
                const kparts: std.ArrayList([]const u8) = blk092_2: { var _ll_2: std.ArrayList([]const u8) = std.ArrayList([]const u8).empty; var _split_iter_2 = std.mem.splitSequence(u8, key, ":"); while (_split_iter_2.next()) |_se_2| { _ll_2.append(_zbr_rt._allocator, _se_2) catch @panic("OOM"); } break :blk092_2 _ll_2; };
// zbr:selfhost/Checker.zbr:626
                const uname: []const u8 = _zbr_at(kparts.items, 0);
// zbr:selfhost/Checker.zbr:627
                const vname: []const u8 = _zbr_at(kparts.items, 1);
// zbr:selfhost/Checker.zbr:628
                dead_sb.appendSlice(_zbr_rt._allocator, _str_concat(_str_concat(_str_concat(_str_concat(_str_concat(_str_concat(_str_concat(_str_concat(_str_concat(_str_concat("  ", BLD, _zbr_rt._allocator), "[", _zbr_rt._allocator), uname, _zbr_rt._allocator), "]", _zbr_rt._allocator), RST, _zbr_rt._allocator), "  ", _zbr_rt._allocator), YLW, _zbr_rt._allocator), vname, _zbr_rt._allocator), RST, _zbr_rt._allocator), "\n", _zbr_rt._allocator)) catch @panic("OOM");
// zbr:selfhost/Checker.zbr:629
                const sites: std.ArrayList([]const u8) = (self.match_sites.get(key).?);
// zbr:selfhost/Checker.zbr:630
                var si: i64 = 0;
// zbr:selfhost/Checker.zbr:631
                while (_zebra_lt(si, @as(i64, @intCast(sites.items.len)))) {
// zbr:selfhost/Checker.zbr:632
                    dead_sb.appendSlice(_zbr_rt._allocator, _str_concat(_str_concat(_str_concat(_str_concat("    ", CYN, _zbr_rt._allocator), _zbr_at(sites.items, si), _zbr_rt._allocator), RST, _zbr_rt._allocator), "\n", _zbr_rt._allocator)) catch @panic("OOM");
// zbr:selfhost/Checker.zbr:633
                    si = (si + 1);
                }
// zbr:selfhost/Checker.zbr:634
                dead_sb.appendSlice(_zbr_rt._allocator, "\n") catch @panic("OOM");
            }
// zbr:selfhost/Checker.zbr:635
            i = (i + 1);
        }
// zbr:selfhost/Checker.zbr:638
        var phantom_count: i64 = 0;
// zbr:selfhost/Checker.zbr:639
        var phantom_sb = std.ArrayList(u8).empty;
// zbr:selfhost/Checker.zbr:640
        i = 0;
// zbr:selfhost/Checker.zbr:641
        while (_zebra_lt(i, @as(i64, @intCast(self.constructed_key_list.items.len)))) {
// zbr:selfhost/Checker.zbr:642
            const key: []const u8 = _zbr_at(self.constructed_key_list.items, i);
// zbr:selfhost/Checker.zbr:643
            if ((!self.match_sites.contains(key))) {
// zbr:selfhost/Checker.zbr:644
                phantom_count = (phantom_count + 1);
// zbr:selfhost/Checker.zbr:645
                const kparts: std.ArrayList([]const u8) = blk092_3: { var _ll_3: std.ArrayList([]const u8) = std.ArrayList([]const u8).empty; var _split_iter_3 = std.mem.splitSequence(u8, key, ":"); while (_split_iter_3.next()) |_se_3| { _ll_3.append(_zbr_rt._allocator, _se_3) catch @panic("OOM"); } break :blk092_3 _ll_3; };
// zbr:selfhost/Checker.zbr:646
                const uname: []const u8 = _zbr_at(kparts.items, 0);
// zbr:selfhost/Checker.zbr:647
                const vname: []const u8 = _zbr_at(kparts.items, 1);
// zbr:selfhost/Checker.zbr:648
                phantom_sb.appendSlice(_zbr_rt._allocator, _str_concat(_str_concat(_str_concat(_str_concat(_str_concat(_str_concat(_str_concat(_str_concat(_str_concat(_str_concat("  ", BLD, _zbr_rt._allocator), "[", _zbr_rt._allocator), uname, _zbr_rt._allocator), "]", _zbr_rt._allocator), RST, _zbr_rt._allocator), "  ", _zbr_rt._allocator), YLW, _zbr_rt._allocator), vname, _zbr_rt._allocator), RST, _zbr_rt._allocator), "\n\n", _zbr_rt._allocator)) catch @panic("OOM");
            }
// zbr:selfhost/Checker.zbr:649
            i = (i + 1);
        }
// zbr:selfhost/Checker.zbr:652
        var unreachable_count: i64 = 0;
// zbr:selfhost/Checker.zbr:653
        var unreach_sb = std.ArrayList(u8).empty;
// zbr:selfhost/Checker.zbr:654
        i = 0;
// zbr:selfhost/Checker.zbr:655
        while (_zebra_lt(i, @as(i64, @intCast(self.module_fn_key_list.items.len)))) {
// zbr:selfhost/Checker.zbr:656
            const key: []const u8 = _zbr_at(self.module_fn_key_list.items, i);
// zbr:selfhost/Checker.zbr:657
            if ((!self.reachable_set.contains(key))) {
// zbr:selfhost/Checker.zbr:658
                unreachable_count = (unreachable_count + 1);
// zbr:selfhost/Checker.zbr:662
                var loc: []const u8 = "";
// zbr:selfhost/Checker.zbr:663
                if (self.module_fns.contains(key)) {
// zbr:selfhost/Checker.zbr:664
                    loc = (self.module_fns.get(key).?);
                }
// zbr:selfhost/Checker.zbr:665
                const fn_name: []const u8 = self.extractFnName(key);
// zbr:selfhost/Checker.zbr:666
                unreach_sb.appendSlice(_zbr_rt._allocator, _str_concat(_str_concat(_str_concat(_str_concat(_str_concat(_str_concat(_str_concat(_str_concat("  ", CYN, _zbr_rt._allocator), loc, _zbr_rt._allocator), RST, _zbr_rt._allocator), "  ", _zbr_rt._allocator), YLW, _zbr_rt._allocator), fn_name, _zbr_rt._allocator), RST, _zbr_rt._allocator), "\n", _zbr_rt._allocator)) catch @panic("OOM");
            }
// zbr:selfhost/Checker.zbr:667
            i = (i + 1);
        }
// zbr:selfhost/Checker.zbr:670
        if (_zebra_gt(dead_count, 0)) {
// zbr:selfhost/Checker.zbr:671
            sb.appendSlice(_zbr_rt._allocator, _str_concat(_str_concat(_str_concat(_str_concat(_str_concat(_str_concat(RED, BLD, _zbr_rt._allocator), "dead union arms", _zbr_rt._allocator), RST, _zbr_rt._allocator), " — matched but never constructed (", _zbr_rt._allocator), (std.fmt.allocPrint(_zbr_rt._allocator, "{}", .{dead_count}) catch @panic("OOM")), _zbr_rt._allocator), "):\n\n", _zbr_rt._allocator)) catch @panic("OOM");
// zbr:selfhost/Checker.zbr:672
            sb.appendSlice(_zbr_rt._allocator, (dead_sb.toOwnedSlice(_zbr_rt._allocator) catch "")) catch @panic("OOM");
        }
// zbr:selfhost/Checker.zbr:674
        if (_zebra_gt(phantom_count, 0)) {
// zbr:selfhost/Checker.zbr:675
            sb.appendSlice(_zbr_rt._allocator, _str_concat(_str_concat(_str_concat(_str_concat(_str_concat(_str_concat(YLW, BLD, _zbr_rt._allocator), "phantom variants", _zbr_rt._allocator), RST, _zbr_rt._allocator), " — constructed but never matched (", _zbr_rt._allocator), (std.fmt.allocPrint(_zbr_rt._allocator, "{}", .{phantom_count}) catch @panic("OOM")), _zbr_rt._allocator), "):\n\n", _zbr_rt._allocator)) catch @panic("OOM");
// zbr:selfhost/Checker.zbr:676
            sb.appendSlice(_zbr_rt._allocator, (phantom_sb.toOwnedSlice(_zbr_rt._allocator) catch "")) catch @panic("OOM");
        }
// zbr:selfhost/Checker.zbr:678
        if (_zebra_gt(unreachable_count, 0)) {
// zbr:selfhost/Checker.zbr:679
            sb.appendSlice(_zbr_rt._allocator, _str_concat(_str_concat(_str_concat(_str_concat(_str_concat(_str_concat(YLW, BLD, _zbr_rt._allocator), "unreachable module-level functions", _zbr_rt._allocator), RST, _zbr_rt._allocator), " (", _zbr_rt._allocator), (std.fmt.allocPrint(_zbr_rt._allocator, "{}", .{unreachable_count}) catch @panic("OOM")), _zbr_rt._allocator), "):\n\n", _zbr_rt._allocator)) catch @panic("OOM");
// zbr:selfhost/Checker.zbr:680
            sb.appendSlice(_zbr_rt._allocator, (unreach_sb.toOwnedSlice(_zbr_rt._allocator) catch "")) catch @panic("OOM");
// zbr:selfhost/Checker.zbr:681
            sb.appendSlice(_zbr_rt._allocator, "\n") catch @panic("OOM");
        }
// zbr:selfhost/Checker.zbr:683
        const total: i64 = ((dead_count + phantom_count) + unreachable_count);
// zbr:selfhost/Checker.zbr:684
        if ((total == 0)) {
// zbr:selfhost/Checker.zbr:685
            sb.appendSlice(_zbr_rt._allocator, _str_concat(_str_concat(_str_concat(BLD, "zebra check: clean", _zbr_rt._allocator), RST, _zbr_rt._allocator), "\n", _zbr_rt._allocator)) catch @panic("OOM");
        } else {
// zbr:selfhost/Checker.zbr:687
            sb.appendSlice(_zbr_rt._allocator, _str_concat(_str_concat(BLD, "zebra check: ", _zbr_rt._allocator), RST, _zbr_rt._allocator)) catch @panic("OOM");
// zbr:selfhost/Checker.zbr:688
            sb.appendSlice(_zbr_rt._allocator, _str_concat((std.fmt.allocPrint(_zbr_rt._allocator, "{}", .{dead_count}) catch @panic("OOM")), " dead arm", _zbr_rt._allocator)) catch @panic("OOM");
// zbr:selfhost/Checker.zbr:689
            if ((dead_count != 1)) {
// zbr:selfhost/Checker.zbr:690
                sb.appendSlice(_zbr_rt._allocator, "s") catch @panic("OOM");
            }
// zbr:selfhost/Checker.zbr:691
            sb.appendSlice(_zbr_rt._allocator, _str_concat(_str_concat(", ", (std.fmt.allocPrint(_zbr_rt._allocator, "{}", .{phantom_count}) catch @panic("OOM")), _zbr_rt._allocator), " phantom variant", _zbr_rt._allocator)) catch @panic("OOM");
// zbr:selfhost/Checker.zbr:692
            if ((phantom_count != 1)) {
// zbr:selfhost/Checker.zbr:693
                sb.appendSlice(_zbr_rt._allocator, "s") catch @panic("OOM");
            }
// zbr:selfhost/Checker.zbr:694
            sb.appendSlice(_zbr_rt._allocator, _str_concat(_str_concat(", ", (std.fmt.allocPrint(_zbr_rt._allocator, "{}", .{unreachable_count}) catch @panic("OOM")), _zbr_rt._allocator), " unreachable fn", _zbr_rt._allocator)) catch @panic("OOM");
// zbr:selfhost/Checker.zbr:695
            if ((unreachable_count != 1)) {
// zbr:selfhost/Checker.zbr:696
                sb.appendSlice(_zbr_rt._allocator, "s") catch @panic("OOM");
            }
// zbr:selfhost/Checker.zbr:697
            sb.appendSlice(_zbr_rt._allocator, "\n") catch @panic("OOM");
        }
// zbr:selfhost/Checker.zbr:699
        return (sb.toOwnedSlice(_zbr_rt._allocator) catch "");
    }

};
const _ttag_DeadCodeChecker: u64 = _zbr_hash("DeadCodeChecker");
const _reflect_DeadCodeChecker_name: []const u8 = "DeadCodeChecker";
const _reflect_DeadCodeChecker_fields: []const []const u8 = &.{"union_infos", "match_sites", "match_key_list", "constructed_set", "constructed_key_list", "module_fns", "module_fn_key_list", "fn_edges", "root_set", "root_key_list", "reachable_set", "exposed_names", "current_file", "current_fn_key"};
const _reflect_DeadCodeChecker_field_types: []const []const u8 = &.{"HashMap(str, UnionInfo)", "HashMap(str, List(str))", "List(str)", "HashMap(str, bool)", "List(str)", "HashMap(str, str)", "List(str)", "HashMap(str, List(str))", "HashMap(str, bool)", "List(str)", "HashMap(str, bool)", "HashMap(str, bool)", "str", "str"};

pub fn _zbr_fn_checkerDirOf(path: []const u8) []const u8 {
// zbr:selfhost/Checker.zbr:704
    if ((!(std.mem.indexOf(u8, path, "/") != null))) {
// zbr:selfhost/Checker.zbr:705
        return "";
    }
// zbr:selfhost/Checker.zbr:706
    const parts: std.ArrayList([]const u8) = blk092_4: { var _ll_4: std.ArrayList([]const u8) = std.ArrayList([]const u8).empty; var _split_iter_4 = std.mem.splitSequence(u8, path, "/"); while (_split_iter_4.next()) |_se_4| { _ll_4.append(_zbr_rt._allocator, _se_4) catch @panic("OOM"); } break :blk092_4 _ll_4; };
// zbr:selfhost/Checker.zbr:707
    if (_zebra_le(@as(i64, @intCast(parts.items.len)), 1)) {
// zbr:selfhost/Checker.zbr:708
        return "";
    }
// zbr:selfhost/Checker.zbr:709
    var out: []const u8 = _zbr_at(parts.items, 0);
// zbr:selfhost/Checker.zbr:710
    var i: i64 = 1;
// zbr:selfhost/Checker.zbr:711
    while (_zebra_lt(i, (@as(i64, @intCast(parts.items.len)) - 1))) {
// zbr:selfhost/Checker.zbr:712
        out = _str_concat(_str_concat(out, "/", _zbr_rt._allocator), _zbr_at(parts.items, i), _zbr_rt._allocator);
// zbr:selfhost/Checker.zbr:713
        i = (i + 1);
    }
// zbr:selfhost/Checker.zbr:714
    return out;
}

pub fn _zbr_fn_checkerLoadDeps(path: []const u8, visited: *std.ArrayList([]const u8), modules: *std.ArrayList(_zbr_ty_Module)) anyerror!void {
// zbr:selfhost/Checker.zbr:717
    var vi: i64 = 0;
// zbr:selfhost/Checker.zbr:718
    while (_zebra_lt(vi, @as(i64, @intCast(visited.items.len)))) {
// zbr:selfhost/Checker.zbr:719
        if (std.mem.eql(u8, _zbr_at(visited.items, vi), path)) {
// zbr:selfhost/Checker.zbr:720
            return;
        }
// zbr:selfhost/Checker.zbr:721
        vi = (vi + 1);
    }
// zbr:selfhost/Checker.zbr:722
    visited.append(_zbr_rt._allocator, _intern(path)) catch @panic("OOM");
// zbr:selfhost/Checker.zbr:723
    if ((!(blk_fex: { std.Io.Dir.cwd().access(_zbr_rt._io, path, .{}) catch break :blk_fex false; break :blk_fex true; }))) {
// zbr:selfhost/Checker.zbr:724
        return;
    }
// zbr:selfhost/Checker.zbr:726
    const src: []const u8 = (std.Io.Dir.cwd().readFileAlloc(_zbr_rt._io, path, _zbr_rt._allocator, .unlimited) catch @panic("File.read error"));
// zbr:selfhost/Checker.zbr:727
    const pm_node = (try Parser._zbr_ty_Parser.parse(src, path));
// zbr:selfhost/Checker.zbr:728
    var resolver = _zbr_ty_Resolver.init(path, src);
// zbr:selfhost/Checker.zbr:729
    (try resolver.resolve(pm_node));
// zbr:selfhost/Checker.zbr:730
    if (_zebra_gt(resolver.errorCount(), 0)) {
// zbr:selfhost/Checker.zbr:731
        { _zbr_rt._error_ctx = .{ .message = _str_concat(_str_concat(_str_concat("resolver errors in ", path, _zbr_rt._allocator), ":\n", _zbr_rt._allocator), resolver.allErrorMessages(), _zbr_rt._allocator) }; return error.ZebraError; }
    }
// zbr:selfhost/Checker.zbr:733
    if (pm_node == .module_) {
        const pm_ptr = pm_node.module_;
        const pm = pm_ptr.*;
// zbr:selfhost/Checker.zbr:735
        var di: i64 = 0;
// zbr:selfhost/Checker.zbr:736
        while (_zebra_lt(di, @as(i64, @intCast(pm.decls.items.len)))) {
// zbr:selfhost/Checker.zbr:737
            if (_zbr_at(pm.decls.items, di) == .use_) {
                const u_ptr = _zbr_at(pm.decls.items, di).use_;
                const u = u_ptr.*;
// zbr:selfhost/Checker.zbr:738
                const dep_name: []const u8 = u.path;
// zbr:selfhost/Checker.zbr:739
                const src_dir: []const u8 = _zbr_fn_checkerDirOf(path);
// zbr:selfhost/Checker.zbr:740
                var dep_path: []const u8 = _str_concat(dep_name, ".zbr", _zbr_rt._allocator);
// zbr:selfhost/Checker.zbr:741
                if (!std.mem.eql(u8, src_dir, "")) {
// zbr:selfhost/Checker.zbr:742
                    dep_path = _str_concat(_str_concat(_str_concat(src_dir, "/", _zbr_rt._allocator), dep_name, _zbr_rt._allocator), ".zbr", _zbr_rt._allocator);
                }
// zbr:selfhost/Checker.zbr:743
                if ((blk_fex: { std.Io.Dir.cwd().access(_zbr_rt._io, dep_path, .{}) catch break :blk_fex false; break :blk_fex true; })) {
// zbr:selfhost/Checker.zbr:744
                    (try _zbr_fn_checkerLoadDeps(dep_path, visited, modules));
                }
            }
// zbr:selfhost/Checker.zbr:745
            di = (di + 1);
        }
// zbr:selfhost/Checker.zbr:746
        const module: _zbr_ty_Module = (try _zbr_ty_ASTBuilder.build(pm, path));
// zbr:selfhost/Checker.zbr:747
        modules.append(_zbr_rt._allocator, module) catch @panic("OOM");
    }
}

pub fn _zbr_fn_runCheck(root_path: []const u8) anyerror!bool {
// zbr:selfhost/Checker.zbr:752
    var visited = std.ArrayList([]const u8).empty;
// zbr:selfhost/Checker.zbr:753
    var modules = std.ArrayList(_zbr_ty_Module).empty;
// zbr:selfhost/Checker.zbr:754
    (try _zbr_fn_checkerLoadDeps(root_path, &visited, &modules));
// zbr:selfhost/Checker.zbr:755
    const n_deps: i64 = (@as(i64, @intCast(modules.items.len)) - 1);
// zbr:selfhost/Checker.zbr:756
    std.debug.print("{s}\n", .{_str_concat(_str_concat(_str_concat(_str_concat("zebra check: ", root_path, _zbr_rt._allocator), " (+ ", _zbr_rt._allocator), (std.fmt.allocPrint(_zbr_rt._allocator, "{}", .{n_deps}) catch @panic("OOM")), _zbr_rt._allocator), " deps)", _zbr_rt._allocator)});
// zbr:selfhost/Checker.zbr:758
    var checker: *_zbr_ty_DeadCodeChecker = _zbr_ty_DeadCodeChecker.init();
// zbr:selfhost/Checker.zbr:761
    var mi: i64 = 0;
// zbr:selfhost/Checker.zbr:762
    while (_zebra_lt(mi, @as(i64, @intCast(modules.items.len)))) {
// zbr:selfhost/Checker.zbr:763
        checker.collectDecls(_zbr_at(modules.items, mi));
// zbr:selfhost/Checker.zbr:764
        mi = (mi + 1);
    }
// zbr:selfhost/Checker.zbr:767
    mi = 0;
// zbr:selfhost/Checker.zbr:768
    while (_zebra_lt(mi, @as(i64, @intCast(modules.items.len)))) {
// zbr:selfhost/Checker.zbr:769
        checker.walkModule(_zbr_at(modules.items, mi));
// zbr:selfhost/Checker.zbr:770
        mi = (mi + 1);
    }
// zbr:selfhost/Checker.zbr:773
    checker.computeReachability();
// zbr:selfhost/Checker.zbr:776
    const rpt: []const u8 = checker.report();
// zbr:selfhost/Checker.zbr:777
    std.debug.print("{s}", .{rpt});
// zbr:selfhost/Checker.zbr:778
    return checker.hasIssues();
}

const _ReflectStrSlice = struct { items: []const []const u8, fn count(self: @This()) i64 { return @intCast(self.items.len); } fn at(self: @This(), i: i64) []const u8 { return self.items[@intCast(i)]; } };
fn _reflect_lookup_name(tag: u64) []const u8 {
    if (tag == _ttag_UnionInfo) return _reflect_UnionInfo_name;
    if (tag == _ttag_DeadCodeChecker) return _reflect_DeadCodeChecker_name;
    return "unknown";
}
fn _reflect_lookup_fields(tag: u64) _ReflectStrSlice {
    if (tag == _ttag_UnionInfo) return .{ .items = _reflect_UnionInfo_fields };
    if (tag == _ttag_DeadCodeChecker) return .{ .items = _reflect_DeadCodeChecker_fields };
    return .{ .items = &.{} };
}
fn _reflect_lookup_field_types(tag: u64) _ReflectStrSlice {
    if (tag == _ttag_UnionInfo) return .{ .items = _reflect_UnionInfo_field_types };
    if (tag == _ttag_DeadCodeChecker) return .{ .items = _reflect_DeadCodeChecker_field_types };
    return .{ .items = &.{} };
}
var _module_vars_inited: bool = false;
pub fn _initModuleVars() void {
    if (_module_vars_inited) return;
    _module_vars_inited = true;
}
