// Generated by zebra-selfhost.
// Source: selfhost/Lexer.zbr

const std     = @import("std");
const builtin = @import("builtin");
const _zbr_rt = @import("zebra_rt.zig");
pub const panic = std.debug.FullPanic(_zbr_rt._zebra_panic);
pub const std_options = _zbr_rt.std_options;
const _zbr_val = _zbr_rt._zbr_val;
const _intern = _zbr_rt._intern;
const _zbr_at = _zbr_rt._zbr_at;
const _zebra_lt = _zbr_rt._zebra_lt;
const _zebra_le = _zbr_rt._zebra_le;
const _zebra_gt = _zbr_rt._zebra_gt;
const _zebra_ge = _zbr_rt._zebra_ge;
const _str_concat = _zbr_rt._str_concat;
const _zbr_hash = _zbr_rt._zbr_hash;
const _ZbrList = _zbr_rt._ZbrList;
const _zbr_new = _zbr_rt._zbr_new;
const _ZbrFn = _zbr_rt._ZbrFn;
const _zbr_invoke = _zbr_rt._zbr_invoke;

const _zbr_mod_Token = @import("Token.zig");
const _zbr_ty_TokenKind = _zbr_mod_Token._zbr_ty_TokenKind;
pub const CharPred = _ZbrFn(fn(u21) bool);
// zbr:selfhost/Lexer.zbr:21
pub fn _zbr_fn_isDigit(c: u21) bool {
// zbr:selfhost/Lexer.zbr:22
    switch (_zbr_val(c)) {
        '0'...'9' => {
// zbr:selfhost/Lexer.zbr:24
            return true;
        },
        else => {
// zbr:selfhost/Lexer.zbr:26
            return false;
        },
    }
}

// zbr:selfhost/Lexer.zbr:28
pub fn _zbr_fn_isDigitOrUnder(c: u21) bool {
// zbr:selfhost/Lexer.zbr:29
    return (_zbr_fn_isDigit(c) or (c == '_'));
}

// zbr:selfhost/Lexer.zbr:31
pub fn _zbr_fn_isHexDigit(c: u21) bool {
// zbr:selfhost/Lexer.zbr:32
    switch (_zbr_val(c)) {
        '0'...'9' => {
// zbr:selfhost/Lexer.zbr:34
            return true;
        },
        'a'...'f' => {
// zbr:selfhost/Lexer.zbr:36
            return true;
        },
        'A'...'F' => {
// zbr:selfhost/Lexer.zbr:38
            return true;
        },
        else => {
// zbr:selfhost/Lexer.zbr:40
            return false;
        },
    }
}

// zbr:selfhost/Lexer.zbr:42
pub fn _zbr_fn_isAlpha(c: u21) bool {
// zbr:selfhost/Lexer.zbr:43
    switch (_zbr_val(c)) {
        'a'...'z' => {
// zbr:selfhost/Lexer.zbr:45
            return true;
        },
        'A'...'Z' => {
// zbr:selfhost/Lexer.zbr:47
            return true;
        },
        else => {
// zbr:selfhost/Lexer.zbr:49
            return false;
        },
    }
}

// zbr:selfhost/Lexer.zbr:51
pub fn _zbr_fn_isIdentContinue(c: u21) bool {
// zbr:selfhost/Lexer.zbr:52
    return ((_zbr_fn_isAlpha(c) or _zbr_fn_isDigit(c)) or (c == '_'));
}

pub const _zbr_ty_LineKind = union(enum) {
    empty,
    whitespace_only,
    comment_only,
    block_comment_only,
    has_content,
};

pub const _zbr_ty_Lexer = struct {
    _type_tag: u64 = _ttag_Lexer,
    src: []const u8 = undefined,
    pos: i64 = undefined,
    line: i64 = undefined,
    lineStart: i64 = undefined,
    indentDepth: i64 = undefined,
    blockDepth: i64 = undefined,
    parenDepth: i64 = undefined,
    out: _ZbrList(*_zbr_mod_Token._zbr_ty_Token) = undefined,
    inLambdaParams: bool = undefined,
    lambdaParamDepth: i64 = undefined,
    afterLambdaParams: bool = undefined,
    lambdaStack: _ZbrList(i64) = undefined,
    afterEnsureEol: bool = undefined,
    ensureBaseDepth: i64 = undefined,
    pub fn init() *_zbr_ty_Lexer {
        const _self = _zbr_rt._allocator.create(_zbr_ty_Lexer) catch @panic("OOM");
        _self._type_tag = _zbr_hash("Lexer");
// zbr:selfhost/Lexer.zbr:82
            _self.src = _intern("");
// zbr:selfhost/Lexer.zbr:83
            _self.pos = 0;
// zbr:selfhost/Lexer.zbr:84
            _self.line = 1;
// zbr:selfhost/Lexer.zbr:85
            _self.lineStart = 0;
// zbr:selfhost/Lexer.zbr:86
            _self.indentDepth = 0;
// zbr:selfhost/Lexer.zbr:87
            _self.blockDepth = 0;
// zbr:selfhost/Lexer.zbr:88
            _self.parenDepth = 0;
// zbr:selfhost/Lexer.zbr:89
            _self.out = _zbr_new(_ZbrList(*_zbr_mod_Token._zbr_ty_Token));
// zbr:selfhost/Lexer.zbr:90
            _self.inLambdaParams = false;
// zbr:selfhost/Lexer.zbr:91
            _self.lambdaParamDepth = 0;
// zbr:selfhost/Lexer.zbr:92
            _self.afterLambdaParams = false;
// zbr:selfhost/Lexer.zbr:93
            _self.lambdaStack = _zbr_new(_ZbrList(i64));
// zbr:selfhost/Lexer.zbr:94
            _self.afterEnsureEol = false;
// zbr:selfhost/Lexer.zbr:95
            _self.ensureBaseDepth = 0;
        return _self;
    }

    // zbr:selfhost/Lexer.zbr:97
    pub fn tokenize(source: []const u8) anyerror!_ZbrList(*_zbr_mod_Token._zbr_ty_Token) {
// zbr:selfhost/Lexer.zbr:98
        var lex = _zbr_ty_Lexer.init();
// zbr:selfhost/Lexer.zbr:99
        lex.src = _intern(source);
// zbr:selfhost/Lexer.zbr:100
        (try lex.run());
// zbr:selfhost/Lexer.zbr:101
        return lex.out;
    }

    // zbr:selfhost/Lexer.zbr:106
    pub fn lexErr(self: *_zbr_ty_Lexer, b: u21, ln: i64, cl: i64) []const u8 {
        _ = self;
// zbr:selfhost/Lexer.zbr:107
        if ((b == '\r')) {
// zbr:selfhost/Lexer.zbr:108
            return _str_concat(_str_concat(_str_concat((std.fmt.allocPrint(_zbr_rt._allocator, "{}", .{ln}) catch @panic("OOM")), ":", _zbr_rt._allocator), (std.fmt.allocPrint(_zbr_rt._allocator, "{}", .{cl}) catch @panic("OOM")), _zbr_rt._allocator), ": unexpected '\\r' (CRLF line endings — convert to LF)", _zbr_rt._allocator);
        }
// zbr:selfhost/Lexer.zbr:120
        if (_zebra_gt(b, '\x7F')) {
// zbr:selfhost/Lexer.zbr:121
            return _str_concat(_str_concat(_str_concat((std.fmt.allocPrint(_zbr_rt._allocator, "{}", .{ln}) catch @panic("OOM")), ":", _zbr_rt._allocator), (std.fmt.allocPrint(_zbr_rt._allocator, "{}", .{cl}) catch @panic("OOM")), _zbr_rt._allocator), ": unexpected non-ASCII byte — identifiers and operators must be ASCII (non-ASCII text is fine inside a string literal or a comment)", _zbr_rt._allocator);
        }
// zbr:selfhost/Lexer.zbr:122
        return _str_concat(_str_concat(_str_concat(_str_concat(_str_concat((std.fmt.allocPrint(_zbr_rt._allocator, "{}", .{ln}) catch @panic("OOM")), ":", _zbr_rt._allocator), (std.fmt.allocPrint(_zbr_rt._allocator, "{}", .{cl}) catch @panic("OOM")), _zbr_rt._allocator), ": unexpected character '", _zbr_rt._allocator), (blk: { var _cpbuf: [4]u8 = undefined; const _cplen = std.unicode.utf8Encode(@intCast(b), &_cpbuf) catch 1; break :blk _zbr_rt._allocator.dupe(u8, _cpbuf[0.._cplen]) catch @panic("OOM"); }), _zbr_rt._allocator), "'", _zbr_rt._allocator);
    }

    // zbr:selfhost/Lexer.zbr:126
    pub fn col(self: *const _zbr_ty_Lexer) i64 {
// zbr:selfhost/Lexer.zbr:127
        return ((self.pos - self.lineStart) + 1);
    }

    // zbr:selfhost/Lexer.zbr:129
    pub fn peek(self: *const _zbr_ty_Lexer) u21 {
// zbr:selfhost/Lexer.zbr:130
        if (_zebra_lt(self.pos, @as(i64, @intCast(self.src.len)))) {
// zbr:selfhost/Lexer.zbr:131
            return _zbr_at(self.src, self.pos);
        }
// zbr:selfhost/Lexer.zbr:132
        return '\x00';
    }

    // zbr:selfhost/Lexer.zbr:134
    pub fn peek1(self: *const _zbr_ty_Lexer) u21 {
// zbr:selfhost/Lexer.zbr:135
        if (_zebra_lt((self.pos + 1), @as(i64, @intCast(self.src.len)))) {
// zbr:selfhost/Lexer.zbr:136
            return _zbr_at(self.src, (self.pos + 1));
        }
// zbr:selfhost/Lexer.zbr:137
        return '\x00';
    }

    // zbr:selfhost/Lexer.zbr:139
    pub fn peekAt(self: *const _zbr_ty_Lexer, offset: i64) u21 {
        if (!(_zebra_ge(offset, 0))) std.debug.panic("require failed in 'peekAt'\n", .{});
// zbr:selfhost/Lexer.zbr:142
        if (_zebra_lt((self.pos + offset), @as(i64, @intCast(self.src.len)))) {
// zbr:selfhost/Lexer.zbr:143
            return _zbr_at(self.src, (self.pos + offset));
        }
// zbr:selfhost/Lexer.zbr:144
        return '\x00';
    }

    // zbr:selfhost/Lexer.zbr:146
    pub fn advanceNewline(self: *_zbr_ty_Lexer) void {
// zbr:selfhost/Lexer.zbr:147
        self.pos = (self.pos + 1);
// zbr:selfhost/Lexer.zbr:148
        self.line = (self.line + 1);
// zbr:selfhost/Lexer.zbr:149
        self.lineStart = self.pos;
    }

    // zbr:selfhost/Lexer.zbr:151
    pub fn emit(self: *_zbr_ty_Lexer, kind: _zbr_ty_TokenKind, text: []const u8, ln: i64, cl: i64) void {
// zbr:selfhost/Lexer.zbr:152
        self.out.append(_zbr_rt._allocator, _zbr_mod_Token._zbr_ty_Token.init(kind, text, ln, cl)) catch @panic("OOM");
    }

    // zbr:selfhost/Lexer.zbr:156
    pub fn scanWhile(self: *_zbr_ty_Lexer, pred: CharPred) void {
// zbr:selfhost/Lexer.zbr:157
        while ((_zebra_lt(self.pos, @as(i64, @intCast(self.src.len))) and _zbr_invoke(&pred, .{_zbr_at(self.src, self.pos)}))) {
// zbr:selfhost/Lexer.zbr:158
            self.pos = (self.pos + 1);
        }
    }

    // zbr:selfhost/Lexer.zbr:162
    pub fn classifyLine(self: *_zbr_ty_Lexer) _zbr_ty_LineKind {
// zbr:selfhost/Lexer.zbr:163
        var i: i64 = self.pos;
// zbr:selfhost/Lexer.zbr:164
        if ((_zebra_ge(i, @as(i64, @intCast(self.src.len))) or (_zbr_at(self.src, i) == '\n'))) {
// zbr:selfhost/Lexer.zbr:165
            return _zbr_ty_LineKind{ .empty = {} };
        }
// zbr:selfhost/Lexer.zbr:166
        var hasWs: bool = false;
// zbr:selfhost/Lexer.zbr:167
        while ((_zebra_lt(i, @as(i64, @intCast(self.src.len))) and ((_zbr_at(self.src, i) == ' ') or (_zbr_at(self.src, i) == '\t')))) {
// zbr:selfhost/Lexer.zbr:168
            hasWs = true;
// zbr:selfhost/Lexer.zbr:169
            i = (i + 1);
        }
// zbr:selfhost/Lexer.zbr:170
        if ((_zebra_ge(i, @as(i64, @intCast(self.src.len))) or (_zbr_at(self.src, i) == '\n'))) {
// zbr:selfhost/Lexer.zbr:171
            if (hasWs) {
// zbr:selfhost/Lexer.zbr:172
                return _zbr_ty_LineKind{ .whitespace_only = {} };
            }
// zbr:selfhost/Lexer.zbr:173
            return _zbr_ty_LineKind{ .empty = {} };
        }
// zbr:selfhost/Lexer.zbr:174
        if ((_zbr_at(self.src, i) == '#')) {
// zbr:selfhost/Lexer.zbr:175
            return _zbr_ty_LineKind{ .comment_only = {} };
        }
// zbr:selfhost/Lexer.zbr:177
        if ((((_zbr_at(self.src, i) == '/') and _zebra_lt((i + 1), @as(i64, @intCast(self.src.len)))) and (_zbr_at(self.src, (i + 1)) == '#'))) {
// zbr:selfhost/Lexer.zbr:178
            var depth: i64 = 0;
// zbr:selfhost/Lexer.zbr:179
            var j: i64 = i;
// zbr:selfhost/Lexer.zbr:180
            while ((_zebra_lt(j, @as(i64, @intCast(self.src.len))) and (_zbr_at(self.src, j) != '\n'))) {
// zbr:selfhost/Lexer.zbr:181
                if ((((_zbr_at(self.src, j) == '/') and _zebra_lt((j + 1), @as(i64, @intCast(self.src.len)))) and (_zbr_at(self.src, (j + 1)) == '#'))) {
// zbr:selfhost/Lexer.zbr:182
                    depth = (depth + 1);
// zbr:selfhost/Lexer.zbr:183
                    j = (j + 2);
                } else {
// zbr:selfhost/Lexer.zbr:184
                    if ((((_zbr_at(self.src, j) == '#') and _zebra_lt((j + 1), @as(i64, @intCast(self.src.len)))) and (_zbr_at(self.src, (j + 1)) == '/'))) {
// zbr:selfhost/Lexer.zbr:185
                        if (_zebra_gt(depth, 0)) {
// zbr:selfhost/Lexer.zbr:186
                            depth = (depth - 1);
                        }
// zbr:selfhost/Lexer.zbr:187
                        j = (j + 2);
// zbr:selfhost/Lexer.zbr:188
                        if ((depth == 0)) {
// zbr:selfhost/Lexer.zbr:190
                            while ((_zebra_lt(j, @as(i64, @intCast(self.src.len))) and ((_zbr_at(self.src, j) == ' ') or (_zbr_at(self.src, j) == '\t')))) {
// zbr:selfhost/Lexer.zbr:191
                                j = (j + 1);
                            }
// zbr:selfhost/Lexer.zbr:192
                            if (((_zebra_ge(j, @as(i64, @intCast(self.src.len))) or (_zbr_at(self.src, j) == '\n')) or (_zbr_at(self.src, j) == '#'))) {
// zbr:selfhost/Lexer.zbr:193
                                return _zbr_ty_LineKind{ .block_comment_only = {} };
                            }
// zbr:selfhost/Lexer.zbr:194
                            return _zbr_ty_LineKind{ .has_content = {} };
                        }
                    } else {
// zbr:selfhost/Lexer.zbr:196
                        j = (j + 1);
                    }
                }
            }
// zbr:selfhost/Lexer.zbr:198
            return _zbr_ty_LineKind{ .block_comment_only = {} };
        }
// zbr:selfhost/Lexer.zbr:199
        return _zbr_ty_LineKind{ .has_content = {} };
    }

    // zbr:selfhost/Lexer.zbr:203
    pub fn processIndentation(self: *_zbr_ty_Lexer) anyerror!void {
// zbr:selfhost/Lexer.zbr:204
        const ln: i64 = self.line;
// zbr:selfhost/Lexer.zbr:205
        var tabs: i64 = 0;
// zbr:selfhost/Lexer.zbr:206
        var spaces: i64 = 0;
// zbr:selfhost/Lexer.zbr:207
        while (_zebra_lt(self.pos, @as(i64, @intCast(self.src.len)))) {
// zbr:selfhost/Lexer.zbr:208
            const c: u8 = _zbr_at(self.src, self.pos);
// zbr:selfhost/Lexer.zbr:209
            if ((c == '\t')) {
// zbr:selfhost/Lexer.zbr:210
                tabs = (tabs + 1);
// zbr:selfhost/Lexer.zbr:211
                self.pos = (self.pos + 1);
            } else {
// zbr:selfhost/Lexer.zbr:212
                if ((c == ' ')) {
// zbr:selfhost/Lexer.zbr:213
                    spaces = (spaces + 1);
// zbr:selfhost/Lexer.zbr:214
                    self.pos = (self.pos + 1);
                } else {
                    break;
                }
            }
        }
// zbr:selfhost/Lexer.zbr:220
        if ((_zebra_gt(tabs, 0) and _zebra_gt(spaces, 0))) {
// zbr:selfhost/Lexer.zbr:221
            { _zbr_rt._error_ctx = .{ .message = _str_concat((std.fmt.allocPrint(_zbr_rt._allocator, "{}", .{ln}) catch @panic("OOM")), ":1: error: mixed tabs and spaces in the indentation of this line -- Zebra indents with 4 spaces per level", _zbr_rt._allocator) }; return error.ZebraError; }
        }
// zbr:selfhost/Lexer.zbr:222
        var level: i64 = 0;
// zbr:selfhost/Lexer.zbr:223
        if (_zebra_gt(spaces, 0)) {
// zbr:selfhost/Lexer.zbr:224
            if ((@rem(spaces, 4) != 0)) {
// zbr:selfhost/Lexer.zbr:225
                { _zbr_rt._error_ctx = .{ .message = _str_concat(_str_concat(_str_concat(_str_concat(_str_concat((std.fmt.allocPrint(_zbr_rt._allocator, "{}", .{ln}) catch @panic("OOM")), ":", _zbr_rt._allocator), (std.fmt.allocPrint(_zbr_rt._allocator, "{}", .{(spaces + 1)}) catch @panic("OOM")), _zbr_rt._allocator), ": error: indentation is ", _zbr_rt._allocator), (std.fmt.allocPrint(_zbr_rt._allocator, "{}", .{spaces}) catch @panic("OOM")), _zbr_rt._allocator), " space(s); Zebra indents by multiples of 4", _zbr_rt._allocator) }; return error.ZebraError; }
            }
// zbr:selfhost/Lexer.zbr:226
            level = @divTrunc(spaces, 4);
        } else {
// zbr:selfhost/Lexer.zbr:228
            level = tabs;
        }
// zbr:selfhost/Lexer.zbr:229
        const oldDepth: i64 = self.indentDepth;
// zbr:selfhost/Lexer.zbr:230
        while (_zebra_gt(level, self.indentDepth)) {
// zbr:selfhost/Lexer.zbr:231
            self.emit(_zbr_ty_TokenKind{ .indent = {} }, "", ln, 1);
// zbr:selfhost/Lexer.zbr:232
            self.indentDepth = (self.indentDepth + 1);
        }
// zbr:selfhost/Lexer.zbr:233
        while (_zebra_lt(level, self.indentDepth)) {
// zbr:selfhost/Lexer.zbr:234
            self.emit(_zbr_ty_TokenKind{ .dedent = {} }, "", ln, 1);
// zbr:selfhost/Lexer.zbr:235
            self.indentDepth = (self.indentDepth - 1);
        }
// zbr:selfhost/Lexer.zbr:236
        if (self.afterEnsureEol) {
// zbr:selfhost/Lexer.zbr:237
            if (_zebra_gt(level, oldDepth)) {
// zbr:selfhost/Lexer.zbr:238
                self.ensureBaseDepth = level;
            }
// zbr:selfhost/Lexer.zbr:239
            self.afterEnsureEol = false;
        }
// zbr:selfhost/Lexer.zbr:240
        if ((_zebra_gt(self.ensureBaseDepth, 0) and _zebra_lt(level, self.ensureBaseDepth))) {
// zbr:selfhost/Lexer.zbr:241
            self.ensureBaseDepth = 0;
        }
// zbr:selfhost/Lexer.zbr:242
        while ((_zebra_gt(@as(i64, @intCast(self.lambdaStack.items.len)), 0) and _zebra_le(self.indentDepth, _zbr_at(self.lambdaStack.items, (@as(i64, @intCast(self.lambdaStack.items.len)) - 1))))) {
// zbr:selfhost/Lexer.zbr:243
            _ = self.lambdaStack.orderedRemove(@intCast((@as(i64, @intCast(self.lambdaStack.items.len)) - 1)));
        }
    }

    // zbr:selfhost/Lexer.zbr:247
    pub fn scanBlockComment(self: *_zbr_ty_Lexer) anyerror!void {
// zbr:selfhost/Lexer.zbr:248
        self.pos = (self.pos + 2);
// zbr:selfhost/Lexer.zbr:249
        self.blockDepth = (self.blockDepth + 1);
// zbr:selfhost/Lexer.zbr:250
        while ((_zebra_lt(self.pos, @as(i64, @intCast(self.src.len))) and _zebra_gt(self.blockDepth, 0))) {
// zbr:selfhost/Lexer.zbr:251
            if ((((_zbr_at(self.src, self.pos) == '/') and _zebra_lt((self.pos + 1), @as(i64, @intCast(self.src.len)))) and (_zbr_at(self.src, (self.pos + 1)) == '#'))) {
// zbr:selfhost/Lexer.zbr:252
                self.pos = (self.pos + 2);
// zbr:selfhost/Lexer.zbr:253
                self.blockDepth = (self.blockDepth + 1);
            } else {
// zbr:selfhost/Lexer.zbr:254
                if ((((_zbr_at(self.src, self.pos) == '#') and _zebra_lt((self.pos + 1), @as(i64, @intCast(self.src.len)))) and (_zbr_at(self.src, (self.pos + 1)) == '/'))) {
// zbr:selfhost/Lexer.zbr:255
                    self.pos = (self.pos + 2);
// zbr:selfhost/Lexer.zbr:256
                    self.blockDepth = (self.blockDepth - 1);
                } else {
// zbr:selfhost/Lexer.zbr:257
                    if ((_zbr_at(self.src, self.pos) == '\n')) {
// zbr:selfhost/Lexer.zbr:258
                        self.advanceNewline();
                    } else {
// zbr:selfhost/Lexer.zbr:260
                        self.pos = (self.pos + 1);
                    }
                }
            }
        }
// zbr:selfhost/Lexer.zbr:261
        if (_zebra_gt(self.blockDepth, 0)) {
// zbr:selfhost/Lexer.zbr:262
            { _zbr_rt._error_ctx = .{ .message = _str_concat((std.fmt.allocPrint(_zbr_rt._allocator, "{}", .{self.line}) catch @panic("OOM")), ":1: error: block comment is never closed", _zbr_rt._allocator) }; return error.ZebraError; }
        }
    }

    // zbr:selfhost/Lexer.zbr:266
    pub fn scanAt(self: *_zbr_ty_Lexer, ln: i64, cl: i64) anyerror!void {
// zbr:selfhost/Lexer.zbr:267
        const c1: u21 = self.peek1();
// zbr:selfhost/Lexer.zbr:268
        if ((c1 == '[')) {
// zbr:selfhost/Lexer.zbr:269
            self.pos = (self.pos + 2);
// zbr:selfhost/Lexer.zbr:270
            self.emit(_zbr_ty_TokenKind{ .at_lbracket = {} }, "@[", ln, cl);
// zbr:selfhost/Lexer.zbr:271
            return;
        }
// zbr:selfhost/Lexer.zbr:272
        if ((_zbr_fn_isAlpha(c1) or (c1 == '_'))) {
// zbr:selfhost/Lexer.zbr:273
            self.pos = (self.pos + 1);
// zbr:selfhost/Lexer.zbr:274
            const start: i64 = self.pos;
// zbr:selfhost/Lexer.zbr:275
            self.scanWhile(.from(_zbr_fn_isIdentContinue));
// zbr:selfhost/Lexer.zbr:276
            self.emit(_zbr_ty_TokenKind{ .at_id = {} }, self.src[@as(usize, @intCast((start - 1)))..@as(usize, @intCast(self.pos))], ln, cl);
// zbr:selfhost/Lexer.zbr:277
            return;
        }
// zbr:selfhost/Lexer.zbr:278
        { _zbr_rt._error_ctx = .{ .message = self.lexErr(c1, self.line, self.col()) }; return error.ZebraError; }
    }

    // zbr:selfhost/Lexer.zbr:282
    pub fn scanIdentOrKeyword(self: *_zbr_ty_Lexer, ln: i64, cl: i64) anyerror!void {
// zbr:selfhost/Lexer.zbr:283
        const start: i64 = self.pos;
// zbr:selfhost/Lexer.zbr:284
        self.scanWhile(.from(_zbr_fn_isIdentContinue));
// zbr:selfhost/Lexer.zbr:285
        const word: []const u8 = self.src[@as(usize, @intCast(start))..@as(usize, @intCast(self.pos))];
// zbr:selfhost/Lexer.zbr:288
        if (((@as(i64, @intCast(word.len)) == 1) and (_zbr_at(word, 0) == 'c'))) {
// zbr:selfhost/Lexer.zbr:289
            const q: u21 = self.peek();
// zbr:selfhost/Lexer.zbr:290
            if (((q == '\'') or (q == '"'))) {
// zbr:selfhost/Lexer.zbr:291
                (try self.scanCharLiteral(q, start, ln, cl));
// zbr:selfhost/Lexer.zbr:292
                return;
            }
        }
// zbr:selfhost/Lexer.zbr:295
        if (((@as(i64, @intCast(word.len)) == 1) and (_zbr_at(word, 0) == 'r'))) {
// zbr:selfhost/Lexer.zbr:296
            const q: u21 = self.peek();
// zbr:selfhost/Lexer.zbr:297
            if (((q == '\'') or (q == '"'))) {
// zbr:selfhost/Lexer.zbr:298
                var kind = _zbr_ty_TokenKind{ .string_raw_single = {} };
// zbr:selfhost/Lexer.zbr:299
                if ((q == '"')) {
// zbr:selfhost/Lexer.zbr:300
                    kind = _zbr_ty_TokenKind{ .string_raw_double = {} };
                }
// zbr:selfhost/Lexer.zbr:301
                (try self.scanSimpleString(q, start, kind, ln, cl, true));
// zbr:selfhost/Lexer.zbr:302
                return;
            }
        }
// zbr:selfhost/Lexer.zbr:305
        if ((((@as(i64, @intCast(word.len)) == 2) and (_zbr_at(word, 0) == 'n')) and (_zbr_at(word, 1) == 's'))) {
// zbr:selfhost/Lexer.zbr:306
            const q: u21 = self.peek();
// zbr:selfhost/Lexer.zbr:307
            if (((q == '\'') or (q == '"'))) {
// zbr:selfhost/Lexer.zbr:308
                var kind = _zbr_ty_TokenKind{ .string_nosub_single = {} };
// zbr:selfhost/Lexer.zbr:309
                if ((q == '"')) {
// zbr:selfhost/Lexer.zbr:310
                    kind = _zbr_ty_TokenKind{ .string_nosub_double = {} };
                }
// zbr:selfhost/Lexer.zbr:311
                (try self.scanSimpleString(q, start, kind, ln, cl, false));
// zbr:selfhost/Lexer.zbr:312
                return;
            }
        }
// zbr:selfhost/Lexer.zbr:315
        if (std.mem.eql(u8, word, "zig")) {
// zbr:selfhost/Lexer.zbr:316
            const q: u21 = self.peek();
// zbr:selfhost/Lexer.zbr:317
            if (((q == '\'') or (q == '"'))) {
// zbr:selfhost/Lexer.zbr:318
                var kind = _zbr_ty_TokenKind{ .zig_single = {} };
// zbr:selfhost/Lexer.zbr:319
                if ((q == '"')) {
// zbr:selfhost/Lexer.zbr:320
                    kind = _zbr_ty_TokenKind{ .zig_double = {} };
                }
// zbr:selfhost/Lexer.zbr:321
                (try self.scanSimpleString(q, start, kind, ln, cl, false));
// zbr:selfhost/Lexer.zbr:322
                return;
            }
        }
// zbr:selfhost/Lexer.zbr:325
        if (((((_zebra_gt(@as(i64, @intCast(word.len)), 3) and (_zbr_at(word, 0) == 'i')) and (_zbr_at(word, 1) == 'n')) and (_zbr_at(word, 2) == 't')) and _zbr_fn_isDigit(_zbr_at(word, 3)))) {
// zbr:selfhost/Lexer.zbr:326
            self.emit(_zbr_ty_TokenKind{ .int_size = {} }, word, ln, cl);
// zbr:selfhost/Lexer.zbr:327
            return;
        }
// zbr:selfhost/Lexer.zbr:328
        if ((((((_zebra_gt(@as(i64, @intCast(word.len)), 4) and (_zbr_at(word, 0) == 'u')) and (_zbr_at(word, 1) == 'i')) and (_zbr_at(word, 2) == 'n')) and (_zbr_at(word, 3) == 't')) and _zbr_fn_isDigit(_zbr_at(word, 4)))) {
// zbr:selfhost/Lexer.zbr:329
            self.emit(_zbr_ty_TokenKind{ .uint_size = {} }, word, ln, cl);
// zbr:selfhost/Lexer.zbr:330
            return;
        }
// zbr:selfhost/Lexer.zbr:331
        if (((((((_zebra_gt(@as(i64, @intCast(word.len)), 5) and (_zbr_at(word, 0) == 'f')) and (_zbr_at(word, 1) == 'l')) and (_zbr_at(word, 2) == 'o')) and (_zbr_at(word, 3) == 'a')) and (_zbr_at(word, 4) == 't')) and _zbr_fn_isDigit(_zbr_at(word, 5)))) {
// zbr:selfhost/Lexer.zbr:332
            self.emit(_zbr_ty_TokenKind{ .float_size = {} }, word, ln, cl);
// zbr:selfhost/Lexer.zbr:333
            return;
        }
// zbr:selfhost/Lexer.zbr:336
        var kw = _zbr_mod_Token._zbr_ty_Keywords.lookup(word);
// zbr:selfhost/Lexer.zbr:340
        var prevDot: bool = false;
// zbr:selfhost/Lexer.zbr:341
        if (_zebra_gt(@as(i64, @intCast(self.out.items.len)), 0)) {
// zbr:selfhost/Lexer.zbr:342
            switch (_zbr_val(_zbr_at(self.out.items, (@as(i64, @intCast(self.out.items.len)) - 1)).kind)) {
                .dot => {
// zbr:selfhost/Lexer.zbr:344
                    prevDot = true;
                },
                else => {
                    // pass
                },
            }
        }
// zbr:selfhost/Lexer.zbr:347
        if ((_zebra_gt(self.ensureBaseDepth, 0) and (!prevDot))) {
// zbr:selfhost/Lexer.zbr:348
            if (std.mem.eql(u8, word, "old")) {
// zbr:selfhost/Lexer.zbr:349
                kw = _zbr_ty_TokenKind{ .kw_old = {} };
            }
// zbr:selfhost/Lexer.zbr:350
            if (std.mem.eql(u8, word, "result")) {
// zbr:selfhost/Lexer.zbr:351
                kw = _zbr_ty_TokenKind{ .kw_result = {} };
            }
        }
// zbr:selfhost/Lexer.zbr:353
        if (kw) |resolvedKw| {
// zbr:selfhost/Lexer.zbr:354
            self.emit(resolvedKw, word, ln, cl);
// zbr:selfhost/Lexer.zbr:355
            switch (_zbr_val(resolvedKw)) {
                .kw_ensure => {
// zbr:selfhost/Lexer.zbr:357
                    self.afterEnsureEol = true;
                },
                else => {
                    // pass
                },
            }
// zbr:selfhost/Lexer.zbr:360
            return;
        }
// zbr:selfhost/Lexer.zbr:363
        if ((self.peek() == '(')) {
// zbr:selfhost/Lexer.zbr:364
            self.pos = (self.pos + 1);
// zbr:selfhost/Lexer.zbr:365
            self.parenDepth = (self.parenDepth + 1);
// zbr:selfhost/Lexer.zbr:366
            self.emit(_zbr_ty_TokenKind{ .open_call = {} }, word, ln, cl);
// zbr:selfhost/Lexer.zbr:367
            return;
        }
// zbr:selfhost/Lexer.zbr:369
        self.emit(_zbr_ty_TokenKind{ .id = {} }, word, ln, cl);
    }

    // zbr:selfhost/Lexer.zbr:373
    pub fn scanCharLiteral(self: *_zbr_ty_Lexer, q: u21, start: i64, ln: i64, cl: i64) anyerror!void {
// zbr:selfhost/Lexer.zbr:374
        self.pos = (self.pos + 1);
// zbr:selfhost/Lexer.zbr:375
        while (_zebra_lt(self.pos, @as(i64, @intCast(self.src.len)))) {
// zbr:selfhost/Lexer.zbr:376
            const c: u8 = _zbr_at(self.src, self.pos);
// zbr:selfhost/Lexer.zbr:377
            if ((c == '\\')) {
// zbr:selfhost/Lexer.zbr:378
                self.pos = (self.pos + 2);
                continue;
            }
// zbr:selfhost/Lexer.zbr:380
            if ((c == q)) {
// zbr:selfhost/Lexer.zbr:381
                self.pos = (self.pos + 1);
                break;
            }
// zbr:selfhost/Lexer.zbr:383
            if ((c == '\n')) {
// zbr:selfhost/Lexer.zbr:384
                { _zbr_rt._error_ctx = .{ .message = _str_concat((std.fmt.allocPrint(_zbr_rt._allocator, "{}", .{self.line}) catch @panic("OOM")), ":1: error: char literal is never closed on this line", _zbr_rt._allocator) }; return error.ZebraError; }
            }
// zbr:selfhost/Lexer.zbr:385
            self.pos = (self.pos + 1);
        }
// zbr:selfhost/Lexer.zbr:386
        var kind = _zbr_ty_TokenKind{ .char_lit_single = {} };
// zbr:selfhost/Lexer.zbr:387
        if ((q == '"')) {
// zbr:selfhost/Lexer.zbr:388
            kind = _zbr_ty_TokenKind{ .char_lit_double = {} };
        }
// zbr:selfhost/Lexer.zbr:389
        self.emit(kind, self.src[@as(usize, @intCast(start))..@as(usize, @intCast(self.pos))], ln, cl);
    }

    // zbr:selfhost/Lexer.zbr:396
    pub fn scanSingleQuote(self: *_zbr_ty_Lexer, ln: i64, cl: i64) anyerror!void {
// zbr:selfhost/Lexer.zbr:397
        const p1: u21 = self.peekAt(1);
// zbr:selfhost/Lexer.zbr:398
        if ((p1 == '\\')) {
// zbr:selfhost/Lexer.zbr:399
            if ((self.peekAt(3) == '\'')) {
// zbr:selfhost/Lexer.zbr:400
                (try self.scanCharLiteral('\'', self.pos, ln, cl));
// zbr:selfhost/Lexer.zbr:401
                return;
            }
        } else {
// zbr:selfhost/Lexer.zbr:402
            if ((((p1 != '\'') and (p1 != '\x00')) and (p1 != '\n'))) {
// zbr:selfhost/Lexer.zbr:403
                if ((self.peekAt(2) == '\'')) {
// zbr:selfhost/Lexer.zbr:404
                    (try self.scanCharLiteral('\'', self.pos, ln, cl));
// zbr:selfhost/Lexer.zbr:405
                    return;
                }
            }
        }
// zbr:selfhost/Lexer.zbr:406
        (try self.scanString('\'', ln, cl));
    }

    // zbr:selfhost/Lexer.zbr:413
    pub fn scanSimpleString(self: *_zbr_ty_Lexer, q: u21, start: i64, kind: _zbr_ty_TokenKind, ln: i64, cl: i64, raw: bool) anyerror!void {
// zbr:selfhost/Lexer.zbr:414
        self.pos = (self.pos + 1);
// zbr:selfhost/Lexer.zbr:415
        while (_zebra_lt(self.pos, @as(i64, @intCast(self.src.len)))) {
// zbr:selfhost/Lexer.zbr:416
            const c: u8 = _zbr_at(self.src, self.pos);
// zbr:selfhost/Lexer.zbr:417
            if (((c == '\\') and (!raw))) {
// zbr:selfhost/Lexer.zbr:418
                self.pos = (self.pos + 2);
                continue;
            }
// zbr:selfhost/Lexer.zbr:420
            if ((c == q)) {
// zbr:selfhost/Lexer.zbr:421
                self.pos = (self.pos + 1);
                break;
            }
// zbr:selfhost/Lexer.zbr:423
            if ((c == '\n')) {
// zbr:selfhost/Lexer.zbr:424
                { _zbr_rt._error_ctx = .{ .message = _str_concat((std.fmt.allocPrint(_zbr_rt._allocator, "{}", .{self.line}) catch @panic("OOM")), ":1: error: string literal is never closed on this line", _zbr_rt._allocator) }; return error.ZebraError; }
            }
// zbr:selfhost/Lexer.zbr:425
            self.pos = (self.pos + 1);
        }
// zbr:selfhost/Lexer.zbr:426
        self.emit(kind, self.src[@as(usize, @intCast(start))..@as(usize, @intCast(self.pos))], ln, cl);
    }

    // zbr:selfhost/Lexer.zbr:430
    pub fn scanString(self: *_zbr_ty_Lexer, q: u21, ln: i64, cl: i64) anyerror!void {
// zbr:selfhost/Lexer.zbr:431
        if ((((q == '"') and (self.peek1() == '"')) and (self.peekAt(2) == '"'))) {
// zbr:selfhost/Lexer.zbr:432
            (try self.scanDocString(ln, cl));
// zbr:selfhost/Lexer.zbr:433
            return;
        }
// zbr:selfhost/Lexer.zbr:435
        const openPos: i64 = self.pos;
// zbr:selfhost/Lexer.zbr:436
        self.pos = (self.pos + 1);
// zbr:selfhost/Lexer.zbr:438
        var hasInterp: bool = false;
// zbr:selfhost/Lexer.zbr:439
        var segStart: i64 = self.pos;
// zbr:selfhost/Lexer.zbr:440
        var segLn: i64 = self.line;
// zbr:selfhost/Lexer.zbr:442
        while (_zebra_lt(self.pos, @as(i64, @intCast(self.src.len)))) {
// zbr:selfhost/Lexer.zbr:443
            const c: u8 = _zbr_at(self.src, self.pos);
// zbr:selfhost/Lexer.zbr:445
            if (((c == '$') and (self.peek1() == '{'))) {
// zbr:selfhost/Lexer.zbr:446
                const segText: []const u8 = self.src[@as(usize, @intCast(segStart))..@as(usize, @intCast(self.pos))];
// zbr:selfhost/Lexer.zbr:447
                if ((!hasInterp)) {
// zbr:selfhost/Lexer.zbr:448
                    var kind = _zbr_ty_TokenKind{ .string_start_single = {} };
// zbr:selfhost/Lexer.zbr:449
                    if ((q == '"')) {
// zbr:selfhost/Lexer.zbr:450
                        kind = _zbr_ty_TokenKind{ .string_start_double = {} };
                    }
// zbr:selfhost/Lexer.zbr:451
                    self.emit(kind, self.src[@as(usize, @intCast(openPos))..@as(usize, @intCast(self.pos))], ln, cl);
// zbr:selfhost/Lexer.zbr:452
                    hasInterp = true;
                } else {
// zbr:selfhost/Lexer.zbr:454
                    var kind = _zbr_ty_TokenKind{ .string_part_single = {} };
// zbr:selfhost/Lexer.zbr:455
                    if ((q == '"')) {
// zbr:selfhost/Lexer.zbr:456
                        kind = _zbr_ty_TokenKind{ .string_part_double = {} };
                    }
// zbr:selfhost/Lexer.zbr:457
                    self.emit(kind, segText, segLn, ((segStart - self.lineStart) + 1));
                }
// zbr:selfhost/Lexer.zbr:458
                self.pos = (self.pos + 2);
// zbr:selfhost/Lexer.zbr:459
                (try self.scanInterpExpr());
// zbr:selfhost/Lexer.zbr:460
                segStart = self.pos;
// zbr:selfhost/Lexer.zbr:461
                segLn = self.line;
                continue;
            }
// zbr:selfhost/Lexer.zbr:464
            if ((c == q)) {
// zbr:selfhost/Lexer.zbr:465
                const segText: []const u8 = self.src[@as(usize, @intCast(segStart))..@as(usize, @intCast(self.pos))];
// zbr:selfhost/Lexer.zbr:466
                self.pos = (self.pos + 1);
// zbr:selfhost/Lexer.zbr:467
                if ((!hasInterp)) {
// zbr:selfhost/Lexer.zbr:468
                    var kind = _zbr_ty_TokenKind{ .string_single = {} };
// zbr:selfhost/Lexer.zbr:469
                    if ((q == '"')) {
// zbr:selfhost/Lexer.zbr:470
                        kind = _zbr_ty_TokenKind{ .string_double = {} };
                    }
// zbr:selfhost/Lexer.zbr:471
                    self.emit(kind, self.src[@as(usize, @intCast(openPos))..@as(usize, @intCast(self.pos))], ln, cl);
                } else {
// zbr:selfhost/Lexer.zbr:473
                    var kind = _zbr_ty_TokenKind{ .string_stop_single = {} };
// zbr:selfhost/Lexer.zbr:474
                    if ((q == '"')) {
// zbr:selfhost/Lexer.zbr:475
                        kind = _zbr_ty_TokenKind{ .string_stop_double = {} };
                    }
// zbr:selfhost/Lexer.zbr:476
                    self.emit(kind, segText, segLn, ((segStart - self.lineStart) + 1));
                }
// zbr:selfhost/Lexer.zbr:477
                return;
            }
// zbr:selfhost/Lexer.zbr:479
            if ((c == '\n')) {
// zbr:selfhost/Lexer.zbr:480
                { _zbr_rt._error_ctx = .{ .message = _str_concat((std.fmt.allocPrint(_zbr_rt._allocator, "{}", .{self.line}) catch @panic("OOM")), ":1: error: string literal is never closed on this line", _zbr_rt._allocator) }; return error.ZebraError; }
            }
// zbr:selfhost/Lexer.zbr:481
            if ((c == '\\')) {
// zbr:selfhost/Lexer.zbr:482
                self.pos = (self.pos + 2);
                continue;
            }
// zbr:selfhost/Lexer.zbr:484
            self.pos = (self.pos + 1);
        }
// zbr:selfhost/Lexer.zbr:486
        { _zbr_rt._error_ctx = .{ .message = _str_concat((std.fmt.allocPrint(_zbr_rt._allocator, "{}", .{self.line}) catch @panic("OOM")), ":1: error: string literal is never closed on this line", _zbr_rt._allocator) }; return error.ZebraError; }
    }

    // zbr:selfhost/Lexer.zbr:490
    pub fn scanInterpExpr(self: *_zbr_ty_Lexer) anyerror!void {
// zbr:selfhost/Lexer.zbr:491
        var depth: i64 = 1;
// zbr:selfhost/Lexer.zbr:508
        const baseParen: i64 = self.parenDepth;
// zbr:selfhost/Lexer.zbr:509
        while (_zebra_gt(depth, 0)) {
// zbr:selfhost/Lexer.zbr:510
            if (_zebra_ge(self.pos, @as(i64, @intCast(self.src.len)))) {
// zbr:selfhost/Lexer.zbr:511
                { _zbr_rt._error_ctx = .{ .message = _str_concat(_str_concat((std.fmt.allocPrint(_zbr_rt._allocator, "{}", .{self.line}) catch @panic("OOM")), ":1: error: an interpolation opened with $", _zbr_rt._allocator), "{ is never closed in this string", _zbr_rt._allocator) }; return error.ZebraError; }
            }
// zbr:selfhost/Lexer.zbr:512
            const c: u8 = _zbr_at(self.src, self.pos);
// zbr:selfhost/Lexer.zbr:513
            if (((c == ' ') or (c == '\t'))) {
// zbr:selfhost/Lexer.zbr:514
                self.pos = (self.pos + 1);
                continue;
            }
// zbr:selfhost/Lexer.zbr:516
            if ((c == '{')) {
// zbr:selfhost/Lexer.zbr:517
                const ln: i64 = self.line;
// zbr:selfhost/Lexer.zbr:518
                const cl: i64 = self.col();
// zbr:selfhost/Lexer.zbr:519
                self.pos = (self.pos + 1);
// zbr:selfhost/Lexer.zbr:520
                self.emit(_zbr_ty_TokenKind{ .lcurly = {} }, "{", ln, cl);
// zbr:selfhost/Lexer.zbr:521
                depth = (depth + 1);
                continue;
            }
// zbr:selfhost/Lexer.zbr:523
            if ((c == '}')) {
// zbr:selfhost/Lexer.zbr:524
                const ln: i64 = self.line;
// zbr:selfhost/Lexer.zbr:525
                const cl: i64 = self.col();
// zbr:selfhost/Lexer.zbr:526
                self.pos = (self.pos + 1);
// zbr:selfhost/Lexer.zbr:527
                depth = (depth - 1);
// zbr:selfhost/Lexer.zbr:528
                if ((depth == 0)) {
// zbr:selfhost/Lexer.zbr:529
                    self.emit(_zbr_ty_TokenKind{ .rcurly_special = {} }, "}", ln, cl);
                } else {
// zbr:selfhost/Lexer.zbr:531
                    self.emit(_zbr_ty_TokenKind{ .rcurly = {} }, "}", ln, cl);
                }
                continue;
            }
// zbr:selfhost/Lexer.zbr:535
            if ((((c == ':') and (depth == 1)) and (self.parenDepth == baseParen))) {
// zbr:selfhost/Lexer.zbr:536
                const specStart: i64 = self.pos;
// zbr:selfhost/Lexer.zbr:537
                const specLn: i64 = self.line;
// zbr:selfhost/Lexer.zbr:538
                const specCl: i64 = self.col();
// zbr:selfhost/Lexer.zbr:539
                self.pos = (self.pos + 1);
// zbr:selfhost/Lexer.zbr:540
                while (((_zebra_lt(self.pos, @as(i64, @intCast(self.src.len))) and (_zbr_at(self.src, self.pos) != '}')) and (_zbr_at(self.src, self.pos) != '\n'))) {
// zbr:selfhost/Lexer.zbr:541
                    self.pos = (self.pos + 1);
                }
// zbr:selfhost/Lexer.zbr:542
                if ((_zebra_lt(self.pos, @as(i64, @intCast(self.src.len))) and (_zbr_at(self.src, self.pos) == '}'))) {
// zbr:selfhost/Lexer.zbr:543
                    self.emit(_zbr_ty_TokenKind{ .string_part_format = {} }, self.src[@as(usize, @intCast(specStart))..@as(usize, @intCast(self.pos))], specLn, specCl);
                    continue;
                }
// zbr:selfhost/Lexer.zbr:545
                self.pos = specStart;
            }
// zbr:selfhost/Lexer.zbr:553
            (try self.scanToken());
        }
    }

    // zbr:selfhost/Lexer.zbr:557
    pub fn scanDocString(self: *_zbr_ty_Lexer, ln: i64, cl: i64) anyerror!void {
// zbr:selfhost/Lexer.zbr:558
        const start: i64 = self.pos;
// zbr:selfhost/Lexer.zbr:559
        self.pos = (self.pos + 3);
// zbr:selfhost/Lexer.zbr:561
        while ((_zebra_lt(self.pos, @as(i64, @intCast(self.src.len))) and ((_zbr_at(self.src, self.pos) == ' ') or (_zbr_at(self.src, self.pos) == '\t')))) {
// zbr:selfhost/Lexer.zbr:562
            self.pos = (self.pos + 1);
        }
// zbr:selfhost/Lexer.zbr:564
        if ((_zebra_lt(self.pos, @as(i64, @intCast(self.src.len))) and (_zbr_at(self.src, self.pos) != '\n'))) {
// zbr:selfhost/Lexer.zbr:565
            while (_zebra_lt((self.pos + 2), @as(i64, @intCast(self.src.len)))) {
// zbr:selfhost/Lexer.zbr:566
                if ((((_zbr_at(self.src, self.pos) == '"') and (_zbr_at(self.src, (self.pos + 1)) == '"')) and (_zbr_at(self.src, (self.pos + 2)) == '"'))) {
// zbr:selfhost/Lexer.zbr:567
                    self.pos = (self.pos + 3);
// zbr:selfhost/Lexer.zbr:568
                    self.emit(_zbr_ty_TokenKind{ .doc_string_line = {} }, self.src[@as(usize, @intCast(start))..@as(usize, @intCast(self.pos))], ln, cl);
// zbr:selfhost/Lexer.zbr:569
                    return;
                }
// zbr:selfhost/Lexer.zbr:570
                self.pos = (self.pos + 1);
            }
// zbr:selfhost/Lexer.zbr:571
            { _zbr_rt._error_ctx = .{ .message = _str_concat((std.fmt.allocPrint(_zbr_rt._allocator, "{}", .{self.line}) catch @panic("OOM")), ":1: error: string literal is never closed on this line", _zbr_rt._allocator) }; return error.ZebraError; }
        }
// zbr:selfhost/Lexer.zbr:573
        if ((_zebra_lt(self.pos, @as(i64, @intCast(self.src.len))) and (_zbr_at(self.src, self.pos) == '\n'))) {
// zbr:selfhost/Lexer.zbr:574
            self.advanceNewline();
        }
// zbr:selfhost/Lexer.zbr:575
        while (_zebra_lt(self.pos, @as(i64, @intCast(self.src.len)))) {
// zbr:selfhost/Lexer.zbr:576
            var p: i64 = self.pos;
// zbr:selfhost/Lexer.zbr:577
            while ((_zebra_lt(p, @as(i64, @intCast(self.src.len))) and ((_zbr_at(self.src, p) == ' ') or (_zbr_at(self.src, p) == '\t')))) {
// zbr:selfhost/Lexer.zbr:578
                p = (p + 1);
            }
// zbr:selfhost/Lexer.zbr:579
            if ((((_zebra_lt((p + 2), @as(i64, @intCast(self.src.len))) and (_zbr_at(self.src, p) == '"')) and (_zbr_at(self.src, (p + 1)) == '"')) and (_zbr_at(self.src, (p + 2)) == '"'))) {
// zbr:selfhost/Lexer.zbr:580
                self.pos = (p + 3);
// zbr:selfhost/Lexer.zbr:581
                self.emit(_zbr_ty_TokenKind{ .doc_string_line = {} }, self.src[@as(usize, @intCast(start))..@as(usize, @intCast(self.pos))], ln, cl);
// zbr:selfhost/Lexer.zbr:582
                return;
            }
// zbr:selfhost/Lexer.zbr:583
            while ((_zebra_lt(self.pos, @as(i64, @intCast(self.src.len))) and (_zbr_at(self.src, self.pos) != '\n'))) {
// zbr:selfhost/Lexer.zbr:584
                self.pos = (self.pos + 1);
            }
// zbr:selfhost/Lexer.zbr:585
            if (_zebra_lt(self.pos, @as(i64, @intCast(self.src.len)))) {
// zbr:selfhost/Lexer.zbr:586
                self.advanceNewline();
            }
        }
// zbr:selfhost/Lexer.zbr:588
        { _zbr_rt._error_ctx = .{ .message = _str_concat((std.fmt.allocPrint(_zbr_rt._allocator, "{}", .{self.line}) catch @panic("OOM")), ":1: error: string literal is never closed on this line", _zbr_rt._allocator) }; return error.ZebraError; }
    }

    // zbr:selfhost/Lexer.zbr:592
    pub fn scanNumericLiteral(self: *_zbr_ty_Lexer, ln: i64, cl: i64) anyerror!void {
// zbr:selfhost/Lexer.zbr:593
        const start: i64 = self.pos;
// zbr:selfhost/Lexer.zbr:595
        if ((((_zbr_at(self.src, self.pos) == '0') and _zebra_lt((self.pos + 1), @as(i64, @intCast(self.src.len)))) and (_zbr_at(self.src, (self.pos + 1)) == 'x'))) {
// zbr:selfhost/Lexer.zbr:596
            self.pos = (self.pos + 2);
// zbr:selfhost/Lexer.zbr:597
            self.scanWhile(.from(_zbr_fn_isHexDigit));
// zbr:selfhost/Lexer.zbr:598
            if ((self.peek() == '_')) {
// zbr:selfhost/Lexer.zbr:599
                const suffixStart: i64 = self.pos;
// zbr:selfhost/Lexer.zbr:600
                self.pos = (self.pos + 1);
// zbr:selfhost/Lexer.zbr:601
                if ((self.peek() == 'u')) {
// zbr:selfhost/Lexer.zbr:602
                    self.pos = (self.pos + 1);
// zbr:selfhost/Lexer.zbr:603
                    self.scanWhile(.from(_zbr_fn_isDigit));
// zbr:selfhost/Lexer.zbr:604
                    self.emit(_zbr_ty_TokenKind{ .hex_lit_unsign = {} }, self.src[@as(usize, @intCast(start))..@as(usize, @intCast(self.pos))], ln, cl);
// zbr:selfhost/Lexer.zbr:605
                    return;
                }
// zbr:selfhost/Lexer.zbr:606
                self.scanWhile(.from(_zbr_fn_isDigit));
// zbr:selfhost/Lexer.zbr:607
                if (_zebra_gt(self.pos, (suffixStart + 1))) {
// zbr:selfhost/Lexer.zbr:608
                    self.emit(_zbr_ty_TokenKind{ .hex_lit_explicit = {} }, self.src[@as(usize, @intCast(start))..@as(usize, @intCast(self.pos))], ln, cl);
// zbr:selfhost/Lexer.zbr:609
                    return;
                }
// zbr:selfhost/Lexer.zbr:610
                self.pos = suffixStart;
            }
// zbr:selfhost/Lexer.zbr:611
            self.emit(_zbr_ty_TokenKind{ .hex_lit = {} }, self.src[@as(usize, @intCast(start))..@as(usize, @intCast(self.pos))], ln, cl);
// zbr:selfhost/Lexer.zbr:612
            return;
        }
// zbr:selfhost/Lexer.zbr:614
        self.scanWhile(.from(_zbr_fn_isDigitOrUnder));
// zbr:selfhost/Lexer.zbr:616
        var hasDot: bool = ((self.peek() == '.') and _zbr_fn_isDigit(self.peekAt(1)));
// zbr:selfhost/Lexer.zbr:617
        if (hasDot) {
// zbr:selfhost/Lexer.zbr:618
            self.pos = (self.pos + 1);
// zbr:selfhost/Lexer.zbr:619
            self.scanWhile(.from(_zbr_fn_isDigitOrUnder));
        }
// zbr:selfhost/Lexer.zbr:623
        if (((self.peek() == 'e') or (self.peek() == 'E'))) {
// zbr:selfhost/Lexer.zbr:624
            var exp_ok: bool = _zbr_fn_isDigit(self.peekAt(1));
// zbr:selfhost/Lexer.zbr:625
            if (((!exp_ok) and ((self.peekAt(1) == '+') or (self.peekAt(1) == '-')))) {
// zbr:selfhost/Lexer.zbr:626
                exp_ok = _zbr_fn_isDigit(self.peekAt(2));
            }
// zbr:selfhost/Lexer.zbr:627
            if (exp_ok) {
// zbr:selfhost/Lexer.zbr:628
                self.pos = (self.pos + 1);
// zbr:selfhost/Lexer.zbr:629
                if (((self.peek() == '+') or (self.peek() == '-'))) {
// zbr:selfhost/Lexer.zbr:630
                    self.pos = (self.pos + 1);
                }
// zbr:selfhost/Lexer.zbr:631
                self.scanWhile(.from(_zbr_fn_isDigit));
// zbr:selfhost/Lexer.zbr:632
                hasDot = true;
            }
        }
// zbr:selfhost/Lexer.zbr:634
        const sc: u21 = self.peek();
// zbr:selfhost/Lexer.zbr:635
        const sc1: u21 = self.peek1();
// zbr:selfhost/Lexer.zbr:637
        if ((((sc == '_') and (sc1 == 'd')) and (!_zbr_fn_isIdentContinue(self.peekAt(2))))) {
// zbr:selfhost/Lexer.zbr:638
            self.pos = (self.pos + 2);
// zbr:selfhost/Lexer.zbr:639
            self.emit(_zbr_ty_TokenKind{ .decimal_lit = {} }, self.src[@as(usize, @intCast(start))..@as(usize, @intCast(self.pos))], ln, cl);
// zbr:selfhost/Lexer.zbr:640
            return;
        }
// zbr:selfhost/Lexer.zbr:642
        if ((((sc == '_') and (sc1 == 'n')) and (!_zbr_fn_isIdentContinue(self.peekAt(2))))) {
// zbr:selfhost/Lexer.zbr:643
            self.pos = (self.pos + 2);
// zbr:selfhost/Lexer.zbr:644
            self.emit(_zbr_ty_TokenKind{ .number_lit = {} }, self.src[@as(usize, @intCast(start))..@as(usize, @intCast(self.pos))], ln, cl);
// zbr:selfhost/Lexer.zbr:645
            return;
        }
// zbr:selfhost/Lexer.zbr:647
        if ((((sc == '_') and (sc1 == 'f')) or (sc == 'f'))) {
// zbr:selfhost/Lexer.zbr:648
            if ((sc == '_')) {
// zbr:selfhost/Lexer.zbr:649
                self.pos = (self.pos + 1);
            }
// zbr:selfhost/Lexer.zbr:650
            self.pos = (self.pos + 1);
// zbr:selfhost/Lexer.zbr:651
            if ((((self.peek() == '3') and (self.peekAt(1) == '2')) or ((self.peek() == '6') and (self.peekAt(1) == '4')))) {
// zbr:selfhost/Lexer.zbr:652
                self.pos = (self.pos + 2);
            }
// zbr:selfhost/Lexer.zbr:653
            self.emit(_zbr_ty_TokenKind{ .float_lit = {} }, self.src[@as(usize, @intCast(start))..@as(usize, @intCast(self.pos))], ln, cl);
// zbr:selfhost/Lexer.zbr:654
            return;
        }
// zbr:selfhost/Lexer.zbr:656
        if (((((sc == '_') and ((sc1 == 'i') or (sc1 == 'u'))) or (sc == 'i')) or (sc == 'u'))) {
// zbr:selfhost/Lexer.zbr:657
            if ((sc == '_')) {
// zbr:selfhost/Lexer.zbr:658
                self.pos = (self.pos + 1);
            }
// zbr:selfhost/Lexer.zbr:659
            self.pos = (self.pos + 1);
// zbr:selfhost/Lexer.zbr:660
            self.scanWhile(.from(_zbr_fn_isDigit));
// zbr:selfhost/Lexer.zbr:661
            self.emit(_zbr_ty_TokenKind{ .integer_lit_explicit = {} }, self.src[@as(usize, @intCast(start))..@as(usize, @intCast(self.pos))], ln, cl);
// zbr:selfhost/Lexer.zbr:662
            return;
        }
// zbr:selfhost/Lexer.zbr:664
        if (hasDot) {
// zbr:selfhost/Lexer.zbr:665
            self.emit(_zbr_ty_TokenKind{ .float_lit = {} }, self.src[@as(usize, @intCast(start))..@as(usize, @intCast(self.pos))], ln, cl);
        } else {
// zbr:selfhost/Lexer.zbr:667
            self.emit(_zbr_ty_TokenKind{ .integer_lit = {} }, self.src[@as(usize, @intCast(start))..@as(usize, @intCast(self.pos))], ln, cl);
        }
    }

    // zbr:selfhost/Lexer.zbr:671
    pub fn scanOperator(self: *_zbr_ty_Lexer, ln: i64, cl: i64) anyerror!void {
// zbr:selfhost/Lexer.zbr:672
        const c: u21 = self.peek();
// zbr:selfhost/Lexer.zbr:673
        const c1: u21 = self.peek1();
// zbr:selfhost/Lexer.zbr:676
        if (_zebra_lt((self.pos + 2), @as(i64, @intCast(self.src.len)))) {
// zbr:selfhost/Lexer.zbr:677
            const c2: u8 = _zbr_at(self.src, (self.pos + 2));
// zbr:selfhost/Lexer.zbr:678
            if ((((c == '/') and (c1 == '/')) and (c2 == '='))) {
// zbr:selfhost/Lexer.zbr:679
                self.pos = (self.pos + 3);
// zbr:selfhost/Lexer.zbr:680
                self.emit(_zbr_ty_TokenKind{ .slashslash_equals = {} }, "//=", ln, cl);
// zbr:selfhost/Lexer.zbr:681
                return;
            }
// zbr:selfhost/Lexer.zbr:682
            if ((((c == '*') and (c1 == '*')) and (c2 == '='))) {
// zbr:selfhost/Lexer.zbr:683
                self.pos = (self.pos + 3);
// zbr:selfhost/Lexer.zbr:684
                self.emit(_zbr_ty_TokenKind{ .starstar_equals = {} }, "**=", ln, cl);
// zbr:selfhost/Lexer.zbr:685
                return;
            }
// zbr:selfhost/Lexer.zbr:686
            if ((((c == '<') and (c1 == '<')) and (c2 == '='))) {
// zbr:selfhost/Lexer.zbr:687
                self.pos = (self.pos + 3);
// zbr:selfhost/Lexer.zbr:688
                self.emit(_zbr_ty_TokenKind{ .double_lt_equals = {} }, "<<=", ln, cl);
// zbr:selfhost/Lexer.zbr:689
                return;
            }
// zbr:selfhost/Lexer.zbr:692
            if ((((c == '<') and (c1 == '<')) and (c2 == '-'))) {
// zbr:selfhost/Lexer.zbr:693
                self.pos = (self.pos + 3);
// zbr:selfhost/Lexer.zbr:694
                self.emit(_zbr_ty_TokenKind{ .left_arrow_deep = {} }, "<<-", ln, cl);
// zbr:selfhost/Lexer.zbr:695
                return;
            }
// zbr:selfhost/Lexer.zbr:696
            if ((((c == '>') and (c1 == '>')) and (c2 == '='))) {
// zbr:selfhost/Lexer.zbr:697
                self.pos = (self.pos + 3);
// zbr:selfhost/Lexer.zbr:698
                self.emit(_zbr_ty_TokenKind{ .double_gt_equals = {} }, ">>=", ln, cl);
// zbr:selfhost/Lexer.zbr:699
                return;
            }
        }
// zbr:selfhost/Lexer.zbr:702
        if (((c == '+') and (c1 == '+'))) {
// zbr:selfhost/Lexer.zbr:703
            self.pos = (self.pos + 2);
// zbr:selfhost/Lexer.zbr:704
            self.emit(_zbr_ty_TokenKind{ .plusplus = {} }, "++", ln, cl);
// zbr:selfhost/Lexer.zbr:705
            return;
        }
// zbr:selfhost/Lexer.zbr:706
        if (((c == '+') and (c1 == '='))) {
// zbr:selfhost/Lexer.zbr:707
            self.pos = (self.pos + 2);
// zbr:selfhost/Lexer.zbr:708
            self.emit(_zbr_ty_TokenKind{ .plus_equals = {} }, "+=", ln, cl);
// zbr:selfhost/Lexer.zbr:709
            return;
        }
// zbr:selfhost/Lexer.zbr:710
        if (((c == '-') and (c1 == '>'))) {
// zbr:selfhost/Lexer.zbr:711
            self.pos = (self.pos + 2);
// zbr:selfhost/Lexer.zbr:712
            self.emit(_zbr_ty_TokenKind{ .arrow = {} }, "->", ln, cl);
// zbr:selfhost/Lexer.zbr:713
            return;
        }
// zbr:selfhost/Lexer.zbr:714
        if (((c == '-') and (c1 == '-'))) {
// zbr:selfhost/Lexer.zbr:715
            self.pos = (self.pos + 2);
// zbr:selfhost/Lexer.zbr:716
            self.emit(_zbr_ty_TokenKind{ .minusminus = {} }, "--", ln, cl);
// zbr:selfhost/Lexer.zbr:717
            return;
        }
// zbr:selfhost/Lexer.zbr:718
        if (((c == '-') and (c1 == '='))) {
// zbr:selfhost/Lexer.zbr:719
            self.pos = (self.pos + 2);
// zbr:selfhost/Lexer.zbr:720
            self.emit(_zbr_ty_TokenKind{ .minus_equals = {} }, "-=", ln, cl);
// zbr:selfhost/Lexer.zbr:721
            return;
        }
// zbr:selfhost/Lexer.zbr:722
        if (((c == '*') and (c1 == '*'))) {
// zbr:selfhost/Lexer.zbr:723
            self.pos = (self.pos + 2);
// zbr:selfhost/Lexer.zbr:724
            self.emit(_zbr_ty_TokenKind{ .starstar = {} }, "**", ln, cl);
// zbr:selfhost/Lexer.zbr:725
            return;
        }
// zbr:selfhost/Lexer.zbr:726
        if (((c == '*') and (c1 == '='))) {
// zbr:selfhost/Lexer.zbr:727
            self.pos = (self.pos + 2);
// zbr:selfhost/Lexer.zbr:728
            self.emit(_zbr_ty_TokenKind{ .star_equals = {} }, "*=", ln, cl);
// zbr:selfhost/Lexer.zbr:729
            return;
        }
// zbr:selfhost/Lexer.zbr:730
        if (((c == '/') and (c1 == '/'))) {
// zbr:selfhost/Lexer.zbr:731
            self.pos = (self.pos + 2);
// zbr:selfhost/Lexer.zbr:732
            self.emit(_zbr_ty_TokenKind{ .slashslash = {} }, "//", ln, cl);
// zbr:selfhost/Lexer.zbr:733
            return;
        }
// zbr:selfhost/Lexer.zbr:734
        if (((c == '/') and (c1 == '='))) {
// zbr:selfhost/Lexer.zbr:735
            self.pos = (self.pos + 2);
// zbr:selfhost/Lexer.zbr:736
            self.emit(_zbr_ty_TokenKind{ .slash_equals = {} }, "/=", ln, cl);
// zbr:selfhost/Lexer.zbr:737
            return;
        }
// zbr:selfhost/Lexer.zbr:738
        if (((c == '%') and (c1 == '%'))) {
// zbr:selfhost/Lexer.zbr:739
            self.pos = (self.pos + 2);
// zbr:selfhost/Lexer.zbr:740
            self.emit(_zbr_ty_TokenKind{ .percentpercent = {} }, "%%", ln, cl);
// zbr:selfhost/Lexer.zbr:741
            return;
        }
// zbr:selfhost/Lexer.zbr:742
        if (((c == '%') and (c1 == '='))) {
// zbr:selfhost/Lexer.zbr:743
            self.pos = (self.pos + 2);
// zbr:selfhost/Lexer.zbr:744
            self.emit(_zbr_ty_TokenKind{ .percent_equals = {} }, "%=", ln, cl);
// zbr:selfhost/Lexer.zbr:745
            return;
        }
// zbr:selfhost/Lexer.zbr:746
        if (((c == '=') and (c1 == '='))) {
// zbr:selfhost/Lexer.zbr:747
            self.pos = (self.pos + 2);
// zbr:selfhost/Lexer.zbr:748
            self.emit(_zbr_ty_TokenKind{ .eq = {} }, "==", ln, cl);
// zbr:selfhost/Lexer.zbr:749
            return;
        }
// zbr:selfhost/Lexer.zbr:750
        if (((c == '<') and (c1 == '>'))) {
// zbr:selfhost/Lexer.zbr:751
            self.pos = (self.pos + 2);
// zbr:selfhost/Lexer.zbr:752
            self.emit(_zbr_ty_TokenKind{ .ne = {} }, "<>", ln, cl);
// zbr:selfhost/Lexer.zbr:753
            return;
        }
// zbr:selfhost/Lexer.zbr:754
        if (((c == '<') and (c1 == '='))) {
// zbr:selfhost/Lexer.zbr:755
            self.pos = (self.pos + 2);
// zbr:selfhost/Lexer.zbr:756
            self.emit(_zbr_ty_TokenKind{ .le = {} }, "<=", ln, cl);
// zbr:selfhost/Lexer.zbr:757
            return;
        }
// zbr:selfhost/Lexer.zbr:758
        if (((c == '<') and (c1 == '<'))) {
// zbr:selfhost/Lexer.zbr:759
            self.pos = (self.pos + 2);
// zbr:selfhost/Lexer.zbr:760
            self.emit(_zbr_ty_TokenKind{ .double_lt = {} }, "<<", ln, cl);
// zbr:selfhost/Lexer.zbr:761
            return;
        }
// zbr:selfhost/Lexer.zbr:762
        if (((c == '<') and (c1 == '-'))) {
// zbr:selfhost/Lexer.zbr:763
            self.pos = (self.pos + 2);
// zbr:selfhost/Lexer.zbr:764
            self.emit(_zbr_ty_TokenKind{ .left_arrow = {} }, "<-", ln, cl);
// zbr:selfhost/Lexer.zbr:765
            return;
        }
// zbr:selfhost/Lexer.zbr:766
        if (((c == '>') and (c1 == '='))) {
// zbr:selfhost/Lexer.zbr:767
            self.pos = (self.pos + 2);
// zbr:selfhost/Lexer.zbr:768
            self.emit(_zbr_ty_TokenKind{ .ge = {} }, ">=", ln, cl);
// zbr:selfhost/Lexer.zbr:769
            return;
        }
// zbr:selfhost/Lexer.zbr:770
        if (((c == '>') and (c1 == '>'))) {
// zbr:selfhost/Lexer.zbr:771
            self.pos = (self.pos + 2);
// zbr:selfhost/Lexer.zbr:772
            self.emit(_zbr_ty_TokenKind{ .double_gt = {} }, ">>", ln, cl);
// zbr:selfhost/Lexer.zbr:773
            return;
        }
// zbr:selfhost/Lexer.zbr:774
        if (((c == '&') and (c1 == '='))) {
// zbr:selfhost/Lexer.zbr:775
            self.pos = (self.pos + 2);
// zbr:selfhost/Lexer.zbr:776
            self.emit(_zbr_ty_TokenKind{ .ampersand_equals = {} }, "&=", ln, cl);
// zbr:selfhost/Lexer.zbr:777
            return;
        }
// zbr:selfhost/Lexer.zbr:778
        if (((c == '|') and (c1 == '='))) {
// zbr:selfhost/Lexer.zbr:779
            self.pos = (self.pos + 2);
// zbr:selfhost/Lexer.zbr:780
            self.emit(_zbr_ty_TokenKind{ .vertical_bar_equals = {} }, "|=", ln, cl);
// zbr:selfhost/Lexer.zbr:781
            return;
        }
// zbr:selfhost/Lexer.zbr:782
        if (((c == '^') and (c1 == '='))) {
// zbr:selfhost/Lexer.zbr:783
            self.pos = (self.pos + 2);
// zbr:selfhost/Lexer.zbr:784
            self.emit(_zbr_ty_TokenKind{ .caret_equals = {} }, "^=", ln, cl);
// zbr:selfhost/Lexer.zbr:785
            return;
        }
// zbr:selfhost/Lexer.zbr:786
        if (((c == '?') and (c1 == '='))) {
// zbr:selfhost/Lexer.zbr:787
            self.pos = (self.pos + 2);
// zbr:selfhost/Lexer.zbr:788
            self.emit(_zbr_ty_TokenKind{ .question_equals = {} }, "?=", ln, cl);
// zbr:selfhost/Lexer.zbr:789
            return;
        }
// zbr:selfhost/Lexer.zbr:790
        if (((c == '?') and (c1 == '.'))) {
// zbr:selfhost/Lexer.zbr:791
            self.pos = (self.pos + 2);
// zbr:selfhost/Lexer.zbr:792
            self.emit(_zbr_ty_TokenKind{ .question_dot = {} }, "?.", ln, cl);
// zbr:selfhost/Lexer.zbr:793
            return;
        }
// zbr:selfhost/Lexer.zbr:794
        if (((c == '!') and (c1 == '='))) {
// zbr:selfhost/Lexer.zbr:795
            self.pos = (self.pos + 2);
// zbr:selfhost/Lexer.zbr:796
            self.emit(_zbr_ty_TokenKind{ .bang_equals = {} }, "!=", ln, cl);
// zbr:selfhost/Lexer.zbr:797
            return;
        }
// zbr:selfhost/Lexer.zbr:798
        if (((c == '.') and (c1 == '.'))) {
// zbr:selfhost/Lexer.zbr:799
            self.pos = (self.pos + 2);
// zbr:selfhost/Lexer.zbr:800
            self.emit(_zbr_ty_TokenKind{ .dotdot = {} }, "..", ln, cl);
// zbr:selfhost/Lexer.zbr:801
            return;
        }
// zbr:selfhost/Lexer.zbr:804
        self.pos = (self.pos + 1);
// zbr:selfhost/Lexer.zbr:805
        if ((c == '+')) {
// zbr:selfhost/Lexer.zbr:806
            self.emit(_zbr_ty_TokenKind{ .plus = {} }, "+", ln, cl);
// zbr:selfhost/Lexer.zbr:807
            return;
        }
// zbr:selfhost/Lexer.zbr:808
        if ((c == '-')) {
// zbr:selfhost/Lexer.zbr:809
            self.emit(_zbr_ty_TokenKind{ .minus = {} }, "-", ln, cl);
// zbr:selfhost/Lexer.zbr:810
            return;
        }
// zbr:selfhost/Lexer.zbr:811
        if ((c == '*')) {
// zbr:selfhost/Lexer.zbr:812
            self.emit(_zbr_ty_TokenKind{ .star = {} }, "*", ln, cl);
// zbr:selfhost/Lexer.zbr:813
            return;
        }
// zbr:selfhost/Lexer.zbr:814
        if ((c == '/')) {
// zbr:selfhost/Lexer.zbr:815
            self.emit(_zbr_ty_TokenKind{ .slash = {} }, "/", ln, cl);
// zbr:selfhost/Lexer.zbr:816
            return;
        }
// zbr:selfhost/Lexer.zbr:817
        if ((c == '%')) {
// zbr:selfhost/Lexer.zbr:818
            self.emit(_zbr_ty_TokenKind{ .percent = {} }, "%", ln, cl);
// zbr:selfhost/Lexer.zbr:819
            return;
        }
// zbr:selfhost/Lexer.zbr:820
        if ((c == '=')) {
// zbr:selfhost/Lexer.zbr:821
            if (self.afterLambdaParams) {
// zbr:selfhost/Lexer.zbr:822
                self.afterLambdaParams = false;
            }
// zbr:selfhost/Lexer.zbr:823
            self.emit(_zbr_ty_TokenKind{ .assign = {} }, "=", ln, cl);
// zbr:selfhost/Lexer.zbr:824
            return;
        }
// zbr:selfhost/Lexer.zbr:825
        if ((c == '<')) {
// zbr:selfhost/Lexer.zbr:826
            self.emit(_zbr_ty_TokenKind{ .lt = {} }, "<", ln, cl);
// zbr:selfhost/Lexer.zbr:827
            return;
        }
// zbr:selfhost/Lexer.zbr:828
        if ((c == '>')) {
// zbr:selfhost/Lexer.zbr:829
            self.emit(_zbr_ty_TokenKind{ .gt = {} }, ">", ln, cl);
// zbr:selfhost/Lexer.zbr:830
            return;
        }
// zbr:selfhost/Lexer.zbr:831
        if ((c == '&')) {
// zbr:selfhost/Lexer.zbr:832
            self.emit(_zbr_ty_TokenKind{ .ampersand = {} }, "&", ln, cl);
// zbr:selfhost/Lexer.zbr:833
            return;
        }
// zbr:selfhost/Lexer.zbr:834
        if ((c == '|')) {
// zbr:selfhost/Lexer.zbr:835
            self.emit(_zbr_ty_TokenKind{ .vertical_bar = {} }, "|", ln, cl);
// zbr:selfhost/Lexer.zbr:836
            return;
        }
// zbr:selfhost/Lexer.zbr:837
        if ((c == '^')) {
// zbr:selfhost/Lexer.zbr:838
            self.emit(_zbr_ty_TokenKind{ .caret = {} }, "^", ln, cl);
// zbr:selfhost/Lexer.zbr:839
            return;
        }
// zbr:selfhost/Lexer.zbr:840
        if ((c == '~')) {
// zbr:selfhost/Lexer.zbr:841
            self.emit(_zbr_ty_TokenKind{ .tilde = {} }, "~", ln, cl);
// zbr:selfhost/Lexer.zbr:842
            return;
        }
// zbr:selfhost/Lexer.zbr:843
        if ((c == '?')) {
// zbr:selfhost/Lexer.zbr:844
            self.emit(_zbr_ty_TokenKind{ .question = {} }, "?", ln, cl);
// zbr:selfhost/Lexer.zbr:845
            return;
        }
// zbr:selfhost/Lexer.zbr:846
        if ((c == '!')) {
// zbr:selfhost/Lexer.zbr:847
            self.emit(_zbr_ty_TokenKind{ .bang = {} }, "!", ln, cl);
// zbr:selfhost/Lexer.zbr:848
            return;
        }
// zbr:selfhost/Lexer.zbr:849
        if ((c == '.')) {
// zbr:selfhost/Lexer.zbr:850
            self.emit(_zbr_ty_TokenKind{ .dot = {} }, ".", ln, cl);
// zbr:selfhost/Lexer.zbr:851
            return;
        }
// zbr:selfhost/Lexer.zbr:852
        if ((c == ':')) {
// zbr:selfhost/Lexer.zbr:853
            self.emit(_zbr_ty_TokenKind{ .colon = {} }, ":", ln, cl);
// zbr:selfhost/Lexer.zbr:854
            return;
        }
// zbr:selfhost/Lexer.zbr:855
        if ((c == ';')) {
// zbr:selfhost/Lexer.zbr:856
            self.emit(_zbr_ty_TokenKind{ .semi = {} }, ";", ln, cl);
// zbr:selfhost/Lexer.zbr:857
            return;
        }
// zbr:selfhost/Lexer.zbr:858
        if ((c == ',')) {
// zbr:selfhost/Lexer.zbr:859
            self.emit(_zbr_ty_TokenKind{ .comma = {} }, ",", ln, cl);
// zbr:selfhost/Lexer.zbr:860
            return;
        }
// zbr:selfhost/Lexer.zbr:861
        if ((c == '(')) {
// zbr:selfhost/Lexer.zbr:862
            if ((_zebra_gt(self.parenDepth, 0) and _zebra_gt(@as(i64, @intCast(self.out.items.len)), 0))) {
// zbr:selfhost/Lexer.zbr:863
                const lastKind = _zbr_at(self.out.items, (@as(i64, @intCast(self.out.items.len)) - 1)).kind;
// zbr:selfhost/Lexer.zbr:864
                switch (_zbr_val(lastKind)) {
                    .kw_def => {
// zbr:selfhost/Lexer.zbr:866
                        self.inLambdaParams = true;
// zbr:selfhost/Lexer.zbr:867
                        self.lambdaParamDepth = (self.parenDepth + 1);
                    },
                    else => {
                        // pass
                    },
                }
            }
// zbr:selfhost/Lexer.zbr:870
            self.parenDepth = (self.parenDepth + 1);
// zbr:selfhost/Lexer.zbr:871
            self.emit(_zbr_ty_TokenKind{ .lparen = {} }, "(", ln, cl);
// zbr:selfhost/Lexer.zbr:872
            return;
        }
// zbr:selfhost/Lexer.zbr:873
        if ((c == ')')) {
// zbr:selfhost/Lexer.zbr:874
            if ((self.inLambdaParams and (self.parenDepth == self.lambdaParamDepth))) {
// zbr:selfhost/Lexer.zbr:875
                self.inLambdaParams = false;
// zbr:selfhost/Lexer.zbr:876
                self.afterLambdaParams = true;
            }
// zbr:selfhost/Lexer.zbr:877
            self.parenDepth = (self.parenDepth - 1);
// zbr:selfhost/Lexer.zbr:878
            self.emit(_zbr_ty_TokenKind{ .rparen = {} }, ")", ln, cl);
// zbr:selfhost/Lexer.zbr:879
            return;
        }
// zbr:selfhost/Lexer.zbr:880
        if ((c == '[')) {
// zbr:selfhost/Lexer.zbr:881
            self.emit(_zbr_ty_TokenKind{ .lbracket = {} }, "[", ln, cl);
// zbr:selfhost/Lexer.zbr:882
            return;
        }
// zbr:selfhost/Lexer.zbr:883
        if ((c == ']')) {
// zbr:selfhost/Lexer.zbr:884
            self.emit(_zbr_ty_TokenKind{ .rbracket = {} }, "]", ln, cl);
// zbr:selfhost/Lexer.zbr:885
            return;
        }
// zbr:selfhost/Lexer.zbr:886
        if ((c == '{')) {
// zbr:selfhost/Lexer.zbr:887
            self.emit(_zbr_ty_TokenKind{ .lcurly = {} }, "{", ln, cl);
// zbr:selfhost/Lexer.zbr:888
            return;
        }
// zbr:selfhost/Lexer.zbr:889
        if ((c == '}')) {
// zbr:selfhost/Lexer.zbr:890
            self.emit(_zbr_ty_TokenKind{ .rcurly = {} }, "}", ln, cl);
// zbr:selfhost/Lexer.zbr:891
            return;
        }
// zbr:selfhost/Lexer.zbr:892
        { _zbr_rt._error_ctx = .{ .message = self.lexErr(c, ln, cl) }; return error.ZebraError; }
    }

    // zbr:selfhost/Lexer.zbr:896
    pub fn scanToken(self: *_zbr_ty_Lexer) anyerror!void {
// zbr:selfhost/Lexer.zbr:897
        const c: u8 = _zbr_at(self.src, self.pos);
// zbr:selfhost/Lexer.zbr:898
        const ln: i64 = self.line;
// zbr:selfhost/Lexer.zbr:899
        const cl: i64 = self.col();
// zbr:selfhost/Lexer.zbr:900
        switch (_zbr_val(c)) {
            '0'...'9' => {
// zbr:selfhost/Lexer.zbr:902
                (try self.scanNumericLiteral(ln, cl));
            },
            '@' => {
// zbr:selfhost/Lexer.zbr:904
                (try self.scanAt(ln, cl));
            },
            'a'...'z' => {
// zbr:selfhost/Lexer.zbr:906
                (try self.scanIdentOrKeyword(ln, cl));
            },
            'A'...'Z' => {
// zbr:selfhost/Lexer.zbr:908
                (try self.scanIdentOrKeyword(ln, cl));
            },
            '_' => {
// zbr:selfhost/Lexer.zbr:910
                (try self.scanIdentOrKeyword(ln, cl));
            },
            '\'' => {
// zbr:selfhost/Lexer.zbr:912
                (try self.scanSingleQuote(ln, cl));
            },
            '"' => {
// zbr:selfhost/Lexer.zbr:914
                (try self.scanString(c, ln, cl));
            },
            else => {
// zbr:selfhost/Lexer.zbr:916
                (try self.scanOperator(ln, cl));
            },
        }
    }

    // zbr:selfhost/Lexer.zbr:920
    pub fn run(self: *_zbr_ty_Lexer) anyerror!void {
// zbr:selfhost/Lexer.zbr:921
        var atLineStart: bool = true;
// zbr:selfhost/Lexer.zbr:922
        while (_zebra_lt(self.pos, @as(i64, @intCast(self.src.len)))) {
// zbr:selfhost/Lexer.zbr:923
            if (atLineStart) {
// zbr:selfhost/Lexer.zbr:924
                atLineStart = false;
// zbr:selfhost/Lexer.zbr:925
                const lk = self.classifyLine();
// zbr:selfhost/Lexer.zbr:926
                switch (_zbr_val(lk)) {
                    .empty => {
// zbr:selfhost/Lexer.zbr:928
                        const ln: i64 = self.line;
// zbr:selfhost/Lexer.zbr:929
                        const cl: i64 = self.col();
// zbr:selfhost/Lexer.zbr:930
                        self.advanceNewline();
// zbr:selfhost/Lexer.zbr:931
                        if ((((self.parenDepth == 0) or self.afterLambdaParams) or _zebra_gt(@as(i64, @intCast(self.lambdaStack.items.len)), 0))) {
// zbr:selfhost/Lexer.zbr:932
                            self.emit(_zbr_ty_TokenKind{ .eol = {} }, "\n", ln, cl);
// zbr:selfhost/Lexer.zbr:933
                            if (self.afterLambdaParams) {
// zbr:selfhost/Lexer.zbr:934
                                self.afterLambdaParams = false;
// zbr:selfhost/Lexer.zbr:935
                                self.lambdaStack.append(_zbr_rt._allocator, self.indentDepth) catch @panic("OOM");
                            }
                        }
// zbr:selfhost/Lexer.zbr:936
                        atLineStart = true;
                        continue;
                    },
                    .whitespace_only => {
// zbr:selfhost/Lexer.zbr:939
                        while ((_zebra_lt(self.pos, @as(i64, @intCast(self.src.len))) and (_zbr_at(self.src, self.pos) != '\n'))) {
// zbr:selfhost/Lexer.zbr:940
                            self.pos = (self.pos + 1);
                        }
// zbr:selfhost/Lexer.zbr:941
                        if (_zebra_lt(self.pos, @as(i64, @intCast(self.src.len)))) {
// zbr:selfhost/Lexer.zbr:942
                            self.advanceNewline();
                        }
// zbr:selfhost/Lexer.zbr:943
                        atLineStart = true;
                        continue;
                    },
                    .comment_only => {
// zbr:selfhost/Lexer.zbr:946
                        while ((_zebra_lt(self.pos, @as(i64, @intCast(self.src.len))) and (_zbr_at(self.src, self.pos) != '\n'))) {
// zbr:selfhost/Lexer.zbr:947
                            self.pos = (self.pos + 1);
                        }
// zbr:selfhost/Lexer.zbr:948
                        if (_zebra_lt(self.pos, @as(i64, @intCast(self.src.len)))) {
// zbr:selfhost/Lexer.zbr:949
                            self.advanceNewline();
                        }
// zbr:selfhost/Lexer.zbr:950
                        atLineStart = true;
                        continue;
                    },
                    .block_comment_only => {
// zbr:selfhost/Lexer.zbr:956
                        while ((_zebra_lt(self.pos, @as(i64, @intCast(self.src.len))) and ((_zbr_at(self.src, self.pos) == ' ') or (_zbr_at(self.src, self.pos) == '\t')))) {
// zbr:selfhost/Lexer.zbr:957
                            self.pos = (self.pos + 1);
                        }
// zbr:selfhost/Lexer.zbr:958
                        (try self.scanBlockComment());
// zbr:selfhost/Lexer.zbr:959
                        while ((_zebra_lt(self.pos, @as(i64, @intCast(self.src.len))) and (_zbr_at(self.src, self.pos) != '\n'))) {
// zbr:selfhost/Lexer.zbr:960
                            self.pos = (self.pos + 1);
                        }
// zbr:selfhost/Lexer.zbr:961
                        if (_zebra_lt(self.pos, @as(i64, @intCast(self.src.len)))) {
// zbr:selfhost/Lexer.zbr:962
                            self.advanceNewline();
                        }
// zbr:selfhost/Lexer.zbr:963
                        atLineStart = true;
                        continue;
                    },
                    .has_content => {
// zbr:selfhost/Lexer.zbr:966
                        if (((self.parenDepth == 0) or _zebra_gt(@as(i64, @intCast(self.lambdaStack.items.len)), 0))) {
// zbr:selfhost/Lexer.zbr:967
                            (try self.processIndentation());
                        }
                    },
                }
            }
// zbr:selfhost/Lexer.zbr:969
            const c: u8 = _zbr_at(self.src, self.pos);
// zbr:selfhost/Lexer.zbr:971
            if (((c == ' ') or (c == '\t'))) {
// zbr:selfhost/Lexer.zbr:972
                self.pos = (self.pos + 1);
                continue;
            }
// zbr:selfhost/Lexer.zbr:975
            if ((c == '\n')) {
// zbr:selfhost/Lexer.zbr:976
                const ln: i64 = self.line;
// zbr:selfhost/Lexer.zbr:977
                const cl: i64 = self.col();
// zbr:selfhost/Lexer.zbr:978
                self.advanceNewline();
// zbr:selfhost/Lexer.zbr:979
                if ((((self.parenDepth == 0) or self.afterLambdaParams) or _zebra_gt(@as(i64, @intCast(self.lambdaStack.items.len)), 0))) {
// zbr:selfhost/Lexer.zbr:980
                    self.emit(_zbr_ty_TokenKind{ .eol = {} }, "\n", ln, cl);
// zbr:selfhost/Lexer.zbr:981
                    if (self.afterLambdaParams) {
// zbr:selfhost/Lexer.zbr:982
                        self.afterLambdaParams = false;
// zbr:selfhost/Lexer.zbr:983
                        self.lambdaStack.append(_zbr_rt._allocator, self.indentDepth) catch @panic("OOM");
                    }
                }
// zbr:selfhost/Lexer.zbr:984
                atLineStart = true;
                continue;
            }
// zbr:selfhost/Lexer.zbr:987
            if ((c == '#')) {
// zbr:selfhost/Lexer.zbr:988
                while ((_zebra_lt(self.pos, @as(i64, @intCast(self.src.len))) and (_zbr_at(self.src, self.pos) != '\n'))) {
// zbr:selfhost/Lexer.zbr:989
                    self.pos = (self.pos + 1);
                }
                continue;
            }
// zbr:selfhost/Lexer.zbr:992
            if (((c == '/') and (self.peek1() == '#'))) {
// zbr:selfhost/Lexer.zbr:993
                (try self.scanBlockComment());
                continue;
            }
// zbr:selfhost/Lexer.zbr:996
            (try self.scanToken());
        }
// zbr:selfhost/Lexer.zbr:998
        if ((!atLineStart)) {
// zbr:selfhost/Lexer.zbr:999
            self.emit(_zbr_ty_TokenKind{ .eol = {} }, "", self.line, self.col());
        }
// zbr:selfhost/Lexer.zbr:1001
        const eofCol: i64 = self.col();
// zbr:selfhost/Lexer.zbr:1002
        const eofLn: i64 = self.line;
// zbr:selfhost/Lexer.zbr:1003
        while (_zebra_gt(self.indentDepth, 0)) {
// zbr:selfhost/Lexer.zbr:1004
            self.emit(_zbr_ty_TokenKind{ .dedent = {} }, "", eofLn, eofCol);
// zbr:selfhost/Lexer.zbr:1005
            self.indentDepth = (self.indentDepth - 1);
        }
// zbr:selfhost/Lexer.zbr:1006
        self.emit(_zbr_ty_TokenKind{ .eof = {} }, "", eofLn, eofCol);
    }

};
const _ttag_Lexer: u64 = _zbr_hash("Lexer");
const _reflect_Lexer_name: []const u8 = "Lexer";
const _reflect_Lexer_fields: []const []const u8 = &.{"src", "pos", "line", "lineStart", "indentDepth", "blockDepth", "parenDepth", "out", "inLambdaParams", "lambdaParamDepth", "afterLambdaParams", "lambdaStack", "afterEnsureEol", "ensureBaseDepth"};
const _reflect_Lexer_field_types: []const []const u8 = &.{"str", "int", "int", "int", "int", "int", "int", "List(Token.Token)", "bool", "int", "bool", "List(int)", "bool", "int"};

const _ReflectStrSlice = struct { items: []const []const u8, fn count(self: @This()) i64 { return @intCast(self.items.len); } fn at(self: @This(), i: i64) []const u8 { return self.items[@intCast(i)]; } };
fn _reflect_lookup_name(tag: u64) []const u8 {
    if (tag == _ttag_Lexer) return _reflect_Lexer_name;
    return "unknown";
}
fn _reflect_lookup_fields(tag: u64) _ReflectStrSlice {
    if (tag == _ttag_Lexer) return .{ .items = _reflect_Lexer_fields };
    return .{ .items = &.{} };
}
fn _reflect_lookup_field_types(tag: u64) _ReflectStrSlice {
    if (tag == _ttag_Lexer) return .{ .items = _reflect_Lexer_field_types };
    return .{ .items = &.{} };
}
var _module_vars_inited: bool = false;
pub fn _initModuleVars() void {
    if (_module_vars_inited) return;
    _module_vars_inited = true;
}
