// Generated by zebra-selfhost.
// Source: selfhost/Resolver.zbr

const std     = @import("std");
const builtin = @import("builtin");
const _zbr_rt = @import("zebra_rt.zig");
pub const panic = std.debug.FullPanic(_zbr_rt._zebra_panic);
pub const std_options = _zbr_rt.std_options;
const _prog_alloc = _zbr_rt._prog_alloc;
const _zbr_val = _zbr_rt._zbr_val;
const _intern = _zbr_rt._intern;
const _zbr_at = _zbr_rt._zbr_at;
const _zebra_lt = _zbr_rt._zebra_lt;
const _zebra_gt = _zbr_rt._zebra_gt;
const _zebra_ge = _zbr_rt._zebra_ge;
const _str_concat = _zbr_rt._str_concat;
const _zbr_hash = _zbr_rt._zbr_hash;
const _ZbrList = _zbr_rt._ZbrList;
const _ZbrMap = _zbr_rt._ZbrMap;
const _zbr_new = _zbr_rt._zbr_new;
const _zbr_print = _zbr_rt._zbr_print;

const _zbr_mod_Parser = @import("Parser.zig");
const _zbr_ty_PNode = _zbr_mod_Parser._zbr_ty_PNode;
const _zbr_ty_PParam = _zbr_mod_Parser._zbr_ty_PParam;
const _zbr_ty_POptChain = _zbr_mod_Parser._zbr_ty_POptChain;
const _zbr_ty_PIfExpr = _zbr_mod_Parser._zbr_ty_PIfExpr;
const _zbr_mod_CgHelpers = @import("CgHelpers.zig");
const _zbr_fn_isStdlibNs = _zbr_mod_CgHelpers._zbr_fn_isStdlibNs;
const _zbr_fn_isBuiltinTypeName = _zbr_mod_CgHelpers._zbr_fn_isBuiltinTypeName;
pub const _zbr_ty_ResolveError = struct {
    message: []const u8 = undefined,
    pub fn init(message: []const u8) _zbr_ty_ResolveError {
        var _self: _zbr_ty_ResolveError = undefined;
// zbr:selfhost/Resolver.zbr:41
            _self.message = _intern(message);
        return _self;
    }

};

pub const _zbr_ty_Resolver = struct {
    _type_tag: u64 = _ttag_Resolver,
    module_scope: _ZbrMap(i64) = undefined,
    class_scope: _ZbrMap(i64) = undefined,
    method_scope: _ZbrMap(i64) = undefined,
    errors: _ZbrList(_zbr_ty_ResolveError) = undefined,
    symbol_count: i64 = undefined,
    file_name: []const u8 = undefined,
    source: []const u8 = undefined,
    pub fn init(file_name: []const u8, source: []const u8) *_zbr_ty_Resolver {
        const _self = _zbr_rt._allocator.create(_zbr_ty_Resolver) catch @panic("OOM");
        _self._type_tag = _zbr_hash("Resolver");
// zbr:selfhost/Resolver.zbr:61
            _self.module_scope = _zbr_new(_ZbrMap(i64));
// zbr:selfhost/Resolver.zbr:62
            _self.class_scope = _zbr_new(_ZbrMap(i64));
// zbr:selfhost/Resolver.zbr:63
            _self.method_scope = _zbr_new(_ZbrMap(i64));
// zbr:selfhost/Resolver.zbr:64
            _self.errors = _zbr_new(_ZbrList(_zbr_ty_ResolveError));
// zbr:selfhost/Resolver.zbr:65
            _self.symbol_count = 0;
// zbr:selfhost/Resolver.zbr:66
            _self.file_name = _intern(file_name);
// zbr:selfhost/Resolver.zbr:67
            _self.source = _intern(source);
        return _self;
    }

    // zbr:selfhost/Resolver.zbr:71
    pub fn fmtErrAt(self: *_zbr_ty_Resolver, line: i64, col: i64, msg: []const u8) []const u8 {
// zbr:selfhost/Resolver.zbr:72
        const head: []const u8 = _str_concat(_str_concat(_str_concat(_str_concat(_str_concat(_str_concat(self.file_name, ":", _zbr_rt._allocator), (std.fmt.allocPrint(_zbr_rt._allocator, "{}", .{line}) catch @panic("OOM")), _zbr_rt._allocator), ":", _zbr_rt._allocator), (std.fmt.allocPrint(_zbr_rt._allocator, "{}", .{col}) catch @panic("OOM")), _zbr_rt._allocator), ": error: ", _zbr_rt._allocator), msg, _zbr_rt._allocator);
// zbr:selfhost/Resolver.zbr:73
        const src_line: []const u8 = self.sourceLine((line - 1));
// zbr:selfhost/Resolver.zbr:74
        if (_zebra_gt(@as(i64, @intCast(src_line.len)), 0)) {
// zbr:selfhost/Resolver.zbr:75
            var caret = _zbr_new(_ZbrList(u8));
// zbr:selfhost/Resolver.zbr:76
            var c: i64 = 1;
// zbr:selfhost/Resolver.zbr:77
            while (_zebra_lt(c, col)) {
// zbr:selfhost/Resolver.zbr:78
                caret.appendSlice(_zbr_rt._allocator, " ") catch @panic("OOM");
// zbr:selfhost/Resolver.zbr:79
                c = (c + 1);
            }
// zbr:selfhost/Resolver.zbr:80
            caret.appendSlice(_zbr_rt._allocator, "^") catch @panic("OOM");
// zbr:selfhost/Resolver.zbr:81
            return _str_concat(_str_concat(_str_concat(_str_concat(head, "\n", _zbr_rt._allocator), src_line, _zbr_rt._allocator), "\n", _zbr_rt._allocator), (_zbr_rt._allocator.dupe(u8, caret.items) catch ""), _zbr_rt._allocator);
        }
// zbr:selfhost/Resolver.zbr:82
        return head;
    }

    // zbr:selfhost/Resolver.zbr:85
    pub fn sourceLine(self: *_zbr_ty_Resolver, li: i64) []const u8 {
// zbr:selfhost/Resolver.zbr:86
        if (((@as(i64, @intCast(self.source.len)) == 0) or _zebra_lt(li, 0))) {
// zbr:selfhost/Resolver.zbr:87
            return "";
        }
// zbr:selfhost/Resolver.zbr:88
        var idx: i64 = 0;
// zbr:selfhost/Resolver.zbr:89
        {
            var _it_ln = std.mem.splitSequence(u8, self.source, "\n");
            while (_it_ln.next()) |ln| {
// zbr:selfhost/Resolver.zbr:90
                if ((idx == li)) {
// zbr:selfhost/Resolver.zbr:91
                    return ln;
                }
// zbr:selfhost/Resolver.zbr:92
                idx = (idx + 1);
            }
        }
// zbr:selfhost/Resolver.zbr:93
        return "";
    }

    // zbr:selfhost/Resolver.zbr:97
    pub fn errorCount(self: *const _zbr_ty_Resolver) i64 {
// zbr:selfhost/Resolver.zbr:98
        return @as(i64, @intCast(self.errors.items.len));
    }

    // zbr:selfhost/Resolver.zbr:100
    pub fn symbolCount(self: *const _zbr_ty_Resolver) i64 {
// zbr:selfhost/Resolver.zbr:101
        return self.symbol_count;
    }

    // zbr:selfhost/Resolver.zbr:103
    pub fn firstError(self: *_zbr_ty_Resolver) []const u8 {
// zbr:selfhost/Resolver.zbr:104
        if (_zebra_gt(@as(i64, @intCast(self.errors.items.len)), 0)) {
// zbr:selfhost/Resolver.zbr:105
            return _zbr_at(self.errors.items, 0).message;
        }
// zbr:selfhost/Resolver.zbr:106
        return "";
    }

    // zbr:selfhost/Resolver.zbr:108
    pub fn allErrorMessages(self: *_zbr_ty_Resolver) []const u8 {
// zbr:selfhost/Resolver.zbr:109
        var b = _zbr_new(_ZbrList(u8));
// zbr:selfhost/Resolver.zbr:110
        for (self.errors.items) |e| {
// zbr:selfhost/Resolver.zbr:111
            b.appendSlice(_zbr_rt._allocator, e.message) catch @panic("OOM");
// zbr:selfhost/Resolver.zbr:112
            b.appendSlice(_zbr_rt._allocator, "\n") catch @panic("OOM");
        }
// zbr:selfhost/Resolver.zbr:113
        return (_zbr_rt._allocator.dupe(u8, b.items) catch "");
    }

    // zbr:selfhost/Resolver.zbr:117
    pub fn resolve(self: *_zbr_ty_Resolver, root: _zbr_ty_PNode) anyerror!void {
// zbr:selfhost/Resolver.zbr:118
        (try self.bindPass1(root));
// zbr:selfhost/Resolver.zbr:119
        (try self.resolvePass2(root));
    }

    // zbr:selfhost/Resolver.zbr:123
    pub fn bindPass1(self: *_zbr_ty_Resolver, root: _zbr_ty_PNode) anyerror!void {
// zbr:selfhost/Resolver.zbr:124
        if (_zbr_val(root) == .module_) {
            const m_ptr = root.module_;
            const m = m_ptr.*;
// zbr:selfhost/Resolver.zbr:125
            for (m.decls.items) |decl| {
// zbr:selfhost/Resolver.zbr:126
                (try self.bindTopDecl(decl));
            }
        }
    }

    // zbr:selfhost/Resolver.zbr:127
    pub fn bindTopDecl(self: *_zbr_ty_Resolver, decl: _zbr_ty_PNode) anyerror!void {
// zbr:selfhost/Resolver.zbr:128
        switch (_zbr_val(decl)) {
            .class_ => |_ptr_c| {
                const c = _ptr_c.*;
// zbr:selfhost/Resolver.zbr:130
                self.module_scope.put(_intern(c.name), 0) catch @panic("OOM");
// zbr:selfhost/Resolver.zbr:131
                self.symbol_count = (self.symbol_count + 1);
            },
            .struct_ => |_ptr_s| {
                const s = _ptr_s.*;
// zbr:selfhost/Resolver.zbr:133
                self.module_scope.put(_intern(s.name), 0) catch @panic("OOM");
// zbr:selfhost/Resolver.zbr:134
                self.symbol_count = (self.symbol_count + 1);
            },
            .union_decl => |_ptr_u| {
                const u = _ptr_u.*;
// zbr:selfhost/Resolver.zbr:136
                self.module_scope.put(_intern(u.name), 0) catch @panic("OOM");
// zbr:selfhost/Resolver.zbr:137
                self.symbol_count = (self.symbol_count + 1);
            },
            .enum_ => |_ptr_e| {
                const e = _ptr_e.*;
// zbr:selfhost/Resolver.zbr:139
                self.module_scope.put(_intern(e.name), 0) catch @panic("OOM");
// zbr:selfhost/Resolver.zbr:140
                self.symbol_count = (self.symbol_count + 1);
            },
            .sig_ => |_ptr_sg| {
                const sg = _ptr_sg.*;
// zbr:selfhost/Resolver.zbr:142
                self.module_scope.put(_intern(sg.name), 0) catch @panic("OOM");
// zbr:selfhost/Resolver.zbr:143
                self.symbol_count = (self.symbol_count + 1);
            },
            .interface_ => |_ptr_i| {
                const i = _ptr_i.*;
// zbr:selfhost/Resolver.zbr:147
                self.module_scope.put(_intern(i.name), 0) catch @panic("OOM");
// zbr:selfhost/Resolver.zbr:148
                self.symbol_count = (self.symbol_count + 1);
            },
            .method_ => |_ptr_m| {
                const m = _ptr_m.*;
// zbr:selfhost/Resolver.zbr:150
                self.module_scope.put(_intern(m.name), 1) catch @panic("OOM");
// zbr:selfhost/Resolver.zbr:151
                self.symbol_count = (self.symbol_count + 1);
            },
            .stmt_var => |_ptr_v| {
                const v = _ptr_v.*;
// zbr:selfhost/Resolver.zbr:156
                self.module_scope.put(_intern(v.name), 0) catch @panic("OOM");
// zbr:selfhost/Resolver.zbr:157
                self.symbol_count = (self.symbol_count + 1);
            },
            .use_ => |_ptr_u| {
                const u = _ptr_u.*;
// zbr:selfhost/Resolver.zbr:159
                self.module_scope.put(_intern(u.path), 5) catch @panic("OOM");
// zbr:selfhost/Resolver.zbr:160
                for (u.exposed.items) |name| {
// zbr:selfhost/Resolver.zbr:161
                    self.module_scope.put(_intern(name), 5) catch @panic("OOM");
                }
            },
            .namespace_decl => |_ptr_ns| {
                const ns = _ptr_ns.*;
// zbr:selfhost/Resolver.zbr:164
                const ns_root_parts: _ZbrList([]const u8) = blk092_1: { var _ll_1: _ZbrList([]const u8) = _zbr_new(_ZbrList([]const u8)); var _split_iter_1 = std.mem.splitSequence(u8, ns.name, "."); while (_split_iter_1.next()) |_se_1| { _ll_1.append(_zbr_rt._allocator, _se_1) catch @panic("OOM"); } break :blk092_1 _ll_1; };
// zbr:selfhost/Resolver.zbr:165
                self.module_scope.put(_intern(_zbr_at(ns_root_parts.items, 0)), 0) catch @panic("OOM");
// zbr:selfhost/Resolver.zbr:166
                self.symbol_count = (self.symbol_count + 1);
            },
            else => {
                // pass
            },
        }
    }

    // zbr:selfhost/Resolver.zbr:172
    pub fn resolvePass2(self: *_zbr_ty_Resolver, root: _zbr_ty_PNode) anyerror!void {
// zbr:selfhost/Resolver.zbr:173
        if (_zbr_val(root) == .module_) {
            const m_ptr = root.module_;
            const m = m_ptr.*;
// zbr:selfhost/Resolver.zbr:174
            for (m.decls.items) |decl| {
// zbr:selfhost/Resolver.zbr:175
                (try self.resolveTopDecl(decl));
            }
        }
    }

    // zbr:selfhost/Resolver.zbr:176
    pub fn resolveTopDecl(self: *_zbr_ty_Resolver, decl: _zbr_ty_PNode) anyerror!void {
// zbr:selfhost/Resolver.zbr:177
        switch (_zbr_val(decl)) {
            .class_ => |_ptr_c| {
                const c = _ptr_c.*;
// zbr:selfhost/Resolver.zbr:179
                (try self.enterClass(c.name, c.members, c.type_params));
            },
            .struct_ => |_ptr_s| {
                const s = _ptr_s.*;
// zbr:selfhost/Resolver.zbr:181
                (try self.enterClass(s.name, s.members, s.type_params));
            },
            .method_ => |_ptr_m| {
                const m = _ptr_m.*;
// zbr:selfhost/Resolver.zbr:183
                (try self.enterMethod(m.params, m.stmts));
            },
            .stmt_var => |_ptr_mv| {
                const mv = _ptr_mv.*;
// zbr:selfhost/Resolver.zbr:187
                self.class_scope = _zbr_new(_ZbrMap(i64));
// zbr:selfhost/Resolver.zbr:188
                self.method_scope = _zbr_new(_ZbrMap(i64));
// zbr:selfhost/Resolver.zbr:189
                for (mv.init_expr.items) |mve| {
// zbr:selfhost/Resolver.zbr:190
                    (try self.resolveExpr(mve));
                }
            },
            .namespace_decl => |_ptr_ns| {
                const ns = _ptr_ns.*;
// zbr:selfhost/Resolver.zbr:193
                for (ns.decls.items) |ns_d| {
// zbr:selfhost/Resolver.zbr:194
                    switch (_zbr_val(ns_d)) {
                        .method_ => |_ptr_nm| {
                            const nm = _ptr_nm.*;
// zbr:selfhost/Resolver.zbr:196
                            (try self.enterMethod(nm.params, nm.stmts));
                        },
                        .namespace_decl => |_ptr_inner_ns| {
                            const inner_ns = _ptr_inner_ns.*;
// zbr:selfhost/Resolver.zbr:198
                            for (inner_ns.decls.items) |inner_d| {
// zbr:selfhost/Resolver.zbr:199
                                if (_zbr_val(inner_d) == .method_) {
                                    const im_ptr = inner_d.method_;
                                    const im = im_ptr.*;
// zbr:selfhost/Resolver.zbr:200
                                    (try self.enterMethod(im.params, im.stmts));
                                }
                            }
                        },
                        else => {
                            // pass
                        },
                    }
                }
            },
            else => {
                // pass
            },
        }
    }

    // zbr:selfhost/Resolver.zbr:209
    pub fn enterClass(self: *_zbr_ty_Resolver, name: []const u8, members: _ZbrList(_zbr_ty_PNode), type_params: _ZbrList([]const u8)) anyerror!void {
        _ = name;
// zbr:selfhost/Resolver.zbr:210
        self.class_scope = _zbr_new(_ZbrMap(i64));
// zbr:selfhost/Resolver.zbr:215
        for (type_params.items) |tp| {
// zbr:selfhost/Resolver.zbr:216
            var tp_name: []const u8 = tp;
// zbr:selfhost/Resolver.zbr:217
            const bar: i64 = (if (std.mem.indexOf(u8, tp, "|")) |_i| @as(i64, @intCast(_i)) else @as(i64, -1));
// zbr:selfhost/Resolver.zbr:218
            if (_zebra_ge(bar, 0)) {
// zbr:selfhost/Resolver.zbr:219
                tp_name = tp[@intCast(0)..@intCast(bar)];
            }
// zbr:selfhost/Resolver.zbr:220
            self.class_scope.put(_intern(tp_name), 6) catch @panic("OOM");
// zbr:selfhost/Resolver.zbr:221
            self.symbol_count = (self.symbol_count + 1);
        }
// zbr:selfhost/Resolver.zbr:223
        for (members.items) |member| {
// zbr:selfhost/Resolver.zbr:224
            (try self.collectMember(member));
        }
// zbr:selfhost/Resolver.zbr:226
        for (members.items) |member| {
// zbr:selfhost/Resolver.zbr:227
            (try self.resolveMember(member));
        }
    }

    // zbr:selfhost/Resolver.zbr:229
    pub fn collectMember(self: *_zbr_ty_Resolver, member: _zbr_ty_PNode) anyerror!void {
// zbr:selfhost/Resolver.zbr:230
        switch (_zbr_val(member)) {
            .method_ => |_ptr_m| {
                const m = _ptr_m.*;
// zbr:selfhost/Resolver.zbr:232
                self.class_scope.put(_intern(m.name), 1) catch @panic("OOM");
// zbr:selfhost/Resolver.zbr:233
                self.symbol_count = (self.symbol_count + 1);
            },
            .field_ => |_ptr_f| {
                const f = _ptr_f.*;
// zbr:selfhost/Resolver.zbr:235
                self.class_scope.put(_intern(f.name), 2) catch @panic("OOM");
// zbr:selfhost/Resolver.zbr:236
                self.symbol_count = (self.symbol_count + 1);
            },
            else => {
                // pass
            },
        }
    }

    // zbr:selfhost/Resolver.zbr:240
    pub fn resolveMember(self: *_zbr_ty_Resolver, member: _zbr_ty_PNode) anyerror!void {
// zbr:selfhost/Resolver.zbr:241
        switch (_zbr_val(member)) {
            .method_ => |_ptr_m| {
                const m = _ptr_m.*;
// zbr:selfhost/Resolver.zbr:243
                (try self.enterMethod(m.params, m.stmts));
            },
            .init_ => |_ptr_i| {
                const i = _ptr_i.*;
// zbr:selfhost/Resolver.zbr:245
                (try self.enterMethod(i.params, i.stmts));
            },
            else => {
                // pass
            },
        }
    }

    // zbr:selfhost/Resolver.zbr:250
    pub fn enterMethod(self: *_zbr_ty_Resolver, params: _ZbrList(_zbr_ty_PParam), stmts: _ZbrList(_zbr_ty_PNode)) anyerror!void {
// zbr:selfhost/Resolver.zbr:251
        self.method_scope = _zbr_new(_ZbrMap(i64));
// zbr:selfhost/Resolver.zbr:252
        for (params.items) |p| {
// zbr:selfhost/Resolver.zbr:253
            self.method_scope.put(_intern(p.name), 3) catch @panic("OOM");
// zbr:selfhost/Resolver.zbr:254
            self.symbol_count = (self.symbol_count + 1);
        }
// zbr:selfhost/Resolver.zbr:255
        (try self.resolveStmts(stmts));
    }

    // zbr:selfhost/Resolver.zbr:259
    pub fn resolveStmts(self: *_zbr_ty_Resolver, stmts: _ZbrList(_zbr_ty_PNode)) anyerror!void {
// zbr:selfhost/Resolver.zbr:260
        for (stmts.items) |stmt| {
// zbr:selfhost/Resolver.zbr:261
            (try self.resolveStmt(stmt));
        }
    }

    // zbr:selfhost/Resolver.zbr:263
    pub fn resolveStmt(self: *_zbr_ty_Resolver, stmt: _zbr_ty_PNode) anyerror!void {
// zbr:selfhost/Resolver.zbr:264
        switch (_zbr_val(stmt)) {
            .stmt_var => |_ptr_v| {
                const v = _ptr_v.*;
// zbr:selfhost/Resolver.zbr:267
                for (v.init_expr.items) |expr| {
// zbr:selfhost/Resolver.zbr:268
                    (try self.resolveExpr(expr));
                }
// zbr:selfhost/Resolver.zbr:269
                self.method_scope.put(_intern(v.name), 4) catch @panic("OOM");
// zbr:selfhost/Resolver.zbr:270
                self.symbol_count = (self.symbol_count + 1);
            },
            .stmt_destruct => |_ptr_d| {
                const d = _ptr_d.*;
// zbr:selfhost/Resolver.zbr:272
                for (d.init_expr.items) |expr| {
// zbr:selfhost/Resolver.zbr:273
                    (try self.resolveExpr(expr));
                }
// zbr:selfhost/Resolver.zbr:274
                for (d.names.items) |nm| {
// zbr:selfhost/Resolver.zbr:275
                    self.method_scope.put(_intern(nm), 4) catch @panic("OOM");
// zbr:selfhost/Resolver.zbr:276
                    self.symbol_count = (self.symbol_count + 1);
                }
            },
            .stmt_return => |_ptr_r| {
                const r = _ptr_r.*;
// zbr:selfhost/Resolver.zbr:278
                for (r.value.items) |expr| {
// zbr:selfhost/Resolver.zbr:279
                    (try self.resolveExpr(expr));
                }
            },
            .stmt_yield => |_ptr_y| {
                const y = _ptr_y.*;
// zbr:selfhost/Resolver.zbr:281
                for (y.value.items) |expr| {
// zbr:selfhost/Resolver.zbr:282
                    (try self.resolveExpr(expr));
                }
            },
            .stmt_if => |_ptr_i| {
                const i = _ptr_i.*;
// zbr:selfhost/Resolver.zbr:284
                for (i.cond.items) |expr| {
// zbr:selfhost/Resolver.zbr:285
                    (try self.resolveExpr(expr));
                }
// zbr:selfhost/Resolver.zbr:286
                if (i.is_capture) |ic| {
// zbr:selfhost/Resolver.zbr:287
                    self.method_scope.put(_intern(ic), 4) catch @panic("OOM");
// zbr:selfhost/Resolver.zbr:288
                    self.symbol_count = (self.symbol_count + 1);
                }
// zbr:selfhost/Resolver.zbr:289
                (try self.resolveStmts(i.then_stmts));
// zbr:selfhost/Resolver.zbr:290
                (try self.resolveStmts(i.else_stmts));
            },
            .stmt_while => |_ptr_w| {
                const w = _ptr_w.*;
// zbr:selfhost/Resolver.zbr:292
                for (w.cond.items) |expr| {
// zbr:selfhost/Resolver.zbr:293
                    (try self.resolveExpr(expr));
                }
// zbr:selfhost/Resolver.zbr:294
                (try self.resolveStmts(w.stmts));
            },
            .stmt_for_in => |_ptr_f| {
                const f = _ptr_f.*;
// zbr:selfhost/Resolver.zbr:296
                for (f.iter.items) |expr| {
// zbr:selfhost/Resolver.zbr:297
                    (try self.resolveExpr(expr));
                }
// zbr:selfhost/Resolver.zbr:298
                for (f.var_names.items) |var_name| {
// zbr:selfhost/Resolver.zbr:299
                    self.method_scope.put(_intern(var_name), 4) catch @panic("OOM");
                }
// zbr:selfhost/Resolver.zbr:300
                (try self.resolveStmts(f.stmts));
// zbr:selfhost/Resolver.zbr:301
                (try self.resolveStmts(f.else_stmts));
            },
            .stmt_assign => |_ptr_a| {
                const a = _ptr_a.*;
// zbr:selfhost/Resolver.zbr:303
                for (a.target.items) |expr| {
// zbr:selfhost/Resolver.zbr:304
                    (try self.resolveExpr(expr));
                }
// zbr:selfhost/Resolver.zbr:305
                for (a.value.items) |expr| {
// zbr:selfhost/Resolver.zbr:306
                    (try self.resolveExpr(expr));
                }
            },
            .stmt_assert => |_ptr_a| {
                const a = _ptr_a.*;
// zbr:selfhost/Resolver.zbr:308
                for (a.cond.items) |expr| {
// zbr:selfhost/Resolver.zbr:309
                    (try self.resolveExpr(expr));
                }
// zbr:selfhost/Resolver.zbr:310
                for (a.message.items) |expr| {
// zbr:selfhost/Resolver.zbr:311
                    (try self.resolveExpr(expr));
                }
            },
            .stmt_raise => |_ptr_r| {
                const r = _ptr_r.*;
// zbr:selfhost/Resolver.zbr:313
                for (r.message.items) |expr| {
// zbr:selfhost/Resolver.zbr:314
                    (try self.resolveExpr(expr));
                }
            },
            .stmt_try_catch => |_ptr_tc| {
                const tc = _ptr_tc.*;
// zbr:selfhost/Resolver.zbr:316
                (try self.resolveStmts(tc.body_stmts));
// zbr:selfhost/Resolver.zbr:317
                if (!std.mem.eql(u8, tc.catch_binding, "")) {
// zbr:selfhost/Resolver.zbr:318
                    self.method_scope.put(_intern(tc.catch_binding), 4) catch @panic("OOM");
                }
// zbr:selfhost/Resolver.zbr:319
                (try self.resolveStmts(tc.catch_stmts));
            },
            .stmt_branch => |_ptr_br| {
                const br = _ptr_br.*;
// zbr:selfhost/Resolver.zbr:321
                for (br.subject.items) |expr| {
// zbr:selfhost/Resolver.zbr:322
                    (try self.resolveExpr(expr));
                }
// zbr:selfhost/Resolver.zbr:323
                for (br.arms.items) |arm| {
// zbr:selfhost/Resolver.zbr:324
                    if (!std.mem.eql(u8, arm.binding, "")) {
// zbr:selfhost/Resolver.zbr:325
                        self.method_scope.put(_intern(arm.binding), 4) catch @panic("OOM");
                    }
// zbr:selfhost/Resolver.zbr:326
                    (try self.resolveStmts(arm.stmts));
                }
// zbr:selfhost/Resolver.zbr:327
                (try self.resolveStmts(br.else_stmts));
            },
            .stmt_expr => |_ptr_inner| {
                const inner = _ptr_inner.*;
// zbr:selfhost/Resolver.zbr:329
                (try self.resolveExpr(inner));
            },
            .stmt_print => |arg_nodes| {
// zbr:selfhost/Resolver.zbr:331
                const arg_list: _ZbrList(_zbr_ty_PNode) = arg_nodes;
// zbr:selfhost/Resolver.zbr:332
                for (arg_list.items) |an| {
// zbr:selfhost/Resolver.zbr:333
                    (try self.resolveExpr(an));
                }
            },
            .stmt_pass => {
                // pass
            },
            .stmt_break => {
                // pass
            },
            .stmt_continue => {
                // pass
            },
            else => {
                // pass
            },
        }
    }

    // zbr:selfhost/Resolver.zbr:345
    pub fn resolveExpr(self: *_zbr_ty_Resolver, expr: _zbr_ty_PNode) anyerror!void {
// zbr:selfhost/Resolver.zbr:346
        switch (_zbr_val(expr)) {
            .expr_id => |_ptr_id| {
                const id = _ptr_id.*;
// zbr:selfhost/Resolver.zbr:348
                if ((!self.isInScope(id.name))) {
// zbr:selfhost/Resolver.zbr:349
                    self.errors.append(_zbr_rt._allocator, _zbr_ty_ResolveError.init(self.fmtErrAt(id.line, id.col, _str_concat(_str_concat("undefined name: '", id.name, _zbr_rt._allocator), "'", _zbr_rt._allocator)))) catch @panic("OOM");
                }
            },
            .expr_binary => |_ptr_b| {
                const b = _ptr_b.*;
// zbr:selfhost/Resolver.zbr:351
                for (b.left.items) |e| {
// zbr:selfhost/Resolver.zbr:352
                    (try self.resolveExpr(e));
                }
// zbr:selfhost/Resolver.zbr:353
                for (b.right.items) |e| {
// zbr:selfhost/Resolver.zbr:354
                    (try self.resolveExpr(e));
                }
            },
            .expr_unary => |_ptr_u| {
                const u = _ptr_u.*;
// zbr:selfhost/Resolver.zbr:356
                for (u.operand.items) |e| {
// zbr:selfhost/Resolver.zbr:357
                    (try self.resolveExpr(e));
                }
            },
            .expr_call => |_ptr_c| {
                const c = _ptr_c.*;
// zbr:selfhost/Resolver.zbr:359
                for (c.callee.items) |e| {
// zbr:selfhost/Resolver.zbr:360
                    (try self.resolveExpr(e));
                }
// zbr:selfhost/Resolver.zbr:364
                var generic_ctor: bool = false;
// zbr:selfhost/Resolver.zbr:365
                for (c.callee.items) |ce| {
// zbr:selfhost/Resolver.zbr:366
                    if (_zbr_val(ce) == .expr_id) {
                        const cid_ptr = ce.expr_id;
                        const cid = cid_ptr.*;
// zbr:selfhost/Resolver.zbr:367
                        if ((((((std.mem.eql(u8, cid.name, "List") or std.mem.eql(u8, cid.name, "HashMap")) or std.mem.eql(u8, cid.name, "Set")) or std.mem.eql(u8, cid.name, "Atomic")) or std.mem.eql(u8, cid.name, "Chan")) or std.mem.eql(u8, cid.name, "ObjectPool"))) {
// zbr:selfhost/Resolver.zbr:368
                            generic_ctor = true;
                        }
                    }
                }
// zbr:selfhost/Resolver.zbr:369
                for (c.args.items) |e| {
// zbr:selfhost/Resolver.zbr:370
                    var skip_e: bool = false;
// zbr:selfhost/Resolver.zbr:371
                    if (generic_ctor) {
// zbr:selfhost/Resolver.zbr:372
                        if (_zbr_val(e) == .expr_id) {
                            const aid_ptr = e.expr_id;
                            const aid = aid_ptr.*;
// zbr:selfhost/Resolver.zbr:373
                            if (_zbr_fn_isBuiltinTypeName(aid.name)) {
// zbr:selfhost/Resolver.zbr:374
                                skip_e = true;
                            }
                        }
                    }
// zbr:selfhost/Resolver.zbr:375
                    if ((!skip_e)) {
// zbr:selfhost/Resolver.zbr:376
                        (try self.resolveExpr(e));
                    }
                }
            },
            .expr_index => |_ptr_ix| {
                const ix = _ptr_ix.*;
// zbr:selfhost/Resolver.zbr:378
                for (ix.object.items) |e| {
// zbr:selfhost/Resolver.zbr:379
                    (try self.resolveExpr(e));
                }
// zbr:selfhost/Resolver.zbr:380
                for (ix.index.items) |e| {
// zbr:selfhost/Resolver.zbr:381
                    (try self.resolveExpr(e));
                }
            },
            .expr_slice => |_ptr_sl| {
                const sl = _ptr_sl.*;
// zbr:selfhost/Resolver.zbr:383
                for (sl.object.items) |e| {
// zbr:selfhost/Resolver.zbr:384
                    (try self.resolveExpr(e));
                }
// zbr:selfhost/Resolver.zbr:385
                for (sl.start.items) |e| {
// zbr:selfhost/Resolver.zbr:386
                    (try self.resolveExpr(e));
                }
// zbr:selfhost/Resolver.zbr:387
                for (sl.stop_.items) |e| {
// zbr:selfhost/Resolver.zbr:388
                    (try self.resolveExpr(e));
                }
            },
            .expr_member => |_ptr_m| {
                const m = _ptr_m.*;
// zbr:selfhost/Resolver.zbr:390
                for (m.base.items) |e| {
// zbr:selfhost/Resolver.zbr:391
                    (try self.resolveExpr(e));
                }
            },
            .expr_try => {
                // pass
            },
            .expr_to_bang => {
                // pass
            },
            .expr_except => |_ptr_ex| {
                const ex = _ptr_ex.*;
// zbr:selfhost/Resolver.zbr:400
                for (ex.base.items) |e| {
// zbr:selfhost/Resolver.zbr:401
                    (try self.resolveExpr(e));
                }
// zbr:selfhost/Resolver.zbr:402
                for (ex.fields.items) |f| {
// zbr:selfhost/Resolver.zbr:403
                    for (f.value.items) |v| {
// zbr:selfhost/Resolver.zbr:404
                        (try self.resolveExpr(v));
                    }
                }
            },
            .expr_string_interp => |_ptr_si| {
                const si = _ptr_si.*;
// zbr:selfhost/Resolver.zbr:406
                for (si.parts.items) |part| {
// zbr:selfhost/Resolver.zbr:407
                    (try self.resolveExpr(part));
                }
            },
            .expr_opt_chain => |_ptr_poc| {
                const poc = _ptr_poc.*;
// zbr:selfhost/Resolver.zbr:409
                for (poc.base.items) |e| {
// zbr:selfhost/Resolver.zbr:410
                    (try self.resolveExpr(e));
                }
// zbr:selfhost/Resolver.zbr:411
                for (poc.args.items) |e| {
// zbr:selfhost/Resolver.zbr:412
                    (try self.resolveExpr(e));
                }
            },
            .expr_if_expr => |_ptr_pie| {
                const pie = _ptr_pie.*;
// zbr:selfhost/Resolver.zbr:414
                for (pie.cond.items) |e| {
// zbr:selfhost/Resolver.zbr:415
                    (try self.resolveExpr(e));
                }
// zbr:selfhost/Resolver.zbr:416
                for (pie.then_expr.items) |e| {
// zbr:selfhost/Resolver.zbr:417
                    (try self.resolveExpr(e));
                }
// zbr:selfhost/Resolver.zbr:418
                for (pie.else_expr.items) |e| {
// zbr:selfhost/Resolver.zbr:419
                    (try self.resolveExpr(e));
                }
            },
            else => {
                // pass
            },
        }
    }

    // zbr:selfhost/Resolver.zbr:426
    pub fn isInScope(self: *_zbr_ty_Resolver, name: []const u8) bool {
// zbr:selfhost/Resolver.zbr:427
        if (self.method_scope.contains(name)) {
// zbr:selfhost/Resolver.zbr:428
            return true;
        }
// zbr:selfhost/Resolver.zbr:429
        if (self.class_scope.contains(name)) {
// zbr:selfhost/Resolver.zbr:430
            return true;
        }
// zbr:selfhost/Resolver.zbr:431
        if (self.module_scope.contains(name)) {
// zbr:selfhost/Resolver.zbr:432
            return true;
        }
// zbr:selfhost/Resolver.zbr:433
        if (self.isBuiltin(name)) {
// zbr:selfhost/Resolver.zbr:434
            return true;
        }
// zbr:selfhost/Resolver.zbr:435
        return false;
    }

    // zbr:selfhost/Resolver.zbr:437
    pub fn isBuiltin(self: *_zbr_ty_Resolver, name: []const u8) bool {
// zbr:selfhost/Resolver.zbr:439
        if ((((std.mem.eql(u8, name, "int") or std.mem.eql(u8, name, "str")) or std.mem.eql(u8, name, "bool")) or std.mem.eql(u8, name, "float"))) {
// zbr:selfhost/Resolver.zbr:440
            return true;
        }
// zbr:selfhost/Resolver.zbr:445
        if ((std.mem.eql(u8, name, "char") or std.mem.eql(u8, name, "uint"))) {
// zbr:selfhost/Resolver.zbr:446
            return true;
        }
// zbr:selfhost/Resolver.zbr:451
        if ((((std.mem.eql(u8, name, "int8") or std.mem.eql(u8, name, "int16")) or std.mem.eql(u8, name, "int32")) or std.mem.eql(u8, name, "int64"))) {
// zbr:selfhost/Resolver.zbr:452
            return true;
        }
// zbr:selfhost/Resolver.zbr:453
        if ((((std.mem.eql(u8, name, "uint8") or std.mem.eql(u8, name, "uint16")) or std.mem.eql(u8, name, "uint32")) or std.mem.eql(u8, name, "uint64"))) {
// zbr:selfhost/Resolver.zbr:454
            return true;
        }
// zbr:selfhost/Resolver.zbr:455
        if (((std.mem.eql(u8, name, "float16") or std.mem.eql(u8, name, "float32")) or std.mem.eql(u8, name, "float64"))) {
// zbr:selfhost/Resolver.zbr:456
            return true;
        }
// zbr:selfhost/Resolver.zbr:457
        if (((std.mem.eql(u8, name, "f16") or std.mem.eql(u8, name, "f32")) or std.mem.eql(u8, name, "f64"))) {
// zbr:selfhost/Resolver.zbr:458
            return true;
        }
// zbr:selfhost/Resolver.zbr:459
        if (((std.mem.eql(u8, name, "nil") or std.mem.eql(u8, name, "true")) or std.mem.eql(u8, name, "false"))) {
// zbr:selfhost/Resolver.zbr:460
            return true;
        }
// zbr:selfhost/Resolver.zbr:461
        if (((std.mem.eql(u8, name, "this") or std.mem.eql(u8, name, "print")) or std.mem.eql(u8, name, "assert"))) {
// zbr:selfhost/Resolver.zbr:462
            return true;
        }
// zbr:selfhost/Resolver.zbr:464
        if ((((std.mem.eql(u8, name, "List") or std.mem.eql(u8, name, "HashMap")) or std.mem.eql(u8, name, "StringBuilder")) or std.mem.eql(u8, name, "Chan"))) {
// zbr:selfhost/Resolver.zbr:465
            return true;
        }
// zbr:selfhost/Resolver.zbr:466
        if ((((std.mem.eql(u8, name, "Atomic") or std.mem.eql(u8, name, "ThreadPool")) or std.mem.eql(u8, name, "ObjectPool")) or std.mem.eql(u8, name, "Set"))) {
// zbr:selfhost/Resolver.zbr:467
            return true;
        }
// zbr:selfhost/Resolver.zbr:468
        if (std.mem.eql(u8, name, "DynLib")) {
// zbr:selfhost/Resolver.zbr:469
            return true;
        }
// zbr:selfhost/Resolver.zbr:475
        if (_zbr_fn_isStdlibNs(name)) {
// zbr:selfhost/Resolver.zbr:476
            return true;
        }
// zbr:selfhost/Resolver.zbr:480
        if (((std.mem.eql(u8, name, "WsConn") or std.mem.eql(u8, name, "CsvWriter")) or std.mem.eql(u8, name, "Calendar"))) {
// zbr:selfhost/Resolver.zbr:481
            return true;
        }
// zbr:selfhost/Resolver.zbr:486
        if (std.mem.eql(u8, name, "CodeEditor")) {
// zbr:selfhost/Resolver.zbr:487
            return true;
        }
// zbr:selfhost/Resolver.zbr:488
        if (((std.mem.eql(u8, name, "SqliteDb") or std.mem.eql(u8, name, "SqliteRow")) or std.mem.eql(u8, name, "Base64"))) {
// zbr:selfhost/Resolver.zbr:489
            return true;
        }
// zbr:selfhost/Resolver.zbr:490
        if ((std.mem.eql(u8, name, "Allocator") or std.mem.eql(u8, name, "Arena"))) {
// zbr:selfhost/Resolver.zbr:491
            return true;
        }
// zbr:selfhost/Resolver.zbr:492
        if (((std.mem.eql(u8, name, "Debug") or std.mem.eql(u8, name, "FixedBuffer")) or std.mem.eql(u8, name, "StackFallback"))) {
// zbr:selfhost/Resolver.zbr:493
            return true;
        }
// zbr:selfhost/Resolver.zbr:494
        if (((std.mem.eql(u8, name, "Page") or std.mem.eql(u8, name, "Smp")) or std.mem.eql(u8, name, "C"))) {
// zbr:selfhost/Resolver.zbr:495
            return true;
        }
// zbr:selfhost/Resolver.zbr:496
        if (self.isSimdName(name)) {
// zbr:selfhost/Resolver.zbr:497
            return true;
        }
// zbr:selfhost/Resolver.zbr:498
        return false;
    }

    // zbr:selfhost/Resolver.zbr:500
    pub fn isSimdName(self: *_zbr_ty_Resolver, name: []const u8) bool {
        _ = self;
// zbr:selfhost/Resolver.zbr:502
        if ((!(std.mem.indexOf(u8, name, "x") != null))) {
// zbr:selfhost/Resolver.zbr:503
            return false;
        }
// zbr:selfhost/Resolver.zbr:504
        const parts: _ZbrList([]const u8) = blk092_2: { var _ll_2: _ZbrList([]const u8) = _zbr_new(_ZbrList([]const u8)); var _split_iter_2 = std.mem.splitSequence(u8, name, "x"); while (_split_iter_2.next()) |_se_2| { _ll_2.append(_zbr_rt._allocator, _se_2) catch @panic("OOM"); } break :blk092_2 _ll_2; };
// zbr:selfhost/Resolver.zbr:505
        if ((@as(i64, @intCast(parts.items.len)) != 2)) {
// zbr:selfhost/Resolver.zbr:506
            return false;
        }
// zbr:selfhost/Resolver.zbr:507
        if (std.mem.eql(u8, _zbr_at(parts.items, 1), "")) {
// zbr:selfhost/Resolver.zbr:508
            return false;
        }
// zbr:selfhost/Resolver.zbr:509
        const prefix: []const u8 = _zbr_at(parts.items, 0);
// zbr:selfhost/Resolver.zbr:510
        if (((std.mem.eql(u8, prefix, "f16") or std.mem.eql(u8, prefix, "f32")) or std.mem.eql(u8, prefix, "f64"))) {
// zbr:selfhost/Resolver.zbr:511
            return true;
        }
// zbr:selfhost/Resolver.zbr:512
        if ((((std.mem.eql(u8, prefix, "i8") or std.mem.eql(u8, prefix, "i16")) or std.mem.eql(u8, prefix, "i32")) or std.mem.eql(u8, prefix, "i64"))) {
// zbr:selfhost/Resolver.zbr:513
            return true;
        }
// zbr:selfhost/Resolver.zbr:514
        if ((((std.mem.eql(u8, prefix, "u8") or std.mem.eql(u8, prefix, "u16")) or std.mem.eql(u8, prefix, "u32")) or std.mem.eql(u8, prefix, "u64"))) {
// zbr:selfhost/Resolver.zbr:515
            return true;
        }
// zbr:selfhost/Resolver.zbr:516
        if (std.mem.eql(u8, prefix, "bool")) {
// zbr:selfhost/Resolver.zbr:517
            return true;
        }
// zbr:selfhost/Resolver.zbr:518
        return false;
    }

};
const _ttag_Resolver: u64 = _zbr_hash("Resolver");
const _reflect_Resolver_name: []const u8 = "Resolver";
const _reflect_Resolver_fields: []const []const u8 = &.{"module_scope", "class_scope", "method_scope", "errors", "symbol_count", "file_name", "source"};
const _reflect_Resolver_field_types: []const []const u8 = &.{"HashMap(str, int)", "HashMap(str, int)", "HashMap(str, int)", "List(ResolveError)", "int", "str", "str"};

// zbr:selfhost/Resolver.zbr:522
pub fn main(_zinit: std.process.Init) void {
    _zbr_rt._io = _zinit.io;
    _zbr_rt._args = _zinit.minimal.args;
    _zbr_rt._environ = _zinit.minimal.environ;
    _zbr_rt._allocator = _prog_alloc();
    defer _zbr_rt._arena.deinit();
    _initModuleVars();
// zbr:selfhost/Resolver.zbr:523
    _zbr_print("{s}\n", .{"resolver: loaded (run resolver_test.zbr to exercise)"});
}

const _ReflectStrSlice = struct { items: []const []const u8, fn count(self: @This()) i64 { return @intCast(self.items.len); } fn at(self: @This(), i: i64) []const u8 { return self.items[@intCast(i)]; } };
fn _reflect_lookup_name(tag: u64) []const u8 {
    if (tag == _ttag_Resolver) return _reflect_Resolver_name;
    return "unknown";
}
fn _reflect_lookup_fields(tag: u64) _ReflectStrSlice {
    if (tag == _ttag_Resolver) return .{ .items = _reflect_Resolver_fields };
    return .{ .items = &.{} };
}
fn _reflect_lookup_field_types(tag: u64) _ReflectStrSlice {
    if (tag == _ttag_Resolver) return .{ .items = _reflect_Resolver_field_types };
    return .{ .items = &.{} };
}
var _module_vars_inited: bool = false;
pub fn _initModuleVars() void {
    if (_module_vars_inited) return;
    _module_vars_inited = true;
}
