#!/usr/bin/env bash
# bootstrap_check.sh — verify selfhost round-trip and level-2 fixed point.
#
# Usage:
#   tools/bootstrap_check.sh           # full 5-step round-trip (commit gate)
#   tools/bootstrap_check.sh --quick   # stop after step 2 (iterative rebuild)
#
# What it does (full mode):
#   1. Regenerates all selfhost .zig files from the Zig-compiled zebra into
#      /tmp/bs-zig (leaving selfhost/*.zig untouched at this stage).
#   2. Builds zebra-selfhost-A.exe from /tmp/bs-zig.
#   3. Has A re-emit into selfhost/ + /tmp/bs-A snapshots; diff baseline.
#   4. Builds zebra-selfhost-B.exe from the selfhost-A-emitted selfhost/.
#   5. Has B re-emit; diffs /tmp/bs-A against /tmp/bs-B.
#
# Quick mode runs only steps 1+2 and exits. Use it for iterative work after
# editing selfhost/*.zbr — you get a fresh zebra-selfhost.exe in ~10s without
# the A/B round-trip. selfhost/*.zig is never touched in quick mode, so the
# working tree stays clean. Run full mode before commit.
#
# Why this flag exists: running `zebra --emit-zig selfhost/X.zbr` manually and
# copying into selfhost/X.zig mixes zebra-shape output (with prologue/
# entry-thunk) against selfhost-shape neighbors (dep-shape), causing runtime
# crashes. Always regenerate the whole set; --quick is the guarded way.
#
# Prerequisites: zig build has already produced zig-out/bin/zebra.exe.
#
# Safety: in full mode, selfhost/*.zig is snapshotted at start; on ERR/INT
# the snapshot is restored so a failed bootstrap never leaves the working
# tree in half-emitted state. A successful full run leaves selfhost/*.zig
# in the deterministic selfhost-B-emitted fixed point. Quick mode never
# writes to selfhost/.

set -euo pipefail

QUICK=0
for arg in "$@"; do
    case "$arg" in
        --quick) QUICK=1 ;;
        -h|--help)
            sed -n '2,32p' "$0"
            exit 0
            ;;
        *)
            echo "bootstrap_check: unknown argument: $arg" >&2
            echo "  usage: $0 [--quick]" >&2
            exit 2
            ;;
    esac
done

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
REPO="$(cd "$SCRIPT_DIR/.." && pwd)"
cd "$REPO"

ZEBRA="$REPO/zig-out/bin/zebra.exe"
SELFHOST_A="$REPO/zig-out/bin/zebra-selfhost.exe"
SELFHOST_B="$REPO/zig-out/bin/zebra-selfhost-B.exe"

# typechecker is part of the selfhost dep graph as of Phase 16c. It is
# included here so the round-trip fixed-point check covers it.
FILES=(Token Lexer ast parser resolver astbuilder cg_helpers typechecker codegen main)

if [[ ! -x "$ZEBRA" ]]; then
    echo "bootstrap_check: $ZEBRA missing. Run 'zbuild' first." >&2
    exit 1
fi

# ── Safety net: snapshot selfhost/*.zig up front; restore on premature exit.
# A clean successful run leaves selfhost/ in the fixed-point state without
# restore. A failure (build error, interrupt) puts the tree back to the
# pre-bootstrap state rather than leaving half-emitted intermediates.
# Quick mode skips this because it never writes to selfhost/.
if [[ $QUICK -eq 0 ]]; then
    BS_PRE=/tmp/bs-pre
    rm -rf "$BS_PRE"
    mkdir -p "$BS_PRE"
    for f_zig in selfhost/*.zig; do
        cp "$f_zig" "$BS_PRE/$(basename "$f_zig")"
    done

    restore_selfhost() {
        local ec=$?
        if [[ $ec -ne 0 ]]; then
            echo "bootstrap_check: restoring selfhost/*.zig from pre-run snapshot ($BS_PRE)" >&2
            for f_zig in "$BS_PRE"/*.zig; do
                cp "$f_zig" "selfhost/$(basename "$f_zig")"
            done
        fi
    }
    trap restore_selfhost EXIT INT
fi

echo "── Step 1: regenerate .zig into /tmp/bs-zig (zebra — Zig-compiled compiler)"
# Emit into /tmp/bs-zig instead of selfhost/ so the checked-in selfhost/*.zig
# is never polluted with zebra's header style ("Generated by the Zebra
# compiler."). This keeps `git status` readable during bootstrap: any dirt
# in selfhost/ is genuinely from the selfhost pass in steps 3/5.
BS_ZIG=/tmp/bs-zig
rm -rf "$BS_ZIG"
mkdir -p "$BS_ZIG"
for f in "${FILES[@]}"; do
    "$ZEBRA" --emit-zig "selfhost/$f.zbr" > "$BS_ZIG/$f.zig" 2>/dev/null
done

echo "── Step 2: build selfhost-A (from /tmp/bs-zig)"
rm -f "$SELFHOST_A"
if ! zig build-exe "$BS_ZIG/main.zig" -femit-bin="$SELFHOST_A" 2>/tmp/bs-rebuildA.err; then
    echo "FAIL: selfhost-A build errors:" >&2
    head -30 /tmp/bs-rebuildA.err >&2
    exit 1
fi

if [[ $QUICK -eq 1 ]]; then
    echo "PASS: quick rebuild — zebra-selfhost.exe rebuilt from selfhost/*.zbr (round-trip skipped)"
    exit 0
fi

echo "── Step 3: selfhost-A re-emits its own source"
mkdir -p /tmp/bs-A /tmp/bs-B
for f in "${FILES[@]}"; do
    "$SELFHOST_A" --emit-zig "selfhost/$f.zbr" >/dev/null 2>/dev/null
    # Stash the root emit immediately — subsequent iterations recompile $f as a
    # dep of some other file, overwriting selfhost/$f.zig with a dep-shaped
    # version (no entry thunk, no _zbr_error_msg helper).
    cp "selfhost/$f.zig" "/tmp/bs-A/$f.zig"
done

echo "── Step 4: build selfhost-B (level-2 bootstrap)"
rm -f "$SELFHOST_B"
if ! zig build-exe selfhost/main.zig -femit-bin="$SELFHOST_B" 2>/tmp/bs-rebuildB.err; then
    echo "FAIL: selfhost-B build errors:" >&2
    grep -E "^selfhost[\\\\/].+:[0-9]+:[0-9]+: error:" /tmp/bs-rebuildB.err >&2 || head -30 /tmp/bs-rebuildB.err >&2
    exit 1
fi

echo "── Step 5: selfhost-B re-emits + diff against selfhost-A output"
for f in "${FILES[@]}"; do
    "$SELFHOST_B" --emit-zig "selfhost/$f.zbr" >/dev/null 2>/dev/null
    cp "selfhost/$f.zig" "/tmp/bs-B/$f.zig"
done

DIVERGENT=0
for f in "${FILES[@]}"; do
    if ! diff -q "/tmp/bs-A/$f.zig" "/tmp/bs-B/$f.zig" >/dev/null; then
        echo "DIVERGENT: $f.zig"
        DIVERGENT=$((DIVERGENT+1))
    fi
done

if [[ $DIVERGENT -ne 0 ]]; then
    echo "FAIL: $DIVERGENT file(s) diverge between selfhost-A and selfhost-B" >&2
    exit 1
fi

# Tree is left in selfhost-B-emitted state: main.zig as root (with entry
# thunk + _zbr_error_msg), everything else last-written as a dep of main.
# This is the deterministic fixed point, so subsequent runs produce no diff.
# (We used to restore to zebra-emitted form here, but zebra leaks pointer
# addresses into _box_<hex>/_bp_<hex> identifier names — see BUGS.md — so
# every bootstrap run would dirty the working tree.)

echo "PASS: round-trip clean, selfhost-B produces output byte-identical to selfhost-A"
