#!/usr/bin/env bash
# REGENERATE selfhost/*.zig USING THE SELFHOST (N-1 bootstrapping).
#
#   bash tools/regen_selfhost.sh            # emit + validate ONLY, touch nothing
#   bash tools/regen_selfhost.sh --apply    # ...then atomically move into selfhost/
#
# This is the bootstrap sunset's criterion 2. Until now `selfhost/*.zig` were emitted by
# zebra-bootstrap.exe, and that job is the last thing keeping a second compiler
# implementation alive.
#
# WHY THIS IS SAFE, given bootstrap_check.sh's standing objection ("using selfhost-A to
# regenerate itself is chicken-and-egg -- a codegen bug in CodeGen.zbr would reproduce
# itself"). That objection is real and is answered by N-1 rather than dismissed: stage-0 is
# the compiler built from the COMMITTED .zig, i.e. one we did not just build, exactly as
# GCC/Rust/Go take stage-0 from a previous release. The Thompson protection is that the
# generated files are TRACKED and the diff is reviewed. The round-trip (bootstrap_check
# steps 3-5) independently proves A's emit and B's emit agree.
#
# EMIT-ONLY BY DEFAULT. A regeneration that half-writes leaves a tree that builds the wrong
# compiler, and `doctor` calls that state one that makes results LIE. So this emits into
# scratch, validates every file, prints the diff size, and stops. `--apply` does the moves,
# and only after the same validation.
#
# --no-runtime-module is deliberate: it produces the INLINE shape the committed files use,
# so the diff is the genuine selfhost-vs-bootstrap emission difference rather than a shape
# change. Without it every file would be unrecognisably restructured and the diff -- which
# IS the review -- would be unreadable.
set -u

REPO="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
ZEBRA="$REPO/zig-out/bin/zebra.exe"
OUT="${TMPDIR:-/tmp}/zbr_regen"
APPLY=0
[ "${1:-}" = "--apply" ] && APPLY=1

FILES=(Token Lexer Ast AstWalk Parser Resolver AstBuilder CgHelpers TypeChecker CodeGen Checker main)
MIN_BYTES=5000

[ -x "$ZEBRA" ] || { echo "regen: REFUSING -- not built: $ZEBRA" >&2; exit 2; }

rm -rf "$OUT"; mkdir -p "$OUT"
echo "── regenerating ${#FILES[@]} module(s) with the SELFHOST (zebra.exe) ──"

for f in "${FILES[@]}"; do
    # --output-dir also BUILDS, which fails for library modules that have no main(). That
    # is expected and is NOT an emit failure, so the file is what gets checked, never rc.
    # RELATIVE PATH, FROM THE REPO ROOT, and this is not cosmetic: the compiler embeds the
    # path it was GIVEN into every `// zbr:<path>:<line>` provenance comment. Passing an
    # ABSOLUTE path changed ~29,000 lines in CodeGen.zig alone -- 78,997 across all twelve
    # modules -- every one of them a path prefix inside a comment. The emission is therefore
    # a function of HOW YOU INVOKE the compiler, not only of the source, which is a quiet
    # coupling: a regen script differing only in argument style produces a diff that reads
    # like a compiler change. The existing regen has always used a relative path; matching it
    # keeps this diff to the REAL emission difference.
    ( cd "$REPO" && "$ZEBRA" --output-dir "$OUT/$f" --no-runtime-module "selfhost/$f.zbr" ) \
        > "$OUT/$f.log" 2>&1 || true
done

fail=0
total_diff=0
printf '  %-14s %9s %9s %8s\n' module emitted committed diff
for f in "${FILES[@]}"; do
    src="$OUT/$f/$f.zig"
    dst="$REPO/selfhost/$f.zig"
    if [ ! -f "$src" ]; then
        printf '  %-14s %s\n' "$f" "MISSING — emit produced no file"
        tail -3 "$OUT/$f.log" | sed 's/^/      /'
        fail=$((fail + 1)); continue
    fi
    b=$(wc -c < "$src" | tr -d ' ')
    if [ "$b" -lt "$MIN_BYTES" ]; then
        printf '  %-14s %s\n' "$f" "TOO SMALL ($b bytes) — a truncated emit would build the wrong compiler"
        fail=$((fail + 1)); continue
    fi
    # A file that exists and is large can still be the WRONG file. The emit header is the
    # cheap proof it came from this compiler rather than being left over from something.
    if ! head -3 "$src" | grep -q 'Generated by'; then
        printf '  %-14s %s\n' "$f" "NO EMIT HEADER — not a generated file"
        fail=$((fail + 1)); continue
    fi
    d=$(diff "$src" "$dst" 2>/dev/null | grep -c '^[<>]')
    total_diff=$((total_diff + d))
    printf '  %-14s %9s %9s %8s\n' "$f" "$(wc -l < "$src" | tr -d ' ')" "$(wc -l < "$dst" | tr -d ' ')" "$d"
done

if [ "$fail" -gt 0 ]; then
    echo "regen: REFUSING -- $fail module(s) failed validation. Nothing moved." >&2
    exit 1
fi

echo "  total changed lines across all modules: $total_diff"
echo "  emissions kept in $OUT for review"

if [ "$APPLY" -eq 0 ]; then
    echo "regen: validated, NOTHING MOVED. Re-run with --apply to install."
    exit 0
fi

# Atomic-ish install: every file validated above, so a kill here leaves complete files.
for f in "${FILES[@]}"; do
    mv -f "$OUT/$f/$f.zig" "$REPO/selfhost/$f.zig"
done

# THE BUILD STAMP MUST BE REBUILT WITH THE BINARY, or `doctor` refuses every gate tier
# afterwards with "zebra.exe was NOT built from the generated Zig now on disk" -- which
# reads as a serious alarm and is in fact just a stale stamp. `doctor` compares
# sha1(selfhost/*.zig) against zig-out/.selfhost-stamp, and only tools/rebuild.sh writes it.
# A plain `zig build` leaves the old one in place, so the tree LOOKS untrustworthy while
# being fine. Observed on this tool's first real use, 2026-08-29.
echo "regen: applied."
echo
echo "  NEXT, and not optional:  bash tools/rebuild.sh --no-regen"
echo "  A plain \`zig build\` leaves zig-out/.selfhost-stamp describing the PREVIOUS"
echo "  sources, and doctor then refuses every gate tier. rebuild.sh --no-regen builds"
echo "  and re-stamps together."
