"""Extract stdlib method signatures from QUICKSTART into a checkable table (#5a).

WHY THIS AND NOT THE OBVIOUS ALTERNATIVE
----------------------------------------
Deriving arities from CodeGen is UNSOUND and was already tried: scanning each
`if mname == "X"` block for the highest `args.at(N)` it reads yields 292 method
names with WRONG numbers — `addDays 0`, `abs 0`, `ceil 0` — because codegen reads
arguments through several idioms (genArgList, loops, helpers) that an AST-free scan
cannot see. A wrong table produces FALSE errors on valid code, which is strictly
worse than no table at all. Do not revive that approach.

QUICKSTART's tables are the trustworthy source: the Signature column states the
argument types directly, so arity is read rather than inferred.

THE RECEIVER-KIND TRAP
----------------------
Rows are NOT owned by the section they appear under. `join` is documented in the
"String method reference" because that is where a reader looks for it, but it is a
`List(str)` method — its own description says so. An earlier pass that assumed the
receiver from the heading mis-reported this as a documentation bug. So every row
carries an explicit receiver KIND, and RECEIVER_OVERRIDES records the exceptions.

Rows that have no fixed arity to check are recorded with kind `-` and skipped by
the checker: `len` is a field, `format` is variadic, and `chars`/`bytes` are
for-only iterators that cannot be bound to a variable.

  python tools/stdlib_sig_extract.py            # rewrite tools/stdlib_signatures.tsv
  python tools/stdlib_sig_extract.py --check    # fail if the file is out of date
"""
import re
import sys
import pathlib

ROOT = pathlib.Path(__file__).resolve().parent.parent
QUICKSTART = ROOT / "QUICKSTART.md"
OUT = ROOT / "tools" / "stdlib_signatures.tsv"

# Section heading -> receiver kind for the rows beneath it.
SECTIONS = {"### String method reference": "str"}

# Rows whose receiver is NOT the section's. The reason is recorded per entry so a
# future reader does not "fix" it back.
RECEIVER_OVERRIDES = {
    "join": ("List(str)", "documented under str for discoverability; called on a list"),
}

# Rows with no fixed arity to compile-check.
UNCHECKABLE = {
    "len":    "field, not a call",
    "format": "variadic",
    "chars":  "for-only iterator; cannot be bound",
    "bytes":  "for-only iterator; cannot be bound",
}

ROW = re.compile(r"^\|\s*`([A-Za-z_][A-Za-z0-9_]*)\(?([^`)]*)\)?`\s*\|\s*(.+?)\s*\|")


def arity_of(sig):
    """Argument count from a Signature cell like `(str, int): int?`."""
    m = re.match(r"^`\((.*?)\)\s*:", sig)
    if m is None:
        return None
    inner = m.group(1).strip()
    if inner == "":
        return 0
    depth, n = 0, 1
    for ch in inner:
        if ch in "([":
            depth += 1
        elif ch in ")]":
            depth -= 1
        elif ch == "," and depth == 0:
            n += 1
    return n


def arg_types(sig):
    m = re.match(r"^`\((.*?)\)\s*:", sig)
    if m is None or m.group(1).strip() == "":
        return []
    parts, depth, cur = [], 0, ""
    for ch in m.group(1):
        if ch in "([":
            depth += 1
        elif ch in ")]":
            depth -= 1
        if ch == "," and depth == 0:
            parts.append(cur.strip()); cur = ""
        else:
            cur += ch
    parts.append(cur.strip())
    return parts


def extract():
    lines = QUICKSTART.read_text(encoding="utf-8").split("\n")
    rows, kind, seen = [], None, set()
    for line in lines:
        stripped = line.strip()
        if stripped.startswith("### "):
            kind = SECTIONS.get(stripped)
            continue
        if kind is None or not stripped.startswith("|"):
            continue
        m = ROW.match(stripped)
        if m is None:
            continue
        name, _params, sig = m.group(1), m.group(2), m.group(3)
        if name in ("Method",):
            continue
        recv, note = kind, ""
        if name in RECEIVER_OVERRIDES:
            recv, note = RECEIVER_OVERRIDES[name]
        if name in UNCHECKABLE:
            rows.append((("-"), name, "-", "", UNCHECKABLE[name]))
            continue
        n = arity_of(sig)
        if n is None:
            continue
        key = (recv, name)
        if key in seen:
            continue
        seen.add(key)
        rows.append((recv, name, str(n), ",".join(arg_types(sig)), note))
    return rows


def render(rows):
    out = ["# GENERATED by tools/stdlib_sig_extract.py from QUICKSTART.md — do not hand-edit.",
           "# Validate with: python tools/stdlib_sig_check.py",
           "# recv_kind\tmethod\tarity\targ_types\tnote   ('-' recv = no fixed arity to check)"]
    for r in rows:
        out.append("\t".join(r).rstrip("\t"))
    return "\n".join(out) + "\n"


def main():
    rows = extract()
    text = render(rows)
    checkable = [r for r in rows if r[0] != "-"]
    if "--check" in sys.argv:
        if not OUT.exists() or OUT.read_text(encoding="utf-8") != text:
            print("stdlib_signatures.tsv is out of date — rerun without --check")
            return 1
        print("stdlib_signatures.tsv up to date (%d checkable rows)" % len(checkable))
        return 0
    OUT.write_text(text, encoding="utf-8", newline="\n")
    print("wrote %s: %d rows (%d checkable, %d skipped)"
          % (OUT.name, len(rows), len(checkable), len(rows) - len(checkable)))
    return 0


if __name__ == "__main__":
    sys.exit(main())
